// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DokumenPendukung struct {
	ID          int64       `db:"id"`
	NamaTombol  string      `db:"nama_tombol"`
	NamaHalaman string      `db:"nama_halaman"`
	File        []byte      `db:"file"`
	UpdatedBy   pgtype.Text `db:"updated_by"`
	UpdatedAt   pgtype.Date `db:"updated_at"`
}

type Pemberitahuan struct {
	ID              int64       `db:"id"`
	JudulBerita     string      `db:"judul_berita"`
	DeskripsiBerita string      `db:"deskripsi_berita"`
	Status          string      `db:"status"`
	UpdatedBy       string      `db:"updated_by"`
	UpdatedAt       pgtype.Date `db:"updated_at"`
}

type Permission struct {
	ID        int16              `db:"id"`
	Kode      string             `db:"kode"`
	Nama      string             `db:"nama"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at"`
}

type Resource struct {
	ID        int16              `db:"id"`
	Service   string             `db:"service"`
	Kode      string             `db:"kode"`
	Nama      string             `db:"nama"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at"`
}

type ResourcePermission struct {
	ID           int32              `db:"id"`
	Kode         pgtype.Text        `db:"kode"`
	ResourceID   int16              `db:"resource_id"`
	PermissionID int16              `db:"permission_id"`
	CreatedAt    pgtype.Timestamptz `db:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at"`
}

type Role struct {
	ID int16 `db:"id"`
	// deprecated
	Service   pgtype.Text        `db:"service"`
	Nama      string             `db:"nama"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at"`
	Deskripsi pgtype.Text        `db:"deskripsi"`
	IsDefault bool               `db:"is_default"`
}

type RoleResourcePermission struct {
	ID                   int32              `db:"id"`
	RoleID               int16              `db:"role_id"`
	ResourcePermissionID int32              `db:"resource_permission_id"`
	CreatedAt            pgtype.Timestamptz `db:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at"`
	DeletedAt            pgtype.Timestamptz `db:"deleted_at"`
}

type User struct {
	ID             pgtype.UUID        `db:"id"`
	Source         string             `db:"source"`
	Nip            string             `db:"nip"`
	CreatedAt      pgtype.Timestamptz `db:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at"`
	DeletedAt      pgtype.Timestamptz `db:"deleted_at"`
	Email          pgtype.Text        `db:"email"`
	Nama           pgtype.Text        `db:"nama"`
	UnitOrganisasi pgtype.Text        `db:"unit_organisasi"`
}

type UserRole struct {
	ID        int32              `db:"id"`
	Nip       string             `db:"nip"`
	RoleID    int16              `db:"role_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at"`
}
