// Code generated by sqlc. DO NOT EDIT.
// source: user.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserNIPByIDAndSource = `-- name: GetUserNIPByIDAndSource :one
select nip from "user"
where id = $1 and source = $2 and deleted_at is null
`

type GetUserNIPByIDAndSourceParams struct {
	ID     pgtype.UUID `db:"id"`
	Source string      `db:"source"`
}

func (q *Queries) GetUserNIPByIDAndSource(ctx context.Context, arg GetUserNIPByIDAndSourceParams) (string, error) {
	row := q.db.QueryRow(ctx, getUserNIPByIDAndSource, arg.ID, arg.Source)
	var nip string
	err := row.Scan(&nip)
	return nip, err
}

const listUserRoleByNIP = `-- name: ListUserRoleByNIP :many
select distinct on (r.service)
  r.service,
  r.nama
from user_role ur
join role r on r.id = ur.role_id and r.deleted_at is null
where ur.nip = $1 and ur.deleted_at is null
order by r.service, ur.updated_at desc
`

type ListUserRoleByNIPRow struct {
	Service string `db:"service"`
	Nama    string `db:"nama"`
}

func (q *Queries) ListUserRoleByNIP(ctx context.Context, nip string) ([]ListUserRoleByNIPRow, error) {
	rows, err := q.db.Query(ctx, listUserRoleByNIP, nip)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserRoleByNIPRow
	for rows.Next() {
		var i ListUserRoleByNIPRow
		if err := rows.Scan(&i.Service, &i.Nama); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
