name: Feature Request
description: Suggest an idea for this project
title: "[FEAT] <TITLE>"
labels:
  - enhancement
  - feature-request
assignees:
  - gisketch
  - DrKJeff16

body:
  - type: checkboxes
    attributes:
      label: Validation Checks
      description: Tick all the checkboxes below to validate your issue.
      options:
        - label: I have read the docs (`README.md`, etc.)
          required: true
        - label: I have checked for existing issues related to this one, whether open or closed
          required: true

  - type: input
    attributes:
      label: OS and Version
      placeholder: Linux 6.15.6-arch1-1
    validations:
      required: true

  - type: textarea
    attributes:
      label: Your Suggestion
      description: Write down, as detailed as you can, what is it that you'd like integrated.
    validations:
      required: true

  - type: textarea
    attributes:
      label: How Would This Improve the Plugin?
      description: |
        Describe clearly how would this plugin benefit from your suggestion
        (and what kinds of users, if applicable).
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternative Solutions
      description: Please describe any alternative solutions you have considered, if applicable.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Code Implementation
      description: If you can, please include your solution in Lua code.
      value: |
        -- LEAVE THIS UNCHANGED IF THERE IS NO CODE YOU CAN INCLUDE
        require('triforce.foo').bar()
      render: lua
    validations:
      required: false

  - type: textarea
    attributes:
      label: Issues Fixed by This
      description: If applicable, please link any issue that your suggestion could fix.
      placeholder: |
        - #1
        - #2
        ...
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Context
      description: If there's more info you could tell, please do. Screenshots too, if applicable.
    validations:
      required: false
