// Code generated by sqlc. DO NOT EDIT.
// source: jenis_kp.sql

package repository

import (
	"context"
	"database/sql"
)

const getJenisKP = `-- name: GetJenisKP :many
SELECT id, nama FROM ref_jenis_kp
LIMIT $1 OFFSET $2
`

type GetJenisKPParams struct {
	Limit  int32 `db:"limit"`
	Offset int32 `db:"offset"`
}

type GetJenisKPRow struct {
	ID   int32          `db:"id"`
	Nama sql.NullString `db:"nama"`
}

func (q *Queries) GetJenisKP(ctx context.Context, arg GetJenisKPParams) ([]GetJenisKPRow, error) {
	rows, err := q.db.Query(ctx, getJenisKP, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetJenisKPRow
	for rows.Next() {
		var i GetJenisKPRow
		if err := rows.Scan(&i.ID, &i.Nama); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
