// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"database/sql"

	"github.com/google/uuid"
)

type Anak struct {
	ID           int64          `db:"id"`
	PasanganID   sql.NullInt64  `db:"pasangan_id"`
	Nama         sql.NullString `db:"nama"`
	JenisKelamin sql.NullString `db:"jenis_kelamin"`
	TanggalLahir sql.NullTime   `db:"tanggal_lahir"`
	TempatLahir  sql.NullString `db:"tempat_lahir"`
	StatusAnak   sql.NullString `db:"status_anak"`
	PnsID        sql.NullString `db:"pns_id"`
	Nip          sql.NullString `db:"nip"`
	CreatedAt    sql.NullTime   `db:"created_at"`
	UpdatedAt    sql.NullTime   `db:"updated_at"`
	DeletedAt    sql.NullTime   `db:"deleted_at"`
}

type OrangTua struct {
	ID            int32          `db:"id"`
	Hubungan      sql.NullInt16  `db:"hubungan"`
	AkteMeninggal sql.NullString `db:"akte_meninggal"`
	TglMeninggal  sql.NullTime   `db:"tgl_meninggal"`
	Nama          sql.NullString `db:"nama"`
	GelarDepan    sql.NullString `db:"gelar_depan"`
	GelarBelakang sql.NullString `db:"gelar_belakang"`
	TempatLahir   sql.NullString `db:"tempat_lahir"`
	TanggalLahir  sql.NullTime   `db:"tanggal_lahir"`
	AgamaID       sql.NullInt16  `db:"agama_id"`
	Email         sql.NullString `db:"email"`
	JenisDokumen  sql.NullString `db:"jenis_dokumen"`
	NoDokumen     sql.NullString `db:"no_dokumen"`
	Nip           sql.NullString `db:"nip"`
	PnsID         sql.NullString `db:"pns_id"`
	CreatedAt     sql.NullTime   `db:"created_at"`
	UpdatedAt     sql.NullTime   `db:"updated_at"`
	DeletedAt     sql.NullTime   `db:"deleted_at"`
}

type Pasangan struct {
	ID               int64          `db:"id"`
	Pns              sql.NullInt16  `db:"pns"`
	Nama             sql.NullString `db:"nama"`
	TanggalMenikah   sql.NullTime   `db:"tanggal_menikah"`
	AkteNikah        sql.NullString `db:"akte_nikah"`
	TanggalMeninggal sql.NullTime   `db:"tanggal_meninggal"`
	AkteMeninggal    sql.NullString `db:"akte_meninggal"`
	TanggalCerai     sql.NullTime   `db:"tanggal_cerai"`
	AkteCerai        sql.NullString `db:"akte_cerai"`
	Karsus           sql.NullString `db:"karsus"`
	Status           sql.NullInt16  `db:"status"`
	Hubungan         sql.NullInt16  `db:"hubungan"`
	PnsID            sql.NullString `db:"pns_id"`
	Nip              sql.NullString `db:"nip"`
	CreatedAt        sql.NullTime   `db:"created_at"`
	UpdatedAt        sql.NullTime   `db:"updated_at"`
	DeletedAt        sql.NullTime   `db:"deleted_at"`
}

type Pegawai struct {
	ID                    int32          `db:"id"`
	PnsID                 string         `db:"pns_id"`
	NipLama               sql.NullString `db:"nip_lama"`
	NipBaru               sql.NullString `db:"nip_baru"`
	Nama                  sql.NullString `db:"nama"`
	GelarDepan            sql.NullString `db:"gelar_depan"`
	GelarBelakang         sql.NullString `db:"gelar_belakang"`
	TempatLahirID         sql.NullString `db:"tempat_lahir_id"`
	TglLahir              sql.NullTime   `db:"tgl_lahir"`
	JenisKelamin          sql.NullString `db:"jenis_kelamin"`
	AgamaID               sql.NullInt16  `db:"agama_id"`
	JenisKawinID          sql.NullInt16  `db:"jenis_kawin_id"`
	Nik                   sql.NullString `db:"nik"`
	NoDarurat             sql.NullString `db:"no_darurat"`
	NoHp                  sql.NullString `db:"no_hp"`
	Email                 sql.NullString `db:"email"`
	Alamat                sql.NullString `db:"alamat"`
	Npwp                  sql.NullString `db:"npwp"`
	Bpjs                  sql.NullString `db:"bpjs"`
	JenisPegawaiID        sql.NullInt16  `db:"jenis_pegawai_id"`
	KedudukanHukumID      sql.NullInt32  `db:"kedudukan_hukum_id"`
	StatusCpnsPns         sql.NullString `db:"status_cpns_pns"`
	KartuPegawai          sql.NullString `db:"kartu_pegawai"`
	NoSkCpns              sql.NullString `db:"no_sk_cpns"`
	TglSkCpns             sql.NullTime   `db:"tgl_sk_cpns"`
	TmtCpns               sql.NullTime   `db:"tmt_cpns"`
	TmtPns                sql.NullTime   `db:"tmt_pns"`
	GolAwalID             sql.NullInt16  `db:"gol_awal_id"`
	GolID                 sql.NullInt16  `db:"gol_id"`
	TmtGolongan           sql.NullTime   `db:"tmt_golongan"`
	MkTahun               sql.NullInt16  `db:"mk_tahun"`
	MkBulan               sql.NullInt16  `db:"mk_bulan"`
	JabatanID             sql.NullString `db:"jabatan_id"`
	TmtJabatan            sql.NullTime   `db:"tmt_jabatan"`
	PendidikanID          sql.NullString `db:"pendidikan_id"`
	TahunLulus            sql.NullInt16  `db:"tahun_lulus"`
	KpknID                sql.NullString `db:"kpkn_id"`
	LokasiKerjaID         sql.NullString `db:"lokasi_kerja_id"`
	UnorID                sql.NullString `db:"unor_id"`
	UnorIndukID           sql.NullString `db:"unor_induk_id"`
	InstansiIndukID       sql.NullString `db:"instansi_induk_id"`
	InstansiKerjaID       sql.NullString `db:"instansi_kerja_id"`
	SatuanKerjaIndukID    sql.NullString `db:"satuan_kerja_induk_id"`
	SatuanKerjaKerjaID    sql.NullString `db:"satuan_kerja_kerja_id"`
	GolonganDarah         sql.NullString `db:"golongan_darah"`
	Foto                  sql.NullString `db:"foto"`
	TmtPensiun            sql.NullTime   `db:"tmt_pensiun"`
	LokasiKerja           sql.NullString `db:"lokasi_kerja"`
	JmlIstri              sql.NullInt16  `db:"jml_istri"`
	JmlAnak               sql.NullInt16  `db:"jml_anak"`
	NoSuratDokter         sql.NullString `db:"no_surat_dokter"`
	TglSuratDokter        sql.NullTime   `db:"tgl_surat_dokter"`
	NoBebasNarkoba        sql.NullString `db:"no_bebas_narkoba"`
	TglBebasNarkoba       sql.NullTime   `db:"tgl_bebas_narkoba"`
	NoCatatanPolisi       sql.NullString `db:"no_catatan_polisi"`
	TglCatatanPolisi      sql.NullTime   `db:"tgl_catatan_polisi"`
	AkteKelahiran         sql.NullString `db:"akte_kelahiran"`
	StatusHidup           sql.NullString `db:"status_hidup"`
	AkteMeninggal         sql.NullString `db:"akte_meninggal"`
	TglMeninggal          sql.NullTime   `db:"tgl_meninggal"`
	NoAskes               sql.NullString `db:"no_askes"`
	NoTaspen              sql.NullString `db:"no_taspen"`
	TglNpwp               sql.NullTime   `db:"tgl_npwp"`
	TempatLahir           sql.NullString `db:"tempat_lahir"`
	TingkatPendidikanID   sql.NullInt16  `db:"tingkat_pendidikan_id"`
	TempatLahirNama       sql.NullString `db:"tempat_lahir_nama"`
	JenisJabatanNama      sql.NullString `db:"jenis_jabatan_nama"`
	JabatanNama           sql.NullString `db:"jabatan_nama"`
	KpknNama              sql.NullString `db:"kpkn_nama"`
	InstansiIndukNama     sql.NullString `db:"instansi_induk_nama"`
	InstansiKerjaNama     sql.NullString `db:"instansi_kerja_nama"`
	SatuanKerjaIndukNama  sql.NullString `db:"satuan_kerja_induk_nama"`
	SatuanKerjaNama       sql.NullString `db:"satuan_kerja_nama"`
	JabatanInstansiID     sql.NullInt32  `db:"jabatan_instansi_id"`
	Bup                   sql.NullInt16  `db:"bup"`
	JabatanInstansiNama   sql.NullString `db:"jabatan_instansi_nama"`
	JenisJabatanID        sql.NullInt16  `db:"jenis_jabatan_id"`
	TerminatedDate        sql.NullTime   `db:"terminated_date"`
	StatusPegawai         sql.NullInt16  `db:"status_pegawai"`
	JabatanPpnpn          sql.NullString `db:"jabatan_ppnpn"`
	JabatanInstansiRealID sql.NullInt32  `db:"jabatan_instansi_real_id"`
	CreatedBy             sql.NullInt32  `db:"created_by"`
	UpdatedBy             sql.NullInt32  `db:"updated_by"`
	EmailDikbudBak        sql.NullString `db:"email_dikbud_bak"`
	EmailDikbud           sql.NullString `db:"email_dikbud"`
	Kodecepat             sql.NullString `db:"kodecepat"`
	IsDosen               sql.NullInt16  `db:"is_dosen"`
	MkTahunSwasta         sql.NullInt16  `db:"mk_tahun_swasta"`
	MkBulanSwasta         sql.NullInt16  `db:"mk_bulan_swasta"`
	Kk                    sql.NullString `db:"kk"`
	Nidn                  sql.NullString `db:"nidn"`
	Ket                   sql.NullString `db:"ket"`
	NoSkPemberhentian     sql.NullString `db:"no_sk_pemberhentian"`
	StatusPegawaiBackup   sql.NullInt16  `db:"status_pegawai_backup"`
	MasaKerja             sql.NullString `db:"masa_kerja"`
	KartuAsn              sql.NullString `db:"kartu_asn"`
	CreatedAt             sql.NullTime   `db:"created_at"`
	UpdatedAt             sql.NullTime   `db:"updated_at"`
	DeletedAt             sql.NullTime   `db:"deleted_at"`
}

type Pendidikan struct {
	ID                  string         `db:"id"`
	TingkatPendidikanID sql.NullInt16  `db:"tingkat_pendidikan_id"`
	Nama                sql.NullString `db:"nama"`
	CreatedAt           sql.NullTime   `db:"created_at"`
	UpdatedAt           sql.NullTime   `db:"updated_at"`
	DeletedAt           sql.NullTime   `db:"deleted_at"`
}

type PindahUnit struct {
	ID                      int32          `db:"id"`
	Nip                     string         `db:"nip"`
	SuratPermohonanPindah   sql.NullString `db:"surat_permohonan_pindah"`
	UnitAsal                sql.NullString `db:"unit_asal"`
	UnitTujuan              sql.NullString `db:"unit_tujuan"`
	SuratPernyataanMelepas  sql.NullString `db:"surat_pernyataan_melepas"`
	SkKpTerakhir            sql.NullString `db:"sk_kp_terakhir"`
	SkJabatan               sql.NullString `db:"sk_jabatan"`
	Skp                     sql.NullString `db:"skp"`
	SkTunkin                sql.NullString `db:"sk_tunkin"`
	SuratPernyataanMenerima sql.NullString `db:"surat_pernyataan_menerima"`
	NoSkPindah              sql.NullString `db:"no_sk_pindah"`
	TanggalSkPindah         sql.NullTime   `db:"tanggal_sk_pindah"`
	FileSk                  sql.NullString `db:"file_sk"`
	StatusSatker            sql.NullInt16  `db:"status_satker"`
	StatusBiro              sql.NullInt16  `db:"status_biro"`
	JabatanID               sql.NullInt16  `db:"jabatan_id"`
	Keterangan              sql.NullString `db:"keterangan"`
	TanggalTmtPindah        sql.NullTime   `db:"tanggal_tmt_pindah"`
	CreatedBy               sql.NullInt32  `db:"created_by"`
	CreatedAt               sql.NullTime   `db:"created_at"`
	UpdatedAt               sql.NullTime   `db:"updated_at"`
	DeletedAt               sql.NullTime   `db:"deleted_at"`
}

type RefAgama struct {
	ID        int32          `db:"id"`
	Nama      sql.NullString `db:"nama"`
	CreatedAt sql.NullTime   `db:"created_at"`
	UpdatedAt sql.NullTime   `db:"updated_at"`
	DeletedAt sql.NullTime   `db:"deleted_at"`
}

type RefGolongan struct {
	ID          int32          `db:"id"`
	Nama        sql.NullString `db:"nama"`
	NamaPangkat sql.NullString `db:"nama_pangkat"`
	Nama2       sql.NullString `db:"nama_2"`
	Gol         sql.NullInt16  `db:"gol"`
	GolPppk     sql.NullString `db:"gol_pppk"`
	CreatedAt   sql.NullTime   `db:"created_at"`
	UpdatedAt   sql.NullTime   `db:"updated_at"`
	DeletedAt   sql.NullTime   `db:"deleted_at"`
}

type RefInstansi struct {
	ID        string         `db:"id"`
	Nama      sql.NullString `db:"nama"`
	CreatedAt sql.NullTime   `db:"created_at"`
	UpdatedAt sql.NullTime   `db:"updated_at"`
	DeletedAt sql.NullTime   `db:"deleted_at"`
}

type RefJabatan struct {
	KodeJabatan     string         `db:"kode_jabatan"`
	ID              int32          `db:"id"`
	No              int32          `db:"no"`
	NamaJabatan     sql.NullString `db:"nama_jabatan"`
	NamaJabatanFull sql.NullString `db:"nama_jabatan_full"`
	JenisJabatan    sql.NullInt16  `db:"jenis_jabatan"`
	Kelas           sql.NullInt16  `db:"kelas"`
	Pensiun         sql.NullInt16  `db:"pensiun"`
	KodeBkn         sql.NullString `db:"kode_bkn"`
	NamaJabatanBkn  sql.NullString `db:"nama_jabatan_bkn"`
	KategoriJabatan sql.NullString `db:"kategori_jabatan"`
	BknID           sql.NullString `db:"bkn_id"`
	CreatedAt       sql.NullTime   `db:"created_at"`
	UpdatedAt       sql.NullTime   `db:"updated_at"`
	DeletedAt       sql.NullTime   `db:"deleted_at"`
}

type RefJenisDiklat struct {
	ID          int32          `db:"id"`
	BknID       sql.NullInt16  `db:"bkn_id"`
	JenisDiklat sql.NullString `db:"jenis_diklat"`
	Kode        sql.NullString `db:"kode"`
	Status      sql.NullInt16  `db:"status"`
	CreatedAt   sql.NullTime   `db:"created_at"`
	UpdatedAt   sql.NullTime   `db:"updated_at"`
	DeletedAt   sql.NullTime   `db:"deleted_at"`
}

type RefJenisDiklatFungsional struct {
	ID        int32          `db:"id"`
	Nama      sql.NullString `db:"nama"`
	CreatedAt sql.NullTime   `db:"created_at"`
	UpdatedAt sql.NullTime   `db:"updated_at"`
	DeletedAt sql.NullTime   `db:"deleted_at"`
}

type RefJenisDiklatStruktural struct {
	ID        int32          `db:"id"`
	Nama      sql.NullString `db:"nama"`
	CreatedAt sql.NullTime   `db:"created_at"`
	UpdatedAt sql.NullTime   `db:"updated_at"`
	DeletedAt sql.NullTime   `db:"deleted_at"`
}

type RefJenisHukuman struct {
	ID                 int32          `db:"id"`
	DikbudHrID         sql.NullString `db:"dikbud_hr_id"`
	Nama               sql.NullString `db:"nama"`
	TingkatHukuman     sql.NullString `db:"tingkat_hukuman"`
	NamaTingkatHukuman sql.NullString `db:"nama_tingkat_hukuman"`
	CreatedAt          sql.NullTime   `db:"created_at"`
	UpdatedAt          sql.NullTime   `db:"updated_at"`
	DeletedAt          sql.NullTime   `db:"deleted_at"`
}

type RefJenisJabatan struct {
	ID        int32          `db:"id"`
	Nama      sql.NullString `db:"nama"`
	CreatedAt sql.NullTime   `db:"created_at"`
	UpdatedAt sql.NullTime   `db:"updated_at"`
	DeletedAt sql.NullTime   `db:"deleted_at"`
}

type RefJenisKawin struct {
	ID        int32          `db:"id"`
	Nama      sql.NullString `db:"nama"`
	CreatedAt sql.NullTime   `db:"created_at"`
	UpdatedAt sql.NullTime   `db:"updated_at"`
	DeletedAt sql.NullTime   `db:"deleted_at"`
}

type RefJenisKp struct {
	ID         int32          `db:"id"`
	DikbudHrID sql.NullString `db:"dikbud_hr_id"`
	Nama       sql.NullString `db:"nama"`
	CreatedAt  sql.NullTime   `db:"created_at"`
	UpdatedAt  sql.NullTime   `db:"updated_at"`
	DeletedAt  sql.NullTime   `db:"deleted_at"`
}

type RefJenisPegawai struct {
	ID         int32          `db:"id"`
	DikbudHrID sql.NullString `db:"dikbud_hr_id"`
	Nama       sql.NullString `db:"nama"`
	CreatedAt  sql.NullTime   `db:"created_at"`
	UpdatedAt  sql.NullTime   `db:"updated_at"`
	DeletedAt  sql.NullTime   `db:"deleted_at"`
}

type RefJenisPenghargaan struct {
	ID        string         `db:"id"`
	Nama      sql.NullString `db:"nama"`
	CreatedAt sql.NullTime   `db:"created_at"`
	UpdatedAt sql.NullTime   `db:"updated_at"`
	DeletedAt sql.NullTime   `db:"deleted_at"`
}

type RefJenisSatker struct {
	ID        int32          `db:"id"`
	Nama      sql.NullString `db:"nama"`
	CreatedAt sql.NullTime   `db:"created_at"`
	UpdatedAt sql.NullTime   `db:"updated_at"`
	DeletedAt sql.NullTime   `db:"deleted_at"`
}

type RefKedudukanHukum struct {
	ID         int32          `db:"id"`
	DikbudHrID sql.NullString `db:"dikbud_hr_id"`
	Nama       sql.NullString `db:"nama"`
	CreatedAt  sql.NullTime   `db:"created_at"`
	UpdatedAt  sql.NullTime   `db:"updated_at"`
	DeletedAt  sql.NullTime   `db:"deleted_at"`
}

type RefKpkn struct {
	ID        string         `db:"id"`
	Nama      sql.NullString `db:"nama"`
	CreatedAt sql.NullTime   `db:"created_at"`
	UpdatedAt sql.NullTime   `db:"updated_at"`
	DeletedAt sql.NullTime   `db:"deleted_at"`
}

type RefLokasi struct {
	ID             string         `db:"id"`
	KanregID       sql.NullString `db:"kanreg_id"`
	LokasiID       sql.NullString `db:"lokasi_id"`
	Nama           sql.NullString `db:"nama"`
	Jenis          sql.NullString `db:"jenis"`
	JenisKabupaten sql.NullString `db:"jenis_kabupaten"`
	JenisDesa      sql.NullString `db:"jenis_desa"`
	Ibukota        sql.NullString `db:"ibukota"`
	CreatedAt      sql.NullTime   `db:"created_at"`
	UpdatedAt      sql.NullTime   `db:"updated_at"`
	DeletedAt      sql.NullTime   `db:"deleted_at"`
}

type RiwayatAssesman struct {
	ID                  int32           `db:"id"`
	PnsID               sql.NullString  `db:"pns_id"`
	PnsNip              sql.NullString  `db:"pns_nip"`
	Tahun               sql.NullInt16   `db:"tahun"`
	FileUpload          sql.NullString  `db:"file_upload"`
	Nilai               sql.NullFloat64 `db:"nilai"`
	NilaiKinerja        sql.NullFloat64 `db:"nilai_kinerja"`
	TahunPenilaianID    sql.NullInt16   `db:"tahun_penilaian_id"`
	TahunPenilaianTitle sql.NullString  `db:"tahun_penilaian_title"`
	NamaLengkap         sql.NullString  `db:"nama_lengkap"`
	PosisiID            sql.NullString  `db:"posisi_id"`
	UnitOrgID           sql.NullString  `db:"unit_org_id"`
	NamaUnor            sql.NullString  `db:"nama_unor"`
	SaranPengembangan   sql.NullString  `db:"saran_pengembangan"`
	FileUploadFbPotensi sql.NullString  `db:"file_upload_fb_potensi"`
	FileUploadLengkapPt sql.NullString  `db:"file_upload_lengkap_pt"`
	FileUploadFbPt      sql.NullString  `db:"file_upload_fb_pt"`
	FileUploadExists    sql.NullInt16   `db:"file_upload_exists"`
	SatkerID            sql.NullString  `db:"satker_id"`
	CreatedAt           sql.NullTime    `db:"created_at"`
	UpdatedAt           sql.NullTime    `db:"updated_at"`
	DeletedAt           sql.NullTime    `db:"deleted_at"`
}

type RiwayatDiklat struct {
	ID                     int64          `db:"id"`
	JenisDiklat            sql.NullString `db:"jenis_diklat"`
	JenisDiklatID          sql.NullInt16  `db:"jenis_diklat_id"`
	InstitusiPenyelenggara sql.NullString `db:"institusi_penyelenggara"`
	NoSertifikat           sql.NullString `db:"no_sertifikat"`
	TanggalMulai           sql.NullTime   `db:"tanggal_mulai"`
	TanggalSelesai         sql.NullTime   `db:"tanggal_selesai"`
	TahunDiklat            sql.NullInt16  `db:"tahun_diklat"`
	DurasiJam              sql.NullInt16  `db:"durasi_jam"`
	PnsOrangID             sql.NullString `db:"pns_orang_id"`
	NipBaru                sql.NullString `db:"nip_baru"`
	DiklatStrukturalID     sql.NullString `db:"diklat_struktural_id"`
	NamaDiklat             sql.NullString `db:"nama_diklat"`
	FileBase64             sql.NullString `db:"file_base64"`
	RumpunDiklatNama       sql.NullString `db:"rumpun_diklat_nama"`
	RumpunDiklatID         sql.NullString `db:"rumpun_diklat_id"`
	SudahKirimSiasn        sql.NullString `db:"sudah_kirim_siasn"`
	SiasnID                sql.NullString `db:"siasn_id"`
	CreatedAt              sql.NullTime   `db:"created_at"`
	UpdatedAt              sql.NullTime   `db:"updated_at"`
	DeletedAt              sql.NullTime   `db:"deleted_at"`
}

type RiwayatDiklatFungsional struct {
	ID                     string          `db:"id"`
	NipBaru                sql.NullString  `db:"nip_baru"`
	NipLama                sql.NullString  `db:"nip_lama"`
	JenisDiklat            sql.NullString  `db:"jenis_diklat"`
	NamaKursus             sql.NullString  `db:"nama_kursus"`
	JumlahJam              sql.NullInt32   `db:"jumlah_jam"`
	Tahun                  sql.NullInt16   `db:"tahun"`
	InstitusiPenyelenggara sql.NullString  `db:"institusi_penyelenggara"`
	JenisKursusSertifikat  sql.NullString  `db:"jenis_kursus_sertifikat"`
	NoSertifikat           sql.NullString  `db:"no_sertifikat"`
	Instansi               sql.NullString  `db:"instansi"`
	StatusData             sql.NullString  `db:"status_data"`
	TanggalKursus          sql.NullTime    `db:"tanggal_kursus"`
	FileBase64             sql.NullString  `db:"file_base64"`
	KeteranganBerkas       sql.NullString  `db:"keterangan_berkas"`
	Lama                   sql.NullFloat64 `db:"lama"`
	SiasnID                sql.NullString  `db:"siasn_id"`
	CreatedAt              sql.NullTime    `db:"created_at"`
	UpdatedAt              sql.NullTime    `db:"updated_at"`
	DeletedAt              sql.NullTime    `db:"deleted_at"`
}

type RiwayatDiklatStruktural struct {
	ID               string          `db:"id"`
	PnsID            sql.NullString  `db:"pns_id"`
	PnsNip           sql.NullString  `db:"pns_nip"`
	PnsNama          sql.NullString  `db:"pns_nama"`
	JenisDiklatID    sql.NullInt32   `db:"jenis_diklat_id"`
	NamaDiklat       sql.NullString  `db:"nama_diklat"`
	Nomor            sql.NullString  `db:"nomor"`
	Tanggal          sql.NullTime    `db:"tanggal"`
	Tahun            sql.NullInt16   `db:"tahun"`
	StatusData       sql.NullString  `db:"status_data"`
	FileBase64       sql.NullString  `db:"file_base64"`
	KeteranganBerkas sql.NullString  `db:"keterangan_berkas"`
	Lama             sql.NullFloat64 `db:"lama"`
	SiasnID          sql.NullString  `db:"siasn_id"`
	CreatedAt        sql.NullTime    `db:"created_at"`
	UpdatedAt        sql.NullTime    `db:"updated_at"`
	DeletedAt        sql.NullTime    `db:"deleted_at"`
}

type RiwayatGolongan struct {
	ID                        int32          `db:"id"`
	PnsID                     sql.NullString `db:"pns_id"`
	PnsNip                    sql.NullString `db:"pns_nip"`
	PnsNama                   sql.NullString `db:"pns_nama"`
	KodeJenisKp               sql.NullString `db:"kode_jenis_kp"`
	JenisKp                   sql.NullString `db:"jenis_kp"`
	GolonganID                sql.NullInt16  `db:"golongan_id"`
	GolonganNama              sql.NullString `db:"golongan_nama"`
	PangkatNama               sql.NullString `db:"pangkat_nama"`
	SkNomor                   sql.NullString `db:"sk_nomor"`
	NoBkn                     sql.NullString `db:"no_bkn"`
	JumlahAngkaKreditUtama    sql.NullInt16  `db:"jumlah_angka_kredit_utama"`
	JumlahAngkaKreditTambahan sql.NullInt16  `db:"jumlah_angka_kredit_tambahan"`
	MkGolonganTahun           sql.NullInt16  `db:"mk_golongan_tahun"`
	MkGolonganBulan           sql.NullInt16  `db:"mk_golongan_bulan"`
	SkTanggal                 sql.NullTime   `db:"sk_tanggal"`
	TanggalBkn                sql.NullTime   `db:"tanggal_bkn"`
	TmtGolongan               sql.NullTime   `db:"tmt_golongan"`
	StatusSatker              sql.NullInt32  `db:"status_satker"`
	StatusBiro                sql.NullInt32  `db:"status_biro"`
	PangkatTerakhir           sql.NullInt32  `db:"pangkat_terakhir"`
	BknID                     sql.NullString `db:"bkn_id"`
	FileBase64                sql.NullString `db:"file_base64"`
	KeteranganBerkas          sql.NullString `db:"keterangan_berkas"`
	ArsipID                   sql.NullInt64  `db:"arsip_id"`
	GolonganAsal              sql.NullString `db:"golongan_asal"`
	Basic                     sql.NullString `db:"basic"`
	SkType                    sql.NullInt16  `db:"sk_type"`
	Kanreg                    sql.NullString `db:"kanreg"`
	Kpkn                      sql.NullString `db:"kpkn"`
	Keterangan                sql.NullString `db:"keterangan"`
	Lpnk                      sql.NullString `db:"lpnk"`
	JenisRiwayat              sql.NullString `db:"jenis_riwayat"`
	CreatedAt                 sql.NullTime   `db:"created_at"`
	UpdatedAt                 sql.NullTime   `db:"updated_at"`
	DeletedAt                 sql.NullTime   `db:"deleted_at"`
}

type RiwayatHukdi struct {
	ID                  int64          `db:"id"`
	PnsID               sql.NullString `db:"pns_id"`
	PnsNip              sql.NullString `db:"pns_nip"`
	Nama                sql.NullString `db:"nama"`
	GolonganID          sql.NullInt16  `db:"golongan_id"`
	NamaGolongan        sql.NullString `db:"nama_golongan"`
	JenisHukumanID      sql.NullInt16  `db:"jenis_hukuman_id"`
	NamaJenisHukuman    sql.NullString `db:"nama_jenis_hukuman"`
	SkNomor             sql.NullString `db:"sk_nomor"`
	SkTanggal           sql.NullTime   `db:"sk_tanggal"`
	TanggalMulaiHukuman sql.NullTime   `db:"tanggal_mulai_hukuman"`
	MasaTahun           sql.NullInt16  `db:"masa_tahun"`
	MasaBulan           sql.NullInt16  `db:"masa_bulan"`
	TanggalAkhirHukuman sql.NullTime   `db:"tanggal_akhir_hukuman"`
	NoPp                sql.NullString `db:"no_pp"`
	NoSkPembatalan      sql.NullString `db:"no_sk_pembatalan"`
	TanggalSkPembatalan sql.NullTime   `db:"tanggal_sk_pembatalan"`
	BknID               sql.NullString `db:"bkn_id"`
	FileBase64          sql.NullString `db:"file_base64"`
	KeteranganBerkas    sql.NullString `db:"keterangan_berkas"`
	CreatedAt           sql.NullTime   `db:"created_at"`
	UpdatedAt           sql.NullTime   `db:"updated_at"`
	DeletedAt           sql.NullTime   `db:"deleted_at"`
}

type RiwayatJabatan struct {
	BknID          sql.NullString `db:"bkn_id"`
	PnsID          sql.NullString `db:"pns_id"`
	PnsNip         sql.NullString `db:"pns_nip"`
	PnsNama        sql.NullString `db:"pns_nama"`
	UnorID         sql.NullString `db:"unor_id"`
	Unor           sql.NullString `db:"unor"`
	JenisJabatanID sql.NullString `db:"jenis_jabatan_id"`
	JenisJabatan   sql.NullString `db:"jenis_jabatan"`
	JabatanID      sql.NullString `db:"jabatan_id"`
	NamaJabatan    sql.NullString `db:"nama_jabatan"`
	EselonID       sql.NullString `db:"eselon_id"`
	Eselon         sql.NullString `db:"eselon"`
	TmtJabatan     sql.NullTime   `db:"tmt_jabatan"`
	NoSk           sql.NullString `db:"no_sk"`
	TanggalSk      sql.NullTime   `db:"tanggal_sk"`
	SatuanKerjaID  sql.NullString `db:"satuan_kerja_id"`
	TmtPelantikan  sql.NullTime   `db:"tmt_pelantikan"`
	IsActive       sql.NullInt16  `db:"is_active"`
	Eselon1        sql.NullString `db:"eselon1"`
	Eselon2        sql.NullString `db:"eselon2"`
	Eselon3        sql.NullString `db:"eselon3"`
	Eselon4        sql.NullString `db:"eselon4"`
	ID             int64          `db:"id"`
	Catatan        sql.NullString `db:"catatan"`
	JenisSk        sql.NullString `db:"jenis_sk"`
	StatusSatker   sql.NullInt32  `db:"status_satker"`
	StatusBiro     sql.NullInt32  `db:"status_biro"`
	JabatanIDBkn   sql.NullString `db:"jabatan_id_bkn"`
	UnorIDBkn      sql.NullString `db:"unor_id_bkn"`
	TabelMutasiID  sql.NullInt64  `db:"tabel_mutasi_id"`
	CreatedAt      sql.NullTime   `db:"created_at"`
	UpdatedAt      sql.NullTime   `db:"updated_at"`
	DeletedAt      sql.NullTime   `db:"deleted_at"`
}

type RiwayatKgb struct {
	PegawaiID          sql.NullInt32  `db:"pegawai_id"`
	TmtSk              sql.NullTime   `db:"tmt_sk"`
	Alasan             sql.NullString `db:"alasan"`
	MvKgbID            sql.NullInt64  `db:"mv_kgb_id"`
	NoSk               sql.NullString `db:"no_sk"`
	Pejabat            sql.NullString `db:"pejabat"`
	ID                 int64          `db:"id"`
	Ref                sql.NullString `db:"ref"`
	TglSk              sql.NullTime   `db:"tgl_sk"`
	PegawaiNama        sql.NullString `db:"pegawai_nama"`
	PegawaiNip         sql.NullString `db:"pegawai_nip"`
	BirthPlace         sql.NullString `db:"birth_place"`
	BirthDate          sql.NullTime   `db:"birth_date"`
	NGolRuang          sql.NullString `db:"n_gol_ruang"`
	NGolTmt            sql.NullTime   `db:"n_gol_tmt"`
	NMasakerjaThn      sql.NullInt16  `db:"n_masakerja_thn"`
	NMasakerjaBln      sql.NullInt16  `db:"n_masakerja_bln"`
	NGapok             sql.NullString `db:"n_gapok"`
	NJabatanText       sql.NullString `db:"n_jabatan_text"`
	NTmtJabatan        sql.NullTime   `db:"n_tmt_jabatan"`
	NGolonganID        sql.NullInt32  `db:"n_golongan_id"`
	UnitKerjaIndukText sql.NullString `db:"unit_kerja_induk_text"`
	UnitKerjaIndukID   sql.NullString `db:"unit_kerja_induk_id"`
	KantorPembayaran   sql.NullString `db:"kantor_pembayaran"`
	LastEducation      sql.NullString `db:"last_education"`
	LastEducationDate  sql.NullTime   `db:"last_education_date"`
	CreatedAt          sql.NullTime   `db:"created_at"`
	UpdatedAt          sql.NullTime   `db:"updated_at"`
	DeletedAt          sql.NullTime   `db:"deleted_at"`
}

type RiwayatKinerja struct {
	ID                        int32          `db:"id"`
	Tahun                     sql.NullInt32  `db:"tahun"`
	Nip                       sql.NullString `db:"nip"`
	Nama                      sql.NullString `db:"nama"`
	NipPenilai                sql.NullString `db:"nip_penilai"`
	NamaPenilai               sql.NullString `db:"nama_penilai"`
	JabatanPenilai            sql.NullString `db:"jabatan_penilai"`
	UnitKerjaPenilai          sql.NullString `db:"unit_kerja_penilai"`
	NipPenilaiRealisasi       sql.NullString `db:"nip_penilai_realisasi"`
	NamaPenilaiRealisasi      sql.NullString `db:"nama_penilai_realisasi"`
	JabatanPenilaiRealisasi   sql.NullString `db:"jabatan_penilai_realisasi"`
	UnitKerjaPenilaiRealisasi sql.NullString `db:"unit_kerja_penilai_realisasi"`
	RatingHasilKerja          sql.NullString `db:"rating_hasil_kerja"`
	RatingPerilakuKerja       sql.NullString `db:"rating_perilaku_kerja"`
	PredikatKinerja           sql.NullString `db:"predikat_kinerja"`
	Ref                       uuid.NullUUID  `db:"ref"`
	CreatedAt                 sql.NullTime   `db:"created_at"`
	UpdatedAt                 sql.NullTime   `db:"updated_at"`
	DeletedAt                 sql.NullTime   `db:"deleted_at"`
}

type RiwayatKursu struct {
	ID                     int32           `db:"id"`
	PnsNip                 sql.NullString  `db:"pns_nip"`
	TipeKursus             sql.NullString  `db:"tipe_kursus"`
	JenisKursus            sql.NullString  `db:"jenis_kursus"`
	NamaKursus             sql.NullString  `db:"nama_kursus"`
	LamaKursus             sql.NullFloat64 `db:"lama_kursus"`
	TanggalKursus          sql.NullTime    `db:"tanggal_kursus"`
	NoSertifikat           sql.NullString  `db:"no_sertifikat"`
	Instansi               sql.NullString  `db:"instansi"`
	InstitusiPenyelenggara sql.NullString  `db:"institusi_penyelenggara"`
	SiasnID                sql.NullString  `db:"siasn_id"`
	PnsID                  sql.NullString  `db:"pns_id"`
	CreatedAt              sql.NullTime    `db:"created_at"`
	UpdatedAt              sql.NullTime    `db:"updated_at"`
	DeletedAt              sql.NullTime    `db:"deleted_at"`
}

type RiwayatNineBox struct {
	ID           int32          `db:"id"`
	PnsNip       sql.NullString `db:"pns_nip"`
	Nama         sql.NullString `db:"nama"`
	NamaJabatan  sql.NullString `db:"nama_jabatan"`
	KelasJabatan sql.NullInt16  `db:"kelas_jabatan"`
	Kesimpulan   sql.NullString `db:"kesimpulan"`
	Tahun        sql.NullString `db:"tahun"`
	CreatedAt    sql.NullTime   `db:"created_at"`
	UpdatedAt    sql.NullTime   `db:"updated_at"`
	DeletedAt    sql.NullTime   `db:"deleted_at"`
}

type RiwayatPendidikan struct {
	ID                  int32          `db:"id"`
	PnsID3              sql.NullString `db:"pns_id_3"`
	TingkatPendidikanID sql.NullInt16  `db:"tingkat_pendidikan_id"`
	PendidikanID3       sql.NullString `db:"pendidikan_id_3"`
	TanggalLulus        sql.NullTime   `db:"tanggal_lulus"`
	NoIjazah            sql.NullString `db:"no_ijazah"`
	NamaSekolah         sql.NullString `db:"nama_sekolah"`
	GelarDepan          sql.NullString `db:"gelar_depan"`
	GelarBelakang       sql.NullString `db:"gelar_belakang"`
	PendidikanPertama   sql.NullString `db:"pendidikan_pertama"`
	NegaraSekolah       sql.NullString `db:"negara_sekolah"`
	TahunLulus          sql.NullString `db:"tahun_lulus"`
	Nip                 sql.NullString `db:"nip"`
	DiakuiBkn           sql.NullInt32  `db:"diakui_bkn"`
	StatusSatker        sql.NullInt32  `db:"status_satker"`
	StatusBiro          sql.NullInt32  `db:"status_biro"`
	PendidikanTerakhir  sql.NullInt32  `db:"pendidikan_terakhir"`
	PnsID               sql.NullString `db:"pns_id"`
	PendidikanID        sql.NullString `db:"pendidikan_id"`
	CreatedAt           sql.NullTime   `db:"created_at"`
	UpdatedAt           sql.NullTime   `db:"updated_at"`
	DeletedAt           sql.NullTime   `db:"deleted_at"`
}

type RiwayatPenghargaanUmum struct {
	ID                   int32          `db:"id"`
	JenisPenghargaan     sql.NullString `db:"jenis_penghargaan"`
	DeskripsiPenghargaan sql.NullString `db:"deskripsi_penghargaan"`
	TanggalPenghargaan   sql.NullTime   `db:"tanggal_penghargaan"`
	Exist                sql.NullBool   `db:"exist"`
	FileBase64           sql.NullString `db:"file_base64"`
	Nip                  sql.NullString `db:"nip"`
	NamaPenghargaan      sql.NullString `db:"nama_penghargaan"`
	CreatedAt            sql.NullTime   `db:"created_at"`
	UpdatedAt            sql.NullTime   `db:"updated_at"`
	DeletedAt            sql.NullTime   `db:"deleted_at"`
}

type RiwayatPenugasan struct {
	ID               int32          `db:"id"`
	TipeJabatan      sql.NullString `db:"tipe_jabatan"`
	DeskripsiJabatan sql.NullString `db:"deskripsi_jabatan"`
	TanggalMulai     sql.NullTime   `db:"tanggal_mulai"`
	TanggalSelesai   sql.NullTime   `db:"tanggal_selesai"`
	FileBase64       sql.NullString `db:"file_base64"`
	Nip              sql.NullString `db:"nip"`
	NamaJabatan      sql.NullString `db:"nama_jabatan"`
	IsMenjabat       sql.NullBool   `db:"is_menjabat"`
	CreatedAt        sql.NullTime   `db:"created_at"`
	UpdatedAt        sql.NullTime   `db:"updated_at"`
	DeletedAt        sql.NullTime   `db:"deleted_at"`
}

type RiwayatPindahUnitKerja struct {
	ID               int64          `db:"id"`
	PnsID            sql.NullString `db:"pns_id"`
	PnsNip           sql.NullString `db:"pns_nip"`
	PnsNama          sql.NullString `db:"pns_nama"`
	SkNomor          sql.NullString `db:"sk_nomor"`
	AsalID           sql.NullString `db:"asal_id"`
	AsalNama         sql.NullString `db:"asal_nama"`
	UnorIDBaru       sql.NullString `db:"unor_id_baru"`
	NamaUnorBaru     sql.NullString `db:"nama_unor_baru"`
	InstansiID       sql.NullString `db:"instansi_id"`
	NamaInstansi     sql.NullString `db:"nama_instansi"`
	SkTanggal        sql.NullTime   `db:"sk_tanggal"`
	SatuanKerjaID    sql.NullString `db:"satuan_kerja_id"`
	NamaSatuanKerja  sql.NullString `db:"nama_satuan_kerja"`
	FileBase64       sql.NullString `db:"file_base64"`
	KeteranganBerkas sql.NullString `db:"keterangan_berkas"`
	CreatedAt        sql.NullTime   `db:"created_at"`
	UpdatedAt        sql.NullTime   `db:"updated_at"`
	DeletedAt        sql.NullTime   `db:"deleted_at"`
}

type RiwayatSertifikasi struct {
	ID              int64          `db:"id"`
	Nip             sql.NullString `db:"nip"`
	Tahun           sql.NullInt64  `db:"tahun"`
	NamaSertifikasi sql.NullString `db:"nama_sertifikasi"`
	FileBase64      sql.NullString `db:"file_base64"`
	Deskripsi       sql.NullString `db:"deskripsi"`
	CreatedAt       sql.NullTime   `db:"created_at"`
	UpdatedAt       sql.NullTime   `db:"updated_at"`
	DeletedAt       sql.NullTime   `db:"deleted_at"`
}

type RiwayatUjikom struct {
	ID             int64          `db:"id"`
	JenisUjikom    sql.NullString `db:"jenis_ujikom"`
	NipBaru        sql.NullString `db:"nip_baru"`
	LinkSertifikat sql.NullString `db:"link_sertifikat"`
	Exist          sql.NullBool   `db:"exist"`
	Tahun          sql.NullInt32  `db:"tahun"`
	CreatedAt      sql.NullTime   `db:"created_at"`
	UpdatedAt      sql.NullTime   `db:"updated_at"`
	DeletedAt      sql.NullTime   `db:"deleted_at"`
}

type Role struct {
	ID        int32        `db:"id"`
	Nama      string       `db:"nama"`
	CreatedAt sql.NullTime `db:"created_at"`
	UpdatedAt sql.NullTime `db:"updated_at"`
	DeletedAt sql.NullTime `db:"deleted_at"`
}

type TingkatPendidikan struct {
	ID             int32          `db:"id"`
	GolonganID     sql.NullInt32  `db:"golongan_id"`
	Nama           sql.NullString `db:"nama"`
	GolonganAwalID sql.NullInt32  `db:"golongan_awal_id"`
	Abbreviation   sql.NullString `db:"abbreviation"`
	Tingkat        sql.NullInt16  `db:"tingkat"`
	CreatedAt      sql.NullTime   `db:"created_at"`
	UpdatedAt      sql.NullTime   `db:"updated_at"`
	DeletedAt      sql.NullTime   `db:"deleted_at"`
}

type UnitKerja struct {
	ID                   string         `db:"id"`
	No                   sql.NullInt32  `db:"no"`
	KodeInternal         sql.NullString `db:"kode_internal"`
	NamaUnor             sql.NullString `db:"nama_unor"`
	EselonID             sql.NullString `db:"eselon_id"`
	CepatKode            sql.NullString `db:"cepat_kode"`
	NamaJabatan          sql.NullString `db:"nama_jabatan"`
	NamaPejabat          sql.NullString `db:"nama_pejabat"`
	DiatasanID           sql.NullString `db:"diatasan_id"`
	InstansiID           sql.NullString `db:"instansi_id"`
	PemimpinPnsID        sql.NullString `db:"pemimpin_pns_id"`
	JenisUnorID          sql.NullString `db:"jenis_unor_id"`
	UnorInduk            sql.NullString `db:"unor_induk"`
	JumlahIdealStaff     sql.NullInt16  `db:"jumlah_ideal_staff"`
	Order                sql.NullInt32  `db:"order"`
	IsSatker             int16          `db:"is_satker"`
	Eselon1              sql.NullString `db:"eselon_1"`
	Eselon2              sql.NullString `db:"eselon_2"`
	Eselon3              sql.NullString `db:"eselon_3"`
	Eselon4              sql.NullString `db:"eselon_4"`
	ExpiredDate          sql.NullTime   `db:"expired_date"`
	Keterangan           sql.NullString `db:"keterangan"`
	JenisSatker          sql.NullString `db:"jenis_satker"`
	Abbreviation         sql.NullString `db:"abbreviation"`
	UnorIndukPenyetaraan sql.NullString `db:"unor_induk_penyetaraan"`
	JabatanID            sql.NullString `db:"jabatan_id"`
	Waktu                sql.NullString `db:"waktu"`
	Peraturan            sql.NullString `db:"peraturan"`
	Remark               sql.NullString `db:"remark"`
	Aktif                sql.NullBool   `db:"aktif"`
	EselonNama           sql.NullString `db:"eselon_nama"`
	CreatedAt            sql.NullTime   `db:"created_at"`
	UpdatedAt            sql.NullTime   `db:"updated_at"`
	DeletedAt            sql.NullTime   `db:"deleted_at"`
}

type UpdateMandiri struct {
	ID            int32          `db:"id"`
	PnsID         sql.NullString `db:"pns_id"`
	Kolom         sql.NullString `db:"kolom"`
	Dari          sql.NullString `db:"dari"`
	Perubahan     sql.NullString `db:"perubahan"`
	Status        sql.NullInt32  `db:"status"`
	VerifikasiBy  sql.NullInt32  `db:"verifikasi_by"`
	VerifikasiTgl sql.NullTime   `db:"verifikasi_tgl"`
	NamaKolom     sql.NullString `db:"nama_kolom"`
	LevelUpdate   sql.NullInt32  `db:"level_update"`
	TabelID       sql.NullInt32  `db:"tabel_id"`
	UpdatedBy     sql.NullInt32  `db:"updated_by"`
	CreatedAt     sql.NullTime   `db:"created_at"`
	UpdatedAt     sql.NullTime   `db:"updated_at"`
	DeletedAt     sql.NullTime   `db:"deleted_at"`
}

type User struct {
	ID        uuid.UUID      `db:"id"`
	Source    string         `db:"source"`
	Nip       sql.NullString `db:"nip"`
	CreatedAt sql.NullTime   `db:"created_at"`
	UpdatedAt sql.NullTime   `db:"updated_at"`
	DeletedAt sql.NullTime   `db:"deleted_at"`
}

type UserRole struct {
	ID        int32        `db:"id"`
	Nip       string       `db:"nip"`
	RoleID    int32        `db:"role_id"`
	CreatedAt sql.NullTime `db:"created_at"`
	UpdatedAt sql.NullTime `db:"updated_at"`
	DeletedAt sql.NullTime `db:"deleted_at"`
}
