// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Anak struct {
	ID           int64              `db:"id"`
	PasanganID   pgtype.Int8        `db:"pasangan_id"`
	Nama         pgtype.Text        `db:"nama"`
	JenisKelamin pgtype.Text        `db:"jenis_kelamin"`
	TanggalLahir pgtype.Date        `db:"tanggal_lahir"`
	TempatLahir  pgtype.Text        `db:"tempat_lahir"`
	StatusAnak   pgtype.Text        `db:"status_anak"`
	PnsID        pgtype.Text        `db:"pns_id"`
	Nip          pgtype.Text        `db:"nip"`
	CreatedAt    pgtype.Timestamptz `db:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at"`
}

type OrangTua struct {
	ID            int32              `db:"id"`
	Hubungan      pgtype.Int2        `db:"hubungan"`
	AkteMeninggal pgtype.Text        `db:"akte_meninggal"`
	TglMeninggal  pgtype.Date        `db:"tgl_meninggal"`
	Nama          pgtype.Text        `db:"nama"`
	GelarDepan    pgtype.Text        `db:"gelar_depan"`
	GelarBelakang pgtype.Text        `db:"gelar_belakang"`
	TempatLahir   pgtype.Text        `db:"tempat_lahir"`
	TanggalLahir  pgtype.Date        `db:"tanggal_lahir"`
	AgamaID       pgtype.Int2        `db:"agama_id"`
	Email         pgtype.Text        `db:"email"`
	JenisDokumen  pgtype.Text        `db:"jenis_dokumen"`
	NoDokumen     pgtype.Text        `db:"no_dokumen"`
	Nip           pgtype.Text        `db:"nip"`
	PnsID         pgtype.Text        `db:"pns_id"`
	CreatedAt     pgtype.Timestamptz `db:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at"`
	DeletedAt     pgtype.Timestamptz `db:"deleted_at"`
}

type Pasangan struct {
	ID               int64              `db:"id"`
	Pns              pgtype.Int2        `db:"pns"`
	Nama             pgtype.Text        `db:"nama"`
	TanggalMenikah   pgtype.Date        `db:"tanggal_menikah"`
	AkteNikah        pgtype.Text        `db:"akte_nikah"`
	TanggalMeninggal pgtype.Date        `db:"tanggal_meninggal"`
	AkteMeninggal    pgtype.Text        `db:"akte_meninggal"`
	TanggalCerai     pgtype.Date        `db:"tanggal_cerai"`
	AkteCerai        pgtype.Text        `db:"akte_cerai"`
	Karsus           pgtype.Text        `db:"karsus"`
	Status           pgtype.Int2        `db:"status"`
	Hubungan         pgtype.Int2        `db:"hubungan"`
	PnsID            pgtype.Text        `db:"pns_id"`
	Nip              pgtype.Text        `db:"nip"`
	CreatedAt        pgtype.Timestamptz `db:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at"`
}

type Pegawai struct {
	ID                    int32              `db:"id"`
	PnsID                 string             `db:"pns_id"`
	NipLama               pgtype.Text        `db:"nip_lama"`
	NipBaru               pgtype.Text        `db:"nip_baru"`
	Nama                  pgtype.Text        `db:"nama"`
	GelarDepan            pgtype.Text        `db:"gelar_depan"`
	GelarBelakang         pgtype.Text        `db:"gelar_belakang"`
	TempatLahirID         pgtype.Text        `db:"tempat_lahir_id"`
	TglLahir              pgtype.Date        `db:"tgl_lahir"`
	JenisKelamin          pgtype.Text        `db:"jenis_kelamin"`
	AgamaID               pgtype.Int2        `db:"agama_id"`
	JenisKawinID          pgtype.Int2        `db:"jenis_kawin_id"`
	Nik                   pgtype.Text        `db:"nik"`
	NoDarurat             pgtype.Text        `db:"no_darurat"`
	NoHp                  pgtype.Text        `db:"no_hp"`
	Email                 pgtype.Text        `db:"email"`
	Alamat                pgtype.Text        `db:"alamat"`
	Npwp                  pgtype.Text        `db:"npwp"`
	Bpjs                  pgtype.Text        `db:"bpjs"`
	JenisPegawaiID        pgtype.Int2        `db:"jenis_pegawai_id"`
	KedudukanHukumID      pgtype.Int4        `db:"kedudukan_hukum_id"`
	StatusCpnsPns         pgtype.Text        `db:"status_cpns_pns"`
	KartuPegawai          pgtype.Text        `db:"kartu_pegawai"`
	NoSkCpns              pgtype.Text        `db:"no_sk_cpns"`
	TglSkCpns             pgtype.Date        `db:"tgl_sk_cpns"`
	TmtCpns               pgtype.Date        `db:"tmt_cpns"`
	TmtPns                pgtype.Date        `db:"tmt_pns"`
	GolAwalID             pgtype.Int2        `db:"gol_awal_id"`
	GolID                 pgtype.Int2        `db:"gol_id"`
	TmtGolongan           pgtype.Date        `db:"tmt_golongan"`
	MkTahun               pgtype.Int2        `db:"mk_tahun"`
	MkBulan               pgtype.Int2        `db:"mk_bulan"`
	JabatanID             pgtype.Text        `db:"jabatan_id"`
	TmtJabatan            pgtype.Date        `db:"tmt_jabatan"`
	PendidikanID          pgtype.Text        `db:"pendidikan_id"`
	TahunLulus            pgtype.Int2        `db:"tahun_lulus"`
	KpknID                pgtype.Text        `db:"kpkn_id"`
	LokasiKerjaID         pgtype.Text        `db:"lokasi_kerja_id"`
	UnorID                pgtype.Text        `db:"unor_id"`
	UnorIndukID           pgtype.Text        `db:"unor_induk_id"`
	InstansiIndukID       pgtype.Text        `db:"instansi_induk_id"`
	InstansiKerjaID       pgtype.Text        `db:"instansi_kerja_id"`
	SatuanKerjaIndukID    pgtype.Text        `db:"satuan_kerja_induk_id"`
	SatuanKerjaKerjaID    pgtype.Text        `db:"satuan_kerja_kerja_id"`
	GolonganDarah         pgtype.Text        `db:"golongan_darah"`
	Foto                  pgtype.Text        `db:"foto"`
	TmtPensiun            pgtype.Date        `db:"tmt_pensiun"`
	LokasiKerja           pgtype.Text        `db:"lokasi_kerja"`
	JmlIstri              pgtype.Int2        `db:"jml_istri"`
	JmlAnak               pgtype.Int2        `db:"jml_anak"`
	NoSuratDokter         pgtype.Text        `db:"no_surat_dokter"`
	TglSuratDokter        pgtype.Date        `db:"tgl_surat_dokter"`
	NoBebasNarkoba        pgtype.Text        `db:"no_bebas_narkoba"`
	TglBebasNarkoba       pgtype.Date        `db:"tgl_bebas_narkoba"`
	NoCatatanPolisi       pgtype.Text        `db:"no_catatan_polisi"`
	TglCatatanPolisi      pgtype.Date        `db:"tgl_catatan_polisi"`
	AkteKelahiran         pgtype.Text        `db:"akte_kelahiran"`
	StatusHidup           pgtype.Text        `db:"status_hidup"`
	AkteMeninggal         pgtype.Text        `db:"akte_meninggal"`
	TglMeninggal          pgtype.Date        `db:"tgl_meninggal"`
	NoAskes               pgtype.Text        `db:"no_askes"`
	NoTaspen              pgtype.Text        `db:"no_taspen"`
	TglNpwp               pgtype.Date        `db:"tgl_npwp"`
	TempatLahir           pgtype.Text        `db:"tempat_lahir"`
	TingkatPendidikanID   pgtype.Int2        `db:"tingkat_pendidikan_id"`
	TempatLahirNama       pgtype.Text        `db:"tempat_lahir_nama"`
	JenisJabatanNama      pgtype.Text        `db:"jenis_jabatan_nama"`
	JabatanNama           pgtype.Text        `db:"jabatan_nama"`
	KpknNama              pgtype.Text        `db:"kpkn_nama"`
	InstansiIndukNama     pgtype.Text        `db:"instansi_induk_nama"`
	InstansiKerjaNama     pgtype.Text        `db:"instansi_kerja_nama"`
	SatuanKerjaIndukNama  pgtype.Text        `db:"satuan_kerja_induk_nama"`
	SatuanKerjaNama       pgtype.Text        `db:"satuan_kerja_nama"`
	JabatanInstansiID     pgtype.Int4        `db:"jabatan_instansi_id"`
	Bup                   pgtype.Int2        `db:"bup"`
	JabatanInstansiNama   pgtype.Text        `db:"jabatan_instansi_nama"`
	JenisJabatanID        pgtype.Int2        `db:"jenis_jabatan_id"`
	TerminatedDate        pgtype.Date        `db:"terminated_date"`
	StatusPegawai         pgtype.Int2        `db:"status_pegawai"`
	JabatanPpnpn          pgtype.Text        `db:"jabatan_ppnpn"`
	JabatanInstansiRealID pgtype.Int4        `db:"jabatan_instansi_real_id"`
	CreatedBy             pgtype.Int4        `db:"created_by"`
	UpdatedBy             pgtype.Int4        `db:"updated_by"`
	EmailDikbudBak        pgtype.Text        `db:"email_dikbud_bak"`
	EmailDikbud           pgtype.Text        `db:"email_dikbud"`
	Kodecepat             pgtype.Text        `db:"kodecepat"`
	IsDosen               pgtype.Int2        `db:"is_dosen"`
	MkTahunSwasta         pgtype.Int2        `db:"mk_tahun_swasta"`
	MkBulanSwasta         pgtype.Int2        `db:"mk_bulan_swasta"`
	Kk                    pgtype.Text        `db:"kk"`
	Nidn                  pgtype.Text        `db:"nidn"`
	Ket                   pgtype.Text        `db:"ket"`
	NoSkPemberhentian     pgtype.Text        `db:"no_sk_pemberhentian"`
	StatusPegawaiBackup   pgtype.Int2        `db:"status_pegawai_backup"`
	MasaKerja             pgtype.Text        `db:"masa_kerja"`
	KartuAsn              pgtype.Text        `db:"kartu_asn"`
	CreatedAt             pgtype.Timestamptz `db:"created_at"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at"`
	DeletedAt             pgtype.Timestamptz `db:"deleted_at"`
}

type Pendidikan struct {
	ID                  string             `db:"id"`
	TingkatPendidikanID pgtype.Int2        `db:"tingkat_pendidikan_id"`
	Nama                pgtype.Text        `db:"nama"`
	CreatedAt           pgtype.Timestamptz `db:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at"`
	DeletedAt           pgtype.Timestamptz `db:"deleted_at"`
}

type PindahUnit struct {
	ID                      int32              `db:"id"`
	Nip                     string             `db:"nip"`
	SuratPermohonanPindah   pgtype.Text        `db:"surat_permohonan_pindah"`
	UnitAsal                pgtype.Text        `db:"unit_asal"`
	UnitTujuan              pgtype.Text        `db:"unit_tujuan"`
	SuratPernyataanMelepas  pgtype.Text        `db:"surat_pernyataan_melepas"`
	SkKpTerakhir            pgtype.Text        `db:"sk_kp_terakhir"`
	SkJabatan               pgtype.Text        `db:"sk_jabatan"`
	Skp                     pgtype.Text        `db:"skp"`
	SkTunkin                pgtype.Text        `db:"sk_tunkin"`
	SuratPernyataanMenerima pgtype.Text        `db:"surat_pernyataan_menerima"`
	NoSkPindah              pgtype.Text        `db:"no_sk_pindah"`
	TanggalSkPindah         pgtype.Date        `db:"tanggal_sk_pindah"`
	FileSk                  pgtype.Text        `db:"file_sk"`
	StatusSatker            pgtype.Int2        `db:"status_satker"`
	StatusBiro              pgtype.Int2        `db:"status_biro"`
	JabatanID               pgtype.Int2        `db:"jabatan_id"`
	Keterangan              pgtype.Text        `db:"keterangan"`
	TanggalTmtPindah        pgtype.Date        `db:"tanggal_tmt_pindah"`
	CreatedBy               pgtype.Int4        `db:"created_by"`
	CreatedAt               pgtype.Timestamptz `db:"created_at"`
	UpdatedAt               pgtype.Timestamptz `db:"updated_at"`
	DeletedAt               pgtype.Timestamptz `db:"deleted_at"`
}

type RefAgama struct {
	ID        int32              `db:"id"`
	Nama      pgtype.Text        `db:"nama"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at"`
}

type RefGolongan struct {
	ID          int32              `db:"id"`
	Nama        pgtype.Text        `db:"nama"`
	NamaPangkat pgtype.Text        `db:"nama_pangkat"`
	Nama2       pgtype.Text        `db:"nama_2"`
	Gol         pgtype.Int2        `db:"gol"`
	GolPppk     pgtype.Text        `db:"gol_pppk"`
	CreatedAt   pgtype.Timestamptz `db:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at"`
	DeletedAt   pgtype.Timestamptz `db:"deleted_at"`
}

type RefInstansi struct {
	ID        string             `db:"id"`
	Nama      pgtype.Text        `db:"nama"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at"`
}

type RefJabatan struct {
	KodeJabatan     string             `db:"kode_jabatan"`
	ID              int32              `db:"id"`
	No              int32              `db:"no"`
	NamaJabatan     pgtype.Text        `db:"nama_jabatan"`
	NamaJabatanFull pgtype.Text        `db:"nama_jabatan_full"`
	JenisJabatan    pgtype.Int2        `db:"jenis_jabatan"`
	Kelas           pgtype.Int2        `db:"kelas"`
	Pensiun         pgtype.Int2        `db:"pensiun"`
	KodeBkn         pgtype.Text        `db:"kode_bkn"`
	NamaJabatanBkn  pgtype.Text        `db:"nama_jabatan_bkn"`
	KategoriJabatan pgtype.Text        `db:"kategori_jabatan"`
	BknID           pgtype.Text        `db:"bkn_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at"`
	DeletedAt       pgtype.Timestamptz `db:"deleted_at"`
}

type RefJenisDiklat struct {
	ID          int32              `db:"id"`
	BknID       pgtype.Int2        `db:"bkn_id"`
	JenisDiklat pgtype.Text        `db:"jenis_diklat"`
	Kode        pgtype.Text        `db:"kode"`
	Status      pgtype.Int2        `db:"status"`
	CreatedAt   pgtype.Timestamptz `db:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at"`
	DeletedAt   pgtype.Timestamptz `db:"deleted_at"`
}

type RefJenisDiklatFungsional struct {
	ID        int32              `db:"id"`
	Nama      pgtype.Text        `db:"nama"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at"`
}

type RefJenisDiklatStruktural struct {
	ID        int32              `db:"id"`
	Nama      pgtype.Text        `db:"nama"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at"`
}

type RefJenisHukuman struct {
	ID                 int32              `db:"id"`
	DikbudHrID         pgtype.Text        `db:"dikbud_hr_id"`
	Nama               pgtype.Text        `db:"nama"`
	TingkatHukuman     pgtype.Text        `db:"tingkat_hukuman"`
	NamaTingkatHukuman pgtype.Text        `db:"nama_tingkat_hukuman"`
	CreatedAt          pgtype.Timestamptz `db:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at"`
	DeletedAt          pgtype.Timestamptz `db:"deleted_at"`
}

type RefJenisJabatan struct {
	ID        int32              `db:"id"`
	Nama      pgtype.Text        `db:"nama"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at"`
}

type RefJenisKawin struct {
	ID        int32              `db:"id"`
	Nama      pgtype.Text        `db:"nama"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at"`
}

type RefJenisKp struct {
	ID         int32              `db:"id"`
	DikbudHrID pgtype.Text        `db:"dikbud_hr_id"`
	Nama       pgtype.Text        `db:"nama"`
	CreatedAt  pgtype.Timestamptz `db:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at"`
	DeletedAt  pgtype.Timestamptz `db:"deleted_at"`
}

type RefJenisPegawai struct {
	ID         int32              `db:"id"`
	DikbudHrID pgtype.Text        `db:"dikbud_hr_id"`
	Nama       pgtype.Text        `db:"nama"`
	CreatedAt  pgtype.Timestamptz `db:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at"`
	DeletedAt  pgtype.Timestamptz `db:"deleted_at"`
}

type RefJenisPenghargaan struct {
	ID        string             `db:"id"`
	Nama      pgtype.Text        `db:"nama"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at"`
}

type RefJenisSatker struct {
	ID        int32              `db:"id"`
	Nama      pgtype.Text        `db:"nama"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at"`
}

type RefKedudukanHukum struct {
	ID         int32              `db:"id"`
	DikbudHrID pgtype.Text        `db:"dikbud_hr_id"`
	Nama       pgtype.Text        `db:"nama"`
	CreatedAt  pgtype.Timestamptz `db:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at"`
	DeletedAt  pgtype.Timestamptz `db:"deleted_at"`
}

type RefKelasJabatan struct {
	ID               int32            `db:"id"`
	KelasJabatan     pgtype.Text      `db:"kelas_jabatan"`
	TunjanganKinerja pgtype.Int8      `db:"tunjangan_kinerja"`
	CreatedAt        pgtype.Timestamp `db:"created_at"`
	UpdatedAt        pgtype.Timestamp `db:"updated_at"`
}

type RefKpkn struct {
	ID        string             `db:"id"`
	Nama      pgtype.Text        `db:"nama"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at"`
}

type RefLokasi struct {
	ID             string             `db:"id"`
	KanregID       pgtype.Text        `db:"kanreg_id"`
	LokasiID       pgtype.Text        `db:"lokasi_id"`
	Nama           pgtype.Text        `db:"nama"`
	Jenis          pgtype.Text        `db:"jenis"`
	JenisKabupaten pgtype.Text        `db:"jenis_kabupaten"`
	JenisDesa      pgtype.Text        `db:"jenis_desa"`
	Ibukota        pgtype.Text        `db:"ibukota"`
	CreatedAt      pgtype.Timestamptz `db:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at"`
	DeletedAt      pgtype.Timestamptz `db:"deleted_at"`
}

type RiwayatAssesman struct {
	ID                  int32              `db:"id"`
	PnsID               pgtype.Text        `db:"pns_id"`
	PnsNip              pgtype.Text        `db:"pns_nip"`
	Tahun               pgtype.Int2        `db:"tahun"`
	FileUpload          pgtype.Text        `db:"file_upload"`
	Nilai               pgtype.Float4      `db:"nilai"`
	NilaiKinerja        pgtype.Float4      `db:"nilai_kinerja"`
	TahunPenilaianID    pgtype.Int2        `db:"tahun_penilaian_id"`
	TahunPenilaianTitle pgtype.Text        `db:"tahun_penilaian_title"`
	NamaLengkap         pgtype.Text        `db:"nama_lengkap"`
	PosisiID            pgtype.Text        `db:"posisi_id"`
	UnitOrgID           pgtype.Text        `db:"unit_org_id"`
	NamaUnor            pgtype.Text        `db:"nama_unor"`
	SaranPengembangan   pgtype.Text        `db:"saran_pengembangan"`
	FileUploadFbPotensi pgtype.Text        `db:"file_upload_fb_potensi"`
	FileUploadLengkapPt pgtype.Text        `db:"file_upload_lengkap_pt"`
	FileUploadFbPt      pgtype.Text        `db:"file_upload_fb_pt"`
	FileUploadExists    pgtype.Int2        `db:"file_upload_exists"`
	SatkerID            pgtype.Text        `db:"satker_id"`
	CreatedAt           pgtype.Timestamptz `db:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at"`
	DeletedAt           pgtype.Timestamptz `db:"deleted_at"`
}

type RiwayatDiklat struct {
	ID                     int64              `db:"id"`
	JenisDiklat            pgtype.Text        `db:"jenis_diklat"`
	JenisDiklatID          pgtype.Int2        `db:"jenis_diklat_id"`
	InstitusiPenyelenggara pgtype.Text        `db:"institusi_penyelenggara"`
	NoSertifikat           pgtype.Text        `db:"no_sertifikat"`
	TanggalMulai           pgtype.Date        `db:"tanggal_mulai"`
	TanggalSelesai         pgtype.Date        `db:"tanggal_selesai"`
	TahunDiklat            pgtype.Int2        `db:"tahun_diklat"`
	DurasiJam              pgtype.Int2        `db:"durasi_jam"`
	PnsOrangID             pgtype.Text        `db:"pns_orang_id"`
	NipBaru                pgtype.Text        `db:"nip_baru"`
	DiklatStrukturalID     pgtype.Text        `db:"diklat_struktural_id"`
	NamaDiklat             pgtype.Text        `db:"nama_diklat"`
	FileBase64             pgtype.Text        `db:"file_base64"`
	RumpunDiklatNama       pgtype.Text        `db:"rumpun_diklat_nama"`
	RumpunDiklatID         pgtype.Text        `db:"rumpun_diklat_id"`
	SudahKirimSiasn        pgtype.Text        `db:"sudah_kirim_siasn"`
	SiasnID                pgtype.Text        `db:"siasn_id"`
	CreatedAt              pgtype.Timestamptz `db:"created_at"`
	UpdatedAt              pgtype.Timestamptz `db:"updated_at"`
	DeletedAt              pgtype.Timestamptz `db:"deleted_at"`
}

type RiwayatDiklatFungsional struct {
	ID                     string             `db:"id"`
	NipBaru                pgtype.Text        `db:"nip_baru"`
	NipLama                pgtype.Text        `db:"nip_lama"`
	JenisDiklat            pgtype.Text        `db:"jenis_diklat"`
	NamaKursus             pgtype.Text        `db:"nama_kursus"`
	JumlahJam              pgtype.Int4        `db:"jumlah_jam"`
	Tahun                  pgtype.Int2        `db:"tahun"`
	InstitusiPenyelenggara pgtype.Text        `db:"institusi_penyelenggara"`
	JenisKursusSertifikat  pgtype.Text        `db:"jenis_kursus_sertifikat"`
	NoSertifikat           pgtype.Text        `db:"no_sertifikat"`
	Instansi               pgtype.Text        `db:"instansi"`
	StatusData             pgtype.Text        `db:"status_data"`
	TanggalKursus          pgtype.Date        `db:"tanggal_kursus"`
	FileBase64             pgtype.Text        `db:"file_base64"`
	KeteranganBerkas       pgtype.Text        `db:"keterangan_berkas"`
	Lama                   pgtype.Float4      `db:"lama"`
	SiasnID                pgtype.Text        `db:"siasn_id"`
	CreatedAt              pgtype.Timestamptz `db:"created_at"`
	UpdatedAt              pgtype.Timestamptz `db:"updated_at"`
	DeletedAt              pgtype.Timestamptz `db:"deleted_at"`
}

type RiwayatDiklatStruktural struct {
	ID               string             `db:"id"`
	PnsID            pgtype.Text        `db:"pns_id"`
	PnsNip           pgtype.Text        `db:"pns_nip"`
	PnsNama          pgtype.Text        `db:"pns_nama"`
	JenisDiklatID    pgtype.Int4        `db:"jenis_diklat_id"`
	NamaDiklat       pgtype.Text        `db:"nama_diklat"`
	Nomor            pgtype.Text        `db:"nomor"`
	Tanggal          pgtype.Date        `db:"tanggal"`
	Tahun            pgtype.Int2        `db:"tahun"`
	StatusData       pgtype.Text        `db:"status_data"`
	FileBase64       pgtype.Text        `db:"file_base64"`
	KeteranganBerkas pgtype.Text        `db:"keterangan_berkas"`
	Lama             pgtype.Float4      `db:"lama"`
	SiasnID          pgtype.Text        `db:"siasn_id"`
	CreatedAt        pgtype.Timestamptz `db:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at"`
}

type RiwayatGolongan struct {
	ID                        int32              `db:"id"`
	PnsID                     pgtype.Text        `db:"pns_id"`
	PnsNip                    pgtype.Text        `db:"pns_nip"`
	PnsNama                   pgtype.Text        `db:"pns_nama"`
	KodeJenisKp               pgtype.Text        `db:"kode_jenis_kp"`
	JenisKp                   pgtype.Text        `db:"jenis_kp"`
	GolonganID                pgtype.Int2        `db:"golongan_id"`
	GolonganNama              pgtype.Text        `db:"golongan_nama"`
	PangkatNama               pgtype.Text        `db:"pangkat_nama"`
	SkNomor                   pgtype.Text        `db:"sk_nomor"`
	NoBkn                     pgtype.Text        `db:"no_bkn"`
	JumlahAngkaKreditUtama    pgtype.Int2        `db:"jumlah_angka_kredit_utama"`
	JumlahAngkaKreditTambahan pgtype.Int2        `db:"jumlah_angka_kredit_tambahan"`
	MkGolonganTahun           pgtype.Int2        `db:"mk_golongan_tahun"`
	MkGolonganBulan           pgtype.Int2        `db:"mk_golongan_bulan"`
	SkTanggal                 pgtype.Date        `db:"sk_tanggal"`
	TanggalBkn                pgtype.Date        `db:"tanggal_bkn"`
	TmtGolongan               pgtype.Date        `db:"tmt_golongan"`
	StatusSatker              pgtype.Int4        `db:"status_satker"`
	StatusBiro                pgtype.Int4        `db:"status_biro"`
	PangkatTerakhir           pgtype.Int4        `db:"pangkat_terakhir"`
	BknID                     pgtype.Text        `db:"bkn_id"`
	FileBase64                pgtype.Text        `db:"file_base64"`
	KeteranganBerkas          pgtype.Text        `db:"keterangan_berkas"`
	ArsipID                   pgtype.Int8        `db:"arsip_id"`
	GolonganAsal              pgtype.Text        `db:"golongan_asal"`
	Basic                     pgtype.Text        `db:"basic"`
	SkType                    pgtype.Int2        `db:"sk_type"`
	Kanreg                    pgtype.Text        `db:"kanreg"`
	Kpkn                      pgtype.Text        `db:"kpkn"`
	Keterangan                pgtype.Text        `db:"keterangan"`
	Lpnk                      pgtype.Text        `db:"lpnk"`
	JenisRiwayat              pgtype.Text        `db:"jenis_riwayat"`
	CreatedAt                 pgtype.Timestamptz `db:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `db:"updated_at"`
	DeletedAt                 pgtype.Timestamptz `db:"deleted_at"`
	JenisKpID                 pgtype.Int4        `db:"jenis_kp_id"`
}

type RiwayatHukdi struct {
	ID                  int64              `db:"id"`
	PnsID               pgtype.Text        `db:"pns_id"`
	PnsNip              pgtype.Text        `db:"pns_nip"`
	Nama                pgtype.Text        `db:"nama"`
	GolonganID          pgtype.Int2        `db:"golongan_id"`
	NamaGolongan        pgtype.Text        `db:"nama_golongan"`
	JenisHukumanID      pgtype.Int2        `db:"jenis_hukuman_id"`
	NamaJenisHukuman    pgtype.Text        `db:"nama_jenis_hukuman"`
	SkNomor             pgtype.Text        `db:"sk_nomor"`
	SkTanggal           pgtype.Date        `db:"sk_tanggal"`
	TanggalMulaiHukuman pgtype.Date        `db:"tanggal_mulai_hukuman"`
	MasaTahun           pgtype.Int2        `db:"masa_tahun"`
	MasaBulan           pgtype.Int2        `db:"masa_bulan"`
	TanggalAkhirHukuman pgtype.Date        `db:"tanggal_akhir_hukuman"`
	NoPp                pgtype.Text        `db:"no_pp"`
	NoSkPembatalan      pgtype.Text        `db:"no_sk_pembatalan"`
	TanggalSkPembatalan pgtype.Date        `db:"tanggal_sk_pembatalan"`
	BknID               pgtype.Text        `db:"bkn_id"`
	FileBase64          pgtype.Text        `db:"file_base64"`
	KeteranganBerkas    pgtype.Text        `db:"keterangan_berkas"`
	CreatedAt           pgtype.Timestamptz `db:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at"`
	DeletedAt           pgtype.Timestamptz `db:"deleted_at"`
}

type RiwayatJabatan struct {
	BknID                   pgtype.Text        `db:"bkn_id"`
	PnsID                   pgtype.Text        `db:"pns_id"`
	PnsNip                  pgtype.Text        `db:"pns_nip"`
	PnsNama                 pgtype.Text        `db:"pns_nama"`
	UnorID                  pgtype.Text        `db:"unor_id"`
	Unor                    pgtype.Text        `db:"unor"`
	JenisJabatanID          pgtype.Int4        `db:"jenis_jabatan_id"`
	JenisJabatan            pgtype.Text        `db:"jenis_jabatan"`
	JabatanID               pgtype.Int4        `db:"jabatan_id"`
	NamaJabatan             pgtype.Text        `db:"nama_jabatan"`
	EselonID                pgtype.Text        `db:"eselon_id"`
	Eselon                  pgtype.Text        `db:"eselon"`
	TmtJabatan              pgtype.Date        `db:"tmt_jabatan"`
	NoSk                    pgtype.Text        `db:"no_sk"`
	TanggalSk               pgtype.Date        `db:"tanggal_sk"`
	SatuanKerjaID           pgtype.Text        `db:"satuan_kerja_id"`
	TmtPelantikan           pgtype.Date        `db:"tmt_pelantikan"`
	IsActive                pgtype.Int2        `db:"is_active"`
	Eselon1                 pgtype.Text        `db:"eselon1"`
	Eselon2                 pgtype.Text        `db:"eselon2"`
	Eselon3                 pgtype.Text        `db:"eselon3"`
	Eselon4                 pgtype.Text        `db:"eselon4"`
	ID                      int64              `db:"id"`
	Catatan                 pgtype.Text        `db:"catatan"`
	JenisSk                 pgtype.Text        `db:"jenis_sk"`
	StatusSatker            pgtype.Int4        `db:"status_satker"`
	StatusBiro              pgtype.Int4        `db:"status_biro"`
	JabatanIDBkn            pgtype.Text        `db:"jabatan_id_bkn"`
	UnorIDBkn               pgtype.Text        `db:"unor_id_bkn"`
	TabelMutasiID           pgtype.Int8        `db:"tabel_mutasi_id"`
	CreatedAt               pgtype.Timestamptz `db:"created_at"`
	UpdatedAt               pgtype.Timestamptz `db:"updated_at"`
	DeletedAt               pgtype.Timestamptz `db:"deleted_at"`
	StatusPlt               pgtype.Bool        `db:"status_plt"`
	KelasJabatanID          pgtype.Int4        `db:"kelas_jabatan_id"`
	PeriodeJabatanStartDate pgtype.Date        `db:"periode_jabatan_start_date"`
	PeriodeJabatanEndDate   pgtype.Date        `db:"periode_jabatan_end_date"`
}

type RiwayatKgb struct {
	PegawaiID          pgtype.Int4        `db:"pegawai_id"`
	TmtSk              pgtype.Date        `db:"tmt_sk"`
	Alasan             pgtype.Text        `db:"alasan"`
	MvKgbID            pgtype.Int8        `db:"mv_kgb_id"`
	NoSk               pgtype.Text        `db:"no_sk"`
	Pejabat            pgtype.Text        `db:"pejabat"`
	ID                 int64              `db:"id"`
	Ref                pgtype.Text        `db:"ref"`
	TglSk              pgtype.Date        `db:"tgl_sk"`
	PegawaiNama        pgtype.Text        `db:"pegawai_nama"`
	PegawaiNip         pgtype.Text        `db:"pegawai_nip"`
	BirthPlace         pgtype.Text        `db:"birth_place"`
	BirthDate          pgtype.Date        `db:"birth_date"`
	NGolRuang          pgtype.Text        `db:"n_gol_ruang"`
	NGolTmt            pgtype.Date        `db:"n_gol_tmt"`
	NMasakerjaThn      pgtype.Int2        `db:"n_masakerja_thn"`
	NMasakerjaBln      pgtype.Int2        `db:"n_masakerja_bln"`
	NGapok             pgtype.Text        `db:"n_gapok"`
	NJabatanText       pgtype.Text        `db:"n_jabatan_text"`
	NTmtJabatan        pgtype.Date        `db:"n_tmt_jabatan"`
	NGolonganID        pgtype.Int4        `db:"n_golongan_id"`
	UnitKerjaIndukText pgtype.Text        `db:"unit_kerja_induk_text"`
	UnitKerjaIndukID   pgtype.Text        `db:"unit_kerja_induk_id"`
	KantorPembayaran   pgtype.Text        `db:"kantor_pembayaran"`
	LastEducation      pgtype.Text        `db:"last_education"`
	LastEducationDate  pgtype.Date        `db:"last_education_date"`
	CreatedAt          pgtype.Timestamptz `db:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at"`
	DeletedAt          pgtype.Timestamptz `db:"deleted_at"`
}

type RiwayatKinerja struct {
	ID                        int32              `db:"id"`
	Tahun                     pgtype.Int4        `db:"tahun"`
	Nip                       pgtype.Text        `db:"nip"`
	Nama                      pgtype.Text        `db:"nama"`
	NipPenilai                pgtype.Text        `db:"nip_penilai"`
	NamaPenilai               pgtype.Text        `db:"nama_penilai"`
	JabatanPenilai            pgtype.Text        `db:"jabatan_penilai"`
	UnitKerjaPenilai          pgtype.Text        `db:"unit_kerja_penilai"`
	NipPenilaiRealisasi       pgtype.Text        `db:"nip_penilai_realisasi"`
	NamaPenilaiRealisasi      pgtype.Text        `db:"nama_penilai_realisasi"`
	JabatanPenilaiRealisasi   pgtype.Text        `db:"jabatan_penilai_realisasi"`
	UnitKerjaPenilaiRealisasi pgtype.Text        `db:"unit_kerja_penilai_realisasi"`
	RatingHasilKerja          pgtype.Text        `db:"rating_hasil_kerja"`
	RatingPerilakuKerja       pgtype.Text        `db:"rating_perilaku_kerja"`
	PredikatKinerja           pgtype.Text        `db:"predikat_kinerja"`
	Ref                       pgtype.UUID        `db:"ref"`
	CreatedAt                 pgtype.Timestamptz `db:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `db:"updated_at"`
	DeletedAt                 pgtype.Timestamptz `db:"deleted_at"`
}

type RiwayatKursu struct {
	ID                     int32              `db:"id"`
	PnsNip                 pgtype.Text        `db:"pns_nip"`
	TipeKursus             pgtype.Text        `db:"tipe_kursus"`
	JenisKursus            pgtype.Text        `db:"jenis_kursus"`
	NamaKursus             pgtype.Text        `db:"nama_kursus"`
	LamaKursus             pgtype.Float8      `db:"lama_kursus"`
	TanggalKursus          pgtype.Date        `db:"tanggal_kursus"`
	NoSertifikat           pgtype.Text        `db:"no_sertifikat"`
	Instansi               pgtype.Text        `db:"instansi"`
	InstitusiPenyelenggara pgtype.Text        `db:"institusi_penyelenggara"`
	SiasnID                pgtype.Text        `db:"siasn_id"`
	PnsID                  pgtype.Text        `db:"pns_id"`
	CreatedAt              pgtype.Timestamptz `db:"created_at"`
	UpdatedAt              pgtype.Timestamptz `db:"updated_at"`
	DeletedAt              pgtype.Timestamptz `db:"deleted_at"`
}

type RiwayatNineBox struct {
	ID           int32              `db:"id"`
	PnsNip       pgtype.Text        `db:"pns_nip"`
	Nama         pgtype.Text        `db:"nama"`
	NamaJabatan  pgtype.Text        `db:"nama_jabatan"`
	KelasJabatan pgtype.Int2        `db:"kelas_jabatan"`
	Kesimpulan   pgtype.Text        `db:"kesimpulan"`
	Tahun        pgtype.Text        `db:"tahun"`
	CreatedAt    pgtype.Timestamptz `db:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at"`
	DeletedAt    pgtype.Timestamptz `db:"deleted_at"`
}

type RiwayatPendidikan struct {
	ID                  int32              `db:"id"`
	PnsID3              pgtype.Text        `db:"pns_id_3"`
	TingkatPendidikanID pgtype.Int2        `db:"tingkat_pendidikan_id"`
	PendidikanID3       pgtype.Text        `db:"pendidikan_id_3"`
	TanggalLulus        pgtype.Date        `db:"tanggal_lulus"`
	NoIjazah            pgtype.Text        `db:"no_ijazah"`
	NamaSekolah         pgtype.Text        `db:"nama_sekolah"`
	GelarDepan          pgtype.Text        `db:"gelar_depan"`
	GelarBelakang       pgtype.Text        `db:"gelar_belakang"`
	PendidikanPertama   pgtype.Text        `db:"pendidikan_pertama"`
	NegaraSekolah       pgtype.Text        `db:"negara_sekolah"`
	TahunLulus          pgtype.Text        `db:"tahun_lulus"`
	Nip                 pgtype.Text        `db:"nip"`
	DiakuiBkn           pgtype.Int4        `db:"diakui_bkn"`
	StatusSatker        pgtype.Int4        `db:"status_satker"`
	StatusBiro          pgtype.Int4        `db:"status_biro"`
	PendidikanTerakhir  pgtype.Int4        `db:"pendidikan_terakhir"`
	PnsID               pgtype.Text        `db:"pns_id"`
	PendidikanID        pgtype.Text        `db:"pendidikan_id"`
	CreatedAt           pgtype.Timestamptz `db:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at"`
	DeletedAt           pgtype.Timestamptz `db:"deleted_at"`
	TugasBelajar        pgtype.Int2        `db:"tugas_belajar"`
}

type RiwayatPenghargaanUmum struct {
	ID                   int32              `db:"id"`
	JenisPenghargaan     pgtype.Text        `db:"jenis_penghargaan"`
	DeskripsiPenghargaan pgtype.Text        `db:"deskripsi_penghargaan"`
	TanggalPenghargaan   pgtype.Date        `db:"tanggal_penghargaan"`
	Exist                pgtype.Bool        `db:"exist"`
	FileBase64           pgtype.Text        `db:"file_base64"`
	Nip                  pgtype.Text        `db:"nip"`
	NamaPenghargaan      pgtype.Text        `db:"nama_penghargaan"`
	CreatedAt            pgtype.Timestamptz `db:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at"`
	DeletedAt            pgtype.Timestamptz `db:"deleted_at"`
}

type RiwayatPenugasan struct {
	ID               int32              `db:"id"`
	TipeJabatan      pgtype.Text        `db:"tipe_jabatan"`
	DeskripsiJabatan pgtype.Text        `db:"deskripsi_jabatan"`
	TanggalMulai     pgtype.Date        `db:"tanggal_mulai"`
	TanggalSelesai   pgtype.Date        `db:"tanggal_selesai"`
	FileBase64       pgtype.Text        `db:"file_base64"`
	Nip              pgtype.Text        `db:"nip"`
	NamaJabatan      pgtype.Text        `db:"nama_jabatan"`
	IsMenjabat       pgtype.Bool        `db:"is_menjabat"`
	CreatedAt        pgtype.Timestamptz `db:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at"`
}

type RiwayatPindahUnitKerja struct {
	ID               int64              `db:"id"`
	PnsID            pgtype.Text        `db:"pns_id"`
	PnsNip           pgtype.Text        `db:"pns_nip"`
	PnsNama          pgtype.Text        `db:"pns_nama"`
	SkNomor          pgtype.Text        `db:"sk_nomor"`
	AsalID           pgtype.Text        `db:"asal_id"`
	AsalNama         pgtype.Text        `db:"asal_nama"`
	UnorIDBaru       pgtype.Text        `db:"unor_id_baru"`
	NamaUnorBaru     pgtype.Text        `db:"nama_unor_baru"`
	InstansiID       pgtype.Text        `db:"instansi_id"`
	NamaInstansi     pgtype.Text        `db:"nama_instansi"`
	SkTanggal        pgtype.Date        `db:"sk_tanggal"`
	SatuanKerjaID    pgtype.Text        `db:"satuan_kerja_id"`
	NamaSatuanKerja  pgtype.Text        `db:"nama_satuan_kerja"`
	FileBase64       pgtype.Text        `db:"file_base64"`
	KeteranganBerkas pgtype.Text        `db:"keterangan_berkas"`
	CreatedAt        pgtype.Timestamptz `db:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at"`
}

type RiwayatSertifikasi struct {
	ID              int64              `db:"id"`
	Nip             pgtype.Text        `db:"nip"`
	Tahun           pgtype.Int8        `db:"tahun"`
	NamaSertifikasi pgtype.Text        `db:"nama_sertifikasi"`
	FileBase64      pgtype.Text        `db:"file_base64"`
	Deskripsi       pgtype.Text        `db:"deskripsi"`
	CreatedAt       pgtype.Timestamptz `db:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at"`
	DeletedAt       pgtype.Timestamptz `db:"deleted_at"`
}

type RiwayatUjikom struct {
	ID             int64              `db:"id"`
	JenisUjikom    pgtype.Text        `db:"jenis_ujikom"`
	NipBaru        pgtype.Text        `db:"nip_baru"`
	LinkSertifikat pgtype.Text        `db:"link_sertifikat"`
	Exist          pgtype.Bool        `db:"exist"`
	Tahun          pgtype.Int4        `db:"tahun"`
	CreatedAt      pgtype.Timestamptz `db:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at"`
	DeletedAt      pgtype.Timestamptz `db:"deleted_at"`
}

type TingkatPendidikan struct {
	ID             int32              `db:"id"`
	GolonganID     pgtype.Int4        `db:"golongan_id"`
	Nama           pgtype.Text        `db:"nama"`
	GolonganAwalID pgtype.Int4        `db:"golongan_awal_id"`
	Abbreviation   pgtype.Text        `db:"abbreviation"`
	Tingkat        pgtype.Int2        `db:"tingkat"`
	CreatedAt      pgtype.Timestamptz `db:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at"`
	DeletedAt      pgtype.Timestamptz `db:"deleted_at"`
}

type UnitKerja struct {
	ID                   string             `db:"id"`
	No                   pgtype.Int4        `db:"no"`
	KodeInternal         pgtype.Text        `db:"kode_internal"`
	NamaUnor             pgtype.Text        `db:"nama_unor"`
	EselonID             pgtype.Text        `db:"eselon_id"`
	CepatKode            pgtype.Text        `db:"cepat_kode"`
	NamaJabatan          pgtype.Text        `db:"nama_jabatan"`
	NamaPejabat          pgtype.Text        `db:"nama_pejabat"`
	DiatasanID           pgtype.Text        `db:"diatasan_id"`
	InstansiID           pgtype.Text        `db:"instansi_id"`
	PemimpinPnsID        pgtype.Text        `db:"pemimpin_pns_id"`
	JenisUnorID          pgtype.Text        `db:"jenis_unor_id"`
	UnorInduk            pgtype.Text        `db:"unor_induk"`
	JumlahIdealStaff     pgtype.Int2        `db:"jumlah_ideal_staff"`
	Order                pgtype.Int4        `db:"order"`
	IsSatker             int16              `db:"is_satker"`
	Eselon1              pgtype.Text        `db:"eselon_1"`
	Eselon2              pgtype.Text        `db:"eselon_2"`
	Eselon3              pgtype.Text        `db:"eselon_3"`
	Eselon4              pgtype.Text        `db:"eselon_4"`
	ExpiredDate          pgtype.Date        `db:"expired_date"`
	Keterangan           pgtype.Text        `db:"keterangan"`
	JenisSatker          pgtype.Text        `db:"jenis_satker"`
	Abbreviation         pgtype.Text        `db:"abbreviation"`
	UnorIndukPenyetaraan pgtype.Text        `db:"unor_induk_penyetaraan"`
	JabatanID            pgtype.Text        `db:"jabatan_id"`
	Waktu                pgtype.Text        `db:"waktu"`
	Peraturan            pgtype.Text        `db:"peraturan"`
	Remark               pgtype.Text        `db:"remark"`
	Aktif                pgtype.Bool        `db:"aktif"`
	EselonNama           pgtype.Text        `db:"eselon_nama"`
	CreatedAt            pgtype.Timestamptz `db:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at"`
	DeletedAt            pgtype.Timestamptz `db:"deleted_at"`
}

type UpdateMandiri struct {
	ID            int32              `db:"id"`
	PnsID         pgtype.Text        `db:"pns_id"`
	Kolom         pgtype.Text        `db:"kolom"`
	Dari          pgtype.Text        `db:"dari"`
	Perubahan     pgtype.Text        `db:"perubahan"`
	Status        pgtype.Int4        `db:"status"`
	VerifikasiBy  pgtype.Int4        `db:"verifikasi_by"`
	VerifikasiTgl pgtype.Date        `db:"verifikasi_tgl"`
	NamaKolom     pgtype.Text        `db:"nama_kolom"`
	LevelUpdate   pgtype.Int4        `db:"level_update"`
	TabelID       pgtype.Int4        `db:"tabel_id"`
	UpdatedBy     pgtype.Int4        `db:"updated_by"`
	CreatedAt     pgtype.Timestamptz `db:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at"`
	DeletedAt     pgtype.Timestamptz `db:"deleted_at"`
}
