// Code generated by sqlc. DO NOT EDIT.
// source: pegawai.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPegawaiAktif = `-- name: CountPegawaiAktif :one
SELECT
  COUNT(1)
FROM pegawai
LEFT JOIN ref_unit_kerja uk
    ON pegawai.unor_id = uk.id AND uk.deleted_at IS NULL
JOIN ref_kedudukan_hukum
    ON ref_kedudukan_hukum.id = pegawai.kedudukan_hukum_id AND ref_kedudukan_hukum.deleted_at IS NULL
WHERE
    ref_kedudukan_hukum.is_pegawai_aktif = TRUE
    AND ($1::varchar is null or ref_kedudukan_hukum.nama = $1::varchar)
    AND (
        $2::VARCHAR IS NULL
        OR (
            pegawai.nama ILIKE '%' || $2::VARCHAR || '%'
            OR pegawai.nip_baru ILIKE '%' || $2::VARCHAR || '%'
        )
    )
    AND (
        $3::VARCHAR IS NULL
        OR $3::VARCHAR = uk.id
        OR $3::VARCHAR = uk.eselon_1
        OR $3::VARCHAR = uk.eselon_2
        OR $3::VARCHAR = uk.eselon_3
        OR $3::VARCHAR = uk.eselon_4
    )
    AND ( $4::INTEGER IS NULL OR pegawai.gol_id = $4::INTEGER )
    AND ( $5::VARCHAR IS NULL OR pegawai.jabatan_instansi_id = $5::VARCHAR )
    AND (
        $6::varchar[] IS NULL
        OR ( pegawai.status_cpns_pns = ANY($6::VARCHAR[]) AND ref_kedudukan_hukum.nama <> $7::varchar )
    )
    AND pegawai.deleted_at IS NULL
`

type CountPegawaiAktifParams struct {
	StatusHukum pgtype.Text `db:"status_hukum"`
	Keyword     pgtype.Text `db:"keyword"`
	UnitKerjaID pgtype.Text `db:"unit_kerja_id"`
	GolonganID  pgtype.Int4 `db:"golongan_id"`
	JabatanID   pgtype.Text `db:"jabatan_id"`
	StatusPns   []string    `db:"status_pns"`
	Mpp         string      `db:"mpp"`
}

func (q *Queries) CountPegawaiAktif(ctx context.Context, arg CountPegawaiAktifParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPegawaiAktif,
		arg.StatusHukum,
		arg.Keyword,
		arg.UnitKerjaID,
		arg.GolonganID,
		arg.JabatanID,
		arg.StatusPns,
		arg.Mpp,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPegawaiNonAktif = `-- name: CountPegawaiNonAktif :one
SELECT COUNT(1)
FROM pegawai p
	LEFT JOIN ref_unit_kerja uk ON p.unor_id = uk.id AND uk.deleted_at IS NULL
	JOIN ref_kedudukan_hukum
	    ON ref_kedudukan_hukum.id = p.kedudukan_hukum_id AND ref_kedudukan_hukum.deleted_at IS NULL
WHERE p.id is not null
  AND (p.kedudukan_hukum_id = '99' or p.status_pegawai = 3)
	AND ($1::varchar is null or ref_kedudukan_hukum.nama = $1::varchar)
	AND (
	    $2::VARCHAR IS NULL
	    OR $2::VARCHAR = uk.id
	    OR $2::VARCHAR = uk.eselon_1
	    OR $2::VARCHAR = uk.eselon_2
	    OR $2::VARCHAR = uk.eselon_3
	    OR $2::VARCHAR = uk.eselon_4
	)
	AND (
	    $3::VARCHAR IS NULL
	    OR (
		p.nama ILIKE '%' || $3::VARCHAR || '%'
		OR p.nip_baru ILIKE '%' || $3::VARCHAR || '%'
	    )
	)
	AND (
		$4::VARCHAR IS NULL
		OR p.nip_baru = $4::VARCHAR
	)
	AND ( $5::INTEGER IS NULL OR p.gol_id = $5::INTEGER )
	AND ( $6::VARCHAR IS NULL OR p.jabatan_instansi_id = $6::VARCHAR )
	AND (
		$7::varchar[] IS NULL
		OR ( p.status_cpns_pns = ANY($7::VARCHAR[]) AND ref_kedudukan_hukum.nama <> $8::varchar )
	    )
	AND p.deleted_at IS NULL
`

type CountPegawaiNonAktifParams struct {
	StatusHukum pgtype.Text `db:"status_hukum"`
	UnitKerjaID pgtype.Text `db:"unit_kerja_id"`
	Keyword     pgtype.Text `db:"keyword"`
	Nip         pgtype.Text `db:"nip"`
	GolonganID  pgtype.Int4 `db:"golongan_id"`
	JabatanID   pgtype.Text `db:"jabatan_id"`
	StatusPns   []string    `db:"status_pns"`
	Mpp         string      `db:"mpp"`
}

func (q *Queries) CountPegawaiNonAktif(ctx context.Context, arg CountPegawaiNonAktifParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPegawaiNonAktif,
		arg.StatusHukum,
		arg.UnitKerjaID,
		arg.Keyword,
		arg.Nip,
		arg.GolonganID,
		arg.JabatanID,
		arg.StatusPns,
		arg.Mpp,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPegawaiPPPK = `-- name: CountPegawaiPPPK :one
SELECT COUNT(1)
FROM pegawai p
	LEFT JOIN ref_unit_kerja uk ON p.unor_id = uk.id AND uk.deleted_at IS NULL
	JOIN ref_kedudukan_hukum
	    ON ref_kedudukan_hukum.id = p.kedudukan_hukum_id AND ref_kedudukan_hukum.deleted_at IS NULL
WHERE p.id is not null 
	AND p.status_pegawai = 3
	AND ($1::varchar is null or ref_kedudukan_hukum.nama = $1::varchar)
	AND (
	    $2::VARCHAR IS NULL
	    OR $2::VARCHAR = uk.id
	    OR $2::VARCHAR = uk.eselon_1
	    OR $2::VARCHAR = uk.eselon_2
	    OR $2::VARCHAR = uk.eselon_3
	    OR $2::VARCHAR = uk.eselon_4
	)
	AND (
	    $3::VARCHAR IS NULL
	    OR (
		p.nama ILIKE '%' || $3::VARCHAR || '%'
		OR p.nip_baru ILIKE '%' || $3::VARCHAR || '%'
	    )
	)
	AND (
		$4::VARCHAR IS NULL
		OR p.nip_baru = $4::VARCHAR
	)
	AND ( $5::INTEGER IS NULL OR p.gol_id = $5::INTEGER )
	AND ( $6::VARCHAR IS NULL OR p.jabatan_instansi_id = $6::VARCHAR )
	AND (
		$7::varchar[] IS NULL
		OR ( p.status_cpns_pns = ANY($7::VARCHAR[]) AND ref_kedudukan_hukum.nama <> $8::varchar )
	    )
	AND p.deleted_at IS NULL
`

type CountPegawaiPPPKParams struct {
	StatusHukum pgtype.Text `db:"status_hukum"`
	UnitKerjaID pgtype.Text `db:"unit_kerja_id"`
	Keyword     pgtype.Text `db:"keyword"`
	Nip         pgtype.Text `db:"nip"`
	GolonganID  pgtype.Int4 `db:"golongan_id"`
	JabatanID   pgtype.Text `db:"jabatan_id"`
	StatusPns   []string    `db:"status_pns"`
	Mpp         string      `db:"mpp"`
}

func (q *Queries) CountPegawaiPPPK(ctx context.Context, arg CountPegawaiPPPKParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPegawaiPPPK,
		arg.StatusHukum,
		arg.UnitKerjaID,
		arg.Keyword,
		arg.Nip,
		arg.GolonganID,
		arg.JabatanID,
		arg.StatusPns,
		arg.Mpp,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPegawaiByNIP = `-- name: GetPegawaiByNIP :one
select
    pegawai.id as id,
    pns_id,
    nip_baru as nip,
    pegawai.nama as nama,
    tanggal_lahir,
    coalesce(ref_lokasi.nama, tempat_lahir) as tempat_lahir
FROM pegawai
LEFT JOIN ref_lokasi on ref_lokasi.id = pegawai.tempat_lahir_id and ref_lokasi.deleted_at is null
where nip_baru = $1::varchar and pegawai.deleted_at is null
`

type GetPegawaiByNIPRow struct {
	ID           int32       `db:"id"`
	PnsID        string      `db:"pns_id"`
	Nip          pgtype.Text `db:"nip"`
	Nama         pgtype.Text `db:"nama"`
	TanggalLahir pgtype.Date `db:"tanggal_lahir"`
	TempatLahir  pgtype.Text `db:"tempat_lahir"`
}

func (q *Queries) GetPegawaiByNIP(ctx context.Context, nip string) (GetPegawaiByNIPRow, error) {
	row := q.db.QueryRow(ctx, getPegawaiByNIP, nip)
	var i GetPegawaiByNIPRow
	err := row.Scan(
		&i.ID,
		&i.PnsID,
		&i.Nip,
		&i.Nama,
		&i.TanggalLahir,
		&i.TempatLahir,
	)
	return i, err
}

const getPegawaiNIKByNIP = `-- name: GetPegawaiNIKByNIP :one
SELECT nik::text FROM pegawai WHERE nip_baru = $1::varchar AND deleted_at IS NULL
`

func (q *Queries) GetPegawaiNIKByNIP(ctx context.Context, nip string) (string, error) {
	row := q.db.QueryRow(ctx, getPegawaiNIKByNIP, nip)
	var nik string
	err := row.Scan(&nik)
	return nik, err
}

const getPegawaiPNSIDByNIP = `-- name: GetPegawaiPNSIDByNIP :one
SELECT pns_id FROM pegawai WHERE nip_baru = $1::varchar AND deleted_at IS NULL
`

func (q *Queries) GetPegawaiPNSIDByNIP(ctx context.Context, nip string) (string, error) {
	row := q.db.QueryRow(ctx, getPegawaiPNSIDByNIP, nip)
	var pns_id string
	err := row.Scan(&pns_id)
	return pns_id, err
}

const getPegawaiTTDByNIP = `-- name: GetPegawaiTTDByNIP :one
SELECT base64ttd FROM pegawai_ttd WHERE nip = $1::varchar
`

func (q *Queries) GetPegawaiTTDByNIP(ctx context.Context, nip string) (string, error) {
	row := q.db.QueryRow(ctx, getPegawaiTTDByNIP, nip)
	var base64ttd string
	err := row.Scan(&base64ttd)
	return base64ttd, err
}

const getProfilePegawaiByPNSID = `-- name: GetProfilePegawaiByPNSID :one
select
  p.nip_lama,
  p.nip_baru,
  p.gelar_depan,
  p.gelar_belakang,
  p.nama,
  p.unor_id,
  rj.nama_jabatan as jabatan,
  rg.nama_pangkat as pangkat,
  case when rkh.is_pppk then rg.gol_pppk else rg.nama end as golongan,
  p.foto
from pegawai p
left join ref_jabatan rj on rj.kode_jabatan = p.jabatan_instansi_id and rj.deleted_at is null
left join ref_golongan rg on rg.id = p.gol_id and rg.deleted_at is null
left join ref_kedudukan_hukum rkh on rkh.id = p.kedudukan_hukum_id and rkh.deleted_at is null
where pns_id = $1 and p.deleted_at is null
`

type GetProfilePegawaiByPNSIDRow struct {
	NipLama       pgtype.Text `db:"nip_lama"`
	NipBaru       pgtype.Text `db:"nip_baru"`
	GelarDepan    pgtype.Text `db:"gelar_depan"`
	GelarBelakang pgtype.Text `db:"gelar_belakang"`
	Nama          pgtype.Text `db:"nama"`
	UnorID        pgtype.Text `db:"unor_id"`
	Jabatan       pgtype.Text `db:"jabatan"`
	Pangkat       pgtype.Text `db:"pangkat"`
	Golongan      interface{} `db:"golongan"`
	Foto          pgtype.Text `db:"foto"`
}

func (q *Queries) GetProfilePegawaiByPNSID(ctx context.Context, pnsID string) (GetProfilePegawaiByPNSIDRow, error) {
	row := q.db.QueryRow(ctx, getProfilePegawaiByPNSID, pnsID)
	var i GetProfilePegawaiByPNSIDRow
	err := row.Scan(
		&i.NipLama,
		&i.NipBaru,
		&i.GelarDepan,
		&i.GelarBelakang,
		&i.Nama,
		&i.UnorID,
		&i.Jabatan,
		&i.Pangkat,
		&i.Golongan,
		&i.Foto,
	)
	return i, err
}

const listPegawaiAktif = `-- name: ListPegawaiAktif :many
SELECT
    pegawai.pns_id,
    pegawai.nip_baru AS nip,
    pegawai.nama,
    pegawai.gelar_depan,
    pegawai.gelar_belakang,
    ref_golongan_akhir.nama AS golongan,
    ref_jabatan.nama_jabatan AS jabatan,
    pegawai.unor_id,
    ref_kedudukan_hukum.nama as nama_kedudukuan_hukum,
    status_cpns_pns,
    pegawai.foto
FROM pegawai
LEFT JOIN ref_unit_kerja uk
    ON pegawai.unor_id = uk.id AND uk.deleted_at IS NULL
JOIN ref_kedudukan_hukum
    ON ref_kedudukan_hukum.id = pegawai.kedudukan_hukum_id AND ref_kedudukan_hukum.deleted_at IS NULL
LEFT JOIN ref_jabatan
    ON ref_jabatan.kode_jabatan = pegawai.jabatan_instansi_id AND ref_jabatan.deleted_at IS NULL
LEFT JOIN ref_golongan ref_golongan_akhir
    ON ref_golongan_akhir.id = pegawai.gol_id AND ref_golongan_akhir.deleted_at IS NULL
WHERE
    ref_kedudukan_hukum.is_pegawai_aktif = TRUE
    AND ($3::varchar is null or ref_kedudukan_hukum.nama = $3::varchar)
    AND (
        $4::VARCHAR IS NULL
        OR (
            pegawai.nama ILIKE '%' || $4::VARCHAR || '%'
            OR pegawai.nip_baru ILIKE '%' || $4::VARCHAR || '%'
        )
    )
    AND (
        $5::VARCHAR IS NULL
        OR $5::VARCHAR = uk.id
        OR $5::VARCHAR = uk.eselon_1
        OR $5::VARCHAR = uk.eselon_2
        OR $5::VARCHAR = uk.eselon_3
        OR $5::VARCHAR = uk.eselon_4
    )
    AND ( $6::INTEGER IS NULL OR pegawai.gol_id = $6::INTEGER )
    AND ( $7::VARCHAR IS NULL OR pegawai.jabatan_instansi_id = $7::VARCHAR )
    AND (
        $8::varchar[] IS NULL
        OR ( pegawai.status_cpns_pns = ANY($8::VARCHAR[]) AND ref_kedudukan_hukum.nama <> $9::varchar )
    )
    AND pegawai.deleted_at IS NULL
LIMIT $1 OFFSET $2
`

type ListPegawaiAktifParams struct {
	Limit       int32       `db:"limit"`
	Offset      int32       `db:"offset"`
	StatusHukum pgtype.Text `db:"status_hukum"`
	Keyword     pgtype.Text `db:"keyword"`
	UnitKerjaID pgtype.Text `db:"unit_kerja_id"`
	GolonganID  pgtype.Int4 `db:"golongan_id"`
	JabatanID   pgtype.Text `db:"jabatan_id"`
	StatusPns   []string    `db:"status_pns"`
	Mpp         string      `db:"mpp"`
}

type ListPegawaiAktifRow struct {
	PnsID               string      `db:"pns_id"`
	Nip                 pgtype.Text `db:"nip"`
	Nama                pgtype.Text `db:"nama"`
	GelarDepan          pgtype.Text `db:"gelar_depan"`
	GelarBelakang       pgtype.Text `db:"gelar_belakang"`
	Golongan            pgtype.Text `db:"golongan"`
	Jabatan             pgtype.Text `db:"jabatan"`
	UnorID              pgtype.Text `db:"unor_id"`
	NamaKedudukuanHukum pgtype.Text `db:"nama_kedudukuan_hukum"`
	StatusCpnsPns       pgtype.Text `db:"status_cpns_pns"`
	Foto                pgtype.Text `db:"foto"`
}

func (q *Queries) ListPegawaiAktif(ctx context.Context, arg ListPegawaiAktifParams) ([]ListPegawaiAktifRow, error) {
	rows, err := q.db.Query(ctx, listPegawaiAktif,
		arg.Limit,
		arg.Offset,
		arg.StatusHukum,
		arg.Keyword,
		arg.UnitKerjaID,
		arg.GolonganID,
		arg.JabatanID,
		arg.StatusPns,
		arg.Mpp,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPegawaiAktifRow
	for rows.Next() {
		var i ListPegawaiAktifRow
		if err := rows.Scan(
			&i.PnsID,
			&i.Nip,
			&i.Nama,
			&i.GelarDepan,
			&i.GelarBelakang,
			&i.Golongan,
			&i.Jabatan,
			&i.UnorID,
			&i.NamaKedudukuanHukum,
			&i.StatusCpnsPns,
			&i.Foto,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPegawaiNonAktif = `-- name: ListPegawaiNonAktif :many
SELECT 
	p.pns_id,
	p.nip_baru AS nip,
	p.nama,
	p.gelar_depan,
	p.gelar_belakang,
	p.foto,
	p.unor_id,
	p.status_cpns_pns,
	uk.nama_unor,
	ref_golongan_akhir.nama AS golongan,
	ref_jabatan.nama_jabatan AS jabatan,
	ref_kedudukan_hukum.nama as nama_kedudukuan_hukum
FROM pegawai p
	LEFT JOIN ref_unit_kerja uk ON p.unor_id = uk.id AND uk.deleted_at IS NULL
	JOIN ref_kedudukan_hukum
	    ON ref_kedudukan_hukum.id = p.kedudukan_hukum_id AND ref_kedudukan_hukum.deleted_at IS NULL
	LEFT JOIN ref_jabatan
	    ON ref_jabatan.kode_jabatan = p.jabatan_instansi_id AND ref_jabatan.deleted_at IS NULL
	LEFT JOIN ref_golongan ref_golongan_akhir
	    ON ref_golongan_akhir.id = p.gol_id AND ref_golongan_akhir.deleted_at IS NULL
WHERE p.id is not null
	AND (p.kedudukan_hukum_id = '99' or p.status_pegawai = 3)
	AND ($3::varchar is null or ref_kedudukan_hukum.nama = $3::varchar)
	AND (
	    $4::VARCHAR IS NULL
	    OR $4::VARCHAR = uk.id
	    OR $4::VARCHAR = uk.eselon_1
	    OR $4::VARCHAR = uk.eselon_2
	    OR $4::VARCHAR = uk.eselon_3
	    OR $4::VARCHAR = uk.eselon_4
	)
	AND (
	    $5::VARCHAR IS NULL
	    OR (
		p.nama ILIKE '%' || $5::VARCHAR || '%'
		OR p.nip_baru ILIKE '%' || $5::VARCHAR || '%'
	    )
	)
	AND (
		$6::VARCHAR IS NULL
		OR p.nip_baru = $6::VARCHAR
	)
	AND ( $7::INTEGER IS NULL OR p.gol_id = $7::INTEGER )
	AND ( $8::VARCHAR IS NULL OR p.jabatan_instansi_id = $8::VARCHAR )
	AND (
		$9::varchar[] IS NULL
		OR ( p.status_cpns_pns = ANY($9::VARCHAR[]) AND ref_kedudukan_hukum.nama <> $10::varchar )
	    )
	AND p.deleted_at IS NULL
ORDER BY p.nama ASC
LIMIT $1 OFFSET $2
`

type ListPegawaiNonAktifParams struct {
	Limit       int32       `db:"limit"`
	Offset      int32       `db:"offset"`
	StatusHukum pgtype.Text `db:"status_hukum"`
	UnitKerjaID pgtype.Text `db:"unit_kerja_id"`
	Keyword     pgtype.Text `db:"keyword"`
	Nip         pgtype.Text `db:"nip"`
	GolonganID  pgtype.Int4 `db:"golongan_id"`
	JabatanID   pgtype.Text `db:"jabatan_id"`
	StatusPns   []string    `db:"status_pns"`
	Mpp         string      `db:"mpp"`
}

type ListPegawaiNonAktifRow struct {
	PnsID               string      `db:"pns_id"`
	Nip                 pgtype.Text `db:"nip"`
	Nama                pgtype.Text `db:"nama"`
	GelarDepan          pgtype.Text `db:"gelar_depan"`
	GelarBelakang       pgtype.Text `db:"gelar_belakang"`
	Foto                pgtype.Text `db:"foto"`
	UnorID              pgtype.Text `db:"unor_id"`
	StatusCpnsPns       pgtype.Text `db:"status_cpns_pns"`
	NamaUnor            pgtype.Text `db:"nama_unor"`
	Golongan            pgtype.Text `db:"golongan"`
	Jabatan             pgtype.Text `db:"jabatan"`
	NamaKedudukuanHukum pgtype.Text `db:"nama_kedudukuan_hukum"`
}

func (q *Queries) ListPegawaiNonAktif(ctx context.Context, arg ListPegawaiNonAktifParams) ([]ListPegawaiNonAktifRow, error) {
	rows, err := q.db.Query(ctx, listPegawaiNonAktif,
		arg.Limit,
		arg.Offset,
		arg.StatusHukum,
		arg.UnitKerjaID,
		arg.Keyword,
		arg.Nip,
		arg.GolonganID,
		arg.JabatanID,
		arg.StatusPns,
		arg.Mpp,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPegawaiNonAktifRow
	for rows.Next() {
		var i ListPegawaiNonAktifRow
		if err := rows.Scan(
			&i.PnsID,
			&i.Nip,
			&i.Nama,
			&i.GelarDepan,
			&i.GelarBelakang,
			&i.Foto,
			&i.UnorID,
			&i.StatusCpnsPns,
			&i.NamaUnor,
			&i.Golongan,
			&i.Jabatan,
			&i.NamaKedudukuanHukum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPegawaiPPPK = `-- name: ListPegawaiPPPK :many
SELECT 
	p.pns_id,
	p.nip_baru AS nip,
	p.nama,
	p.gelar_depan,
	p.gelar_belakang,
	p.foto,
	p.unor_id,
	p.status_cpns_pns,
	uk.nama_unor,
	ref_golongan_akhir.nama AS golongan,
	ref_jabatan.nama_jabatan AS jabatan,
	ref_kedudukan_hukum.nama as nama_kedudukuan_hukum
FROM pegawai p
	LEFT JOIN ref_unit_kerja as uk ON p.unor_id = uk.id AND uk.deleted_at IS NULL
	JOIN ref_kedudukan_hukum
	    ON ref_kedudukan_hukum.id = p.kedudukan_hukum_id AND ref_kedudukan_hukum.deleted_at IS NULL
	LEFT JOIN ref_jabatan
	    ON ref_jabatan.kode_jabatan = p.jabatan_instansi_id AND ref_jabatan.deleted_at IS NULL
	LEFT JOIN ref_golongan ref_golongan_akhir
	    ON ref_golongan_akhir.id = p.gol_id AND ref_golongan_akhir.deleted_at IS NULL
WHERE p.id is not null
	AND p.status_pegawai = 3
	AND ($3::varchar is null or ref_kedudukan_hukum.nama = $3::varchar)
	AND (
	    $4::VARCHAR IS NULL
	    OR $4::VARCHAR = uk.id
	    OR $4::VARCHAR = uk.eselon_1
	    OR $4::VARCHAR = uk.eselon_2
	    OR $4::VARCHAR = uk.eselon_3
	    OR $4::VARCHAR = uk.eselon_4
	)
	AND (
	    $5::VARCHAR IS NULL
	    OR (
		p.nama ILIKE '%' || $5::VARCHAR || '%'
		OR p.nip_baru ILIKE '%' || $5::VARCHAR || '%'
	    )
	)
	AND (
		$6::VARCHAR IS NULL
		OR p.nip_baru = $6::VARCHAR
	)
	AND ( $7::INTEGER IS NULL OR p.gol_id = $7::INTEGER )
	AND ( $8::VARCHAR IS NULL OR p.jabatan_instansi_id = $8::VARCHAR )
	AND p.deleted_at IS NULL
ORDER BY p.nama ASC
LIMIT $1 OFFSET $2
`

type ListPegawaiPPPKParams struct {
	Limit       int32       `db:"limit"`
	Offset      int32       `db:"offset"`
	StatusHukum pgtype.Text `db:"status_hukum"`
	UnitKerjaID pgtype.Text `db:"unit_kerja_id"`
	Keyword     pgtype.Text `db:"keyword"`
	Nip         pgtype.Text `db:"nip"`
	GolonganID  pgtype.Int4 `db:"golongan_id"`
	JabatanID   pgtype.Text `db:"jabatan_id"`
}

type ListPegawaiPPPKRow struct {
	PnsID               string      `db:"pns_id"`
	Nip                 pgtype.Text `db:"nip"`
	Nama                pgtype.Text `db:"nama"`
	GelarDepan          pgtype.Text `db:"gelar_depan"`
	GelarBelakang       pgtype.Text `db:"gelar_belakang"`
	Foto                pgtype.Text `db:"foto"`
	UnorID              pgtype.Text `db:"unor_id"`
	StatusCpnsPns       pgtype.Text `db:"status_cpns_pns"`
	NamaUnor            pgtype.Text `db:"nama_unor"`
	Golongan            pgtype.Text `db:"golongan"`
	Jabatan             pgtype.Text `db:"jabatan"`
	NamaKedudukuanHukum pgtype.Text `db:"nama_kedudukuan_hukum"`
}

func (q *Queries) ListPegawaiPPPK(ctx context.Context, arg ListPegawaiPPPKParams) ([]ListPegawaiPPPKRow, error) {
	rows, err := q.db.Query(ctx, listPegawaiPPPK,
		arg.Limit,
		arg.Offset,
		arg.StatusHukum,
		arg.UnitKerjaID,
		arg.Keyword,
		arg.Nip,
		arg.GolonganID,
		arg.JabatanID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPegawaiPPPKRow
	for rows.Next() {
		var i ListPegawaiPPPKRow
		if err := rows.Scan(
			&i.PnsID,
			&i.Nip,
			&i.Nama,
			&i.GelarDepan,
			&i.GelarBelakang,
			&i.Foto,
			&i.UnorID,
			&i.StatusCpnsPns,
			&i.NamaUnor,
			&i.Golongan,
			&i.Jabatan,
			&i.NamaKedudukuanHukum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDataPegawai = `-- name: UpdateDataPegawai :exec
UPDATE pegawai
SET
    gelar_depan = $1::varchar,
    nama = $2::varchar,
    gelar_belakang = $3::varchar,
    nip_baru = $4::varchar,
    jenis_kelamin = $5::varchar,
    nik = $6::varchar,
    kk = $7::varchar,
    tempat_lahir_id = $8::varchar,
    tanggal_lahir = $9::date,
    tingkat_pendidikan_id = $10::int2,
    pendidikan_id = $11::varchar,
    jenis_kawin_id = $12::int2,
    agama_id = $13::int2,
    jenis_pegawai_id = $14::int2,
    masa_kerja = $15::varchar,
    jenis_jabatan_id = $16::int2,
    jabatan_instansi_id = $17::varchar,
    unor_id = $18::varchar,
    lokasi_kerja_id = $19::varchar,
    gol_awal_id = $20::int2,
    gol_id = $21::int2,
    tmt_golongan = $22::date,
    tmt_pns = $23::date,
    no_sk_cpns = $24::varchar,
    status_cpns_pns = $25::varchar,
    email_dikbud = $26::varchar,
    email = $27::varchar,
    alamat = $28::varchar,
    no_hp = $29::varchar,
    no_darurat = $30::varchar,
    no_surat_dokter = $31::varchar,
    tanggal_surat_dokter = $32::date,
    no_bebas_narkoba = $33::varchar,
    tanggal_bebas_narkoba = $34::date,
    no_catatan_polisi = $35::varchar,
    tanggal_catatan_polisi = $36::date,
    akte_kelahiran = $37::varchar,
    bpjs = $38::varchar,
    npwp = $39::varchar,
    tanggal_npwp = $40::date,
    no_taspen = $41::varchar,
    updated_at = now(),
    pns_id = $42::varchar,
    mk_bulan = $43::int2,
    mk_tahun = $44::int2,
    mk_bulan_swasta = $45::int2,
    mk_tahun_swasta = $46::int2
WHERE nip_baru = $47::varchar AND deleted_at IS NULL
`

type UpdateDataPegawaiParams struct {
	GelarDepan           string      `db:"gelar_depan"`
	Nama                 string      `db:"nama"`
	GelarBelakang        string      `db:"gelar_belakang"`
	NipBaru              string      `db:"nip_baru"`
	JenisKelamin         string      `db:"jenis_kelamin"`
	Nik                  string      `db:"nik"`
	Kk                   string      `db:"kk"`
	TempatLahirID        string      `db:"tempat_lahir_id"`
	TanggalLahir         pgtype.Date `db:"tanggal_lahir"`
	TingkatPendidikanID  int16       `db:"tingkat_pendidikan_id"`
	PendidikanID         string      `db:"pendidikan_id"`
	JenisKawinID         int16       `db:"jenis_kawin_id"`
	AgamaID              int16       `db:"agama_id"`
	JenisPegawaiID       int16       `db:"jenis_pegawai_id"`
	MasaKerja            string      `db:"masa_kerja"`
	JenisJabatanID       int16       `db:"jenis_jabatan_id"`
	JabatanID            string      `db:"jabatan_id"`
	UnorID               string      `db:"unor_id"`
	LokasiKerjaID        string      `db:"lokasi_kerja_id"`
	GolAwalID            int16       `db:"gol_awal_id"`
	GolID                int16       `db:"gol_id"`
	TmtGolongan          pgtype.Date `db:"tmt_golongan"`
	TmtPns               pgtype.Date `db:"tmt_pns"`
	NoSkCpns             string      `db:"no_sk_cpns"`
	StatusCpnsPns        string      `db:"status_cpns_pns"`
	EmailDikbud          string      `db:"email_dikbud"`
	Email                string      `db:"email"`
	Alamat               string      `db:"alamat"`
	NoHp                 string      `db:"no_hp"`
	NoDarurat            string      `db:"no_darurat"`
	NoSuratDokter        string      `db:"no_surat_dokter"`
	TanggalSuratDokter   pgtype.Date `db:"tanggal_surat_dokter"`
	NoBebasNarkoba       string      `db:"no_bebas_narkoba"`
	TanggalBebasNarkoba  pgtype.Date `db:"tanggal_bebas_narkoba"`
	NoCatatanPolisi      string      `db:"no_catatan_polisi"`
	TanggalCatatanPolisi pgtype.Date `db:"tanggal_catatan_polisi"`
	AkteKelahiran        string      `db:"akte_kelahiran"`
	Bpjs                 string      `db:"bpjs"`
	Npwp                 string      `db:"npwp"`
	TanggalNpwp          pgtype.Date `db:"tanggal_npwp"`
	NoTaspen             string      `db:"no_taspen"`
	PnsID                string      `db:"pns_id"`
	MkBulan              int16       `db:"mk_bulan"`
	MkTahun              int16       `db:"mk_tahun"`
	MkBulanSwasta        int16       `db:"mk_bulan_swasta"`
	MkTahunSwasta        int16       `db:"mk_tahun_swasta"`
	Nip                  string      `db:"nip"`
}

func (q *Queries) UpdateDataPegawai(ctx context.Context, arg UpdateDataPegawaiParams) error {
	_, err := q.db.Exec(ctx, updateDataPegawai,
		arg.GelarDepan,
		arg.Nama,
		arg.GelarBelakang,
		arg.NipBaru,
		arg.JenisKelamin,
		arg.Nik,
		arg.Kk,
		arg.TempatLahirID,
		arg.TanggalLahir,
		arg.TingkatPendidikanID,
		arg.PendidikanID,
		arg.JenisKawinID,
		arg.AgamaID,
		arg.JenisPegawaiID,
		arg.MasaKerja,
		arg.JenisJabatanID,
		arg.JabatanID,
		arg.UnorID,
		arg.LokasiKerjaID,
		arg.GolAwalID,
		arg.GolID,
		arg.TmtGolongan,
		arg.TmtPns,
		arg.NoSkCpns,
		arg.StatusCpnsPns,
		arg.EmailDikbud,
		arg.Email,
		arg.Alamat,
		arg.NoHp,
		arg.NoDarurat,
		arg.NoSuratDokter,
		arg.TanggalSuratDokter,
		arg.NoBebasNarkoba,
		arg.TanggalBebasNarkoba,
		arg.NoCatatanPolisi,
		arg.TanggalCatatanPolisi,
		arg.AkteKelahiran,
		arg.Bpjs,
		arg.Npwp,
		arg.TanggalNpwp,
		arg.NoTaspen,
		arg.PnsID,
		arg.MkBulan,
		arg.MkTahun,
		arg.MkBulanSwasta,
		arg.MkTahunSwasta,
		arg.Nip,
	)
	return err
}

const updateTTDPegawaiNIPByNIP = `-- name: UpdateTTDPegawaiNIPByNIP :exec
UPDATE pegawai_ttd
SET 
    nip = $1::varchar,
    updated_at = now()
WHERE nip = $2::varchar
AND (
    ($1::varchar IS NOT NULL AND $1::varchar IS DISTINCT FROM nip)
)
`

type UpdateTTDPegawaiNIPByNIPParams struct {
	NipBaru string `db:"nip_baru"`
	Nip     string `db:"nip"`
}

func (q *Queries) UpdateTTDPegawaiNIPByNIP(ctx context.Context, arg UpdateTTDPegawaiNIPByNIPParams) error {
	_, err := q.db.Exec(ctx, updateTTDPegawaiNIPByNIP, arg.NipBaru, arg.Nip)
	return err
}
