// Code generated by sqlc. DO NOT EDIT.
// source: pegawai.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPegawaiAktif = `-- name: CountPegawaiAktif :one
SELECT
  COUNT(1)
FROM pegawai
LEFT JOIN ref_unit_kerja uk
    ON pegawai.unor_id = uk.id AND uk.deleted_at IS NULL
JOIN ref_kedudukan_hukum
    ON ref_kedudukan_hukum.id = pegawai.kedudukan_hukum_id AND ref_kedudukan_hukum.deleted_at IS NULL
WHERE
    ref_kedudukan_hukum.is_pegawai_aktif = TRUE
    AND ($1::varchar is null or ref_kedudukan_hukum.nama = $1::varchar)
    AND (
        $2::VARCHAR IS NULL
        OR (
            pegawai.nama ILIKE '%' || $2::VARCHAR || '%'
            OR pegawai.nip_baru ILIKE '%' || $2::VARCHAR || '%'
        )
    )
    AND (
        $3::VARCHAR IS NULL
        OR $3::VARCHAR = uk.id
        OR $3::VARCHAR = uk.eselon_1
        OR $3::VARCHAR = uk.eselon_2
        OR $3::VARCHAR = uk.eselon_3
        OR $3::VARCHAR = uk.eselon_4
    )
    AND ( $4::INTEGER IS NULL OR pegawai.gol_id = $4::INTEGER )
    AND ( $5::VARCHAR IS NULL OR pegawai.jabatan_instansi_id = $5::VARCHAR )
    AND (
        $6::varchar[] IS NULL
        OR ( pegawai.status_cpns_pns = ANY($6::VARCHAR[]) AND ref_kedudukan_hukum.nama <> $7::varchar )
    )
    AND pegawai.deleted_at IS NULL
`

type CountPegawaiAktifParams struct {
	StatusHukum pgtype.Text `db:"status_hukum"`
	Keyword     pgtype.Text `db:"keyword"`
	UnitKerjaID pgtype.Text `db:"unit_kerja_id"`
	GolonganID  pgtype.Int4 `db:"golongan_id"`
	JabatanID   pgtype.Text `db:"jabatan_id"`
	StatusPns   []string    `db:"status_pns"`
	Mpp         string      `db:"mpp"`
}

func (q *Queries) CountPegawaiAktif(ctx context.Context, arg CountPegawaiAktifParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPegawaiAktif,
		arg.StatusHukum,
		arg.Keyword,
		arg.UnitKerjaID,
		arg.GolonganID,
		arg.JabatanID,
		arg.StatusPns,
		arg.Mpp,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPegawaiNIKByNIP = `-- name: GetPegawaiNIKByNIP :one
SELECT nik::text FROM pegawai WHERE nip_baru = $1::varchar AND deleted_at IS NULL
`

func (q *Queries) GetPegawaiNIKByNIP(ctx context.Context, nip string) (string, error) {
	row := q.db.QueryRow(ctx, getPegawaiNIKByNIP, nip)
	var nik string
	err := row.Scan(&nik)
	return nik, err
}

const getPegawaiPNSIDByNIP = `-- name: GetPegawaiPNSIDByNIP :one
SELECT pns_id FROM pegawai WHERE nip_baru = $1::varchar AND deleted_at IS NULL
`

func (q *Queries) GetPegawaiPNSIDByNIP(ctx context.Context, nip string) (string, error) {
	row := q.db.QueryRow(ctx, getPegawaiPNSIDByNIP, nip)
	var pns_id string
	err := row.Scan(&pns_id)
	return pns_id, err
}

const getPegawaiTTDByNIP = `-- name: GetPegawaiTTDByNIP :one
SELECT base64ttd FROM pegawai_ttd WHERE nip = $1::varchar
`

func (q *Queries) GetPegawaiTTDByNIP(ctx context.Context, nip string) (string, error) {
	row := q.db.QueryRow(ctx, getPegawaiTTDByNIP, nip)
	var base64ttd string
	err := row.Scan(&base64ttd)
	return base64ttd, err
}

const getProfilePegawaiByPNSID = `-- name: GetProfilePegawaiByPNSID :one
select
  p.nip_lama,
  p.nip_baru,
  p.gelar_depan,
  p.gelar_belakang,
  p.nama,
  p.unor_id,
  rj.nama_jabatan as jabatan,
  rg.nama_pangkat as pangkat,
  case when rkh.is_pppk then rg.gol_pppk else rg.nama end as golongan,
  p.foto
from pegawai p
left join ref_jabatan rj on rj.kode_jabatan = p.jabatan_instansi_id and rj.deleted_at is null
left join ref_golongan rg on rg.id = p.gol_id and rg.deleted_at is null
left join ref_kedudukan_hukum rkh on rkh.id = p.kedudukan_hukum_id and rkh.deleted_at is null
where pns_id = $1 and p.deleted_at is null
`

type GetProfilePegawaiByPNSIDRow struct {
	NipLama       pgtype.Text `db:"nip_lama"`
	NipBaru       pgtype.Text `db:"nip_baru"`
	GelarDepan    pgtype.Text `db:"gelar_depan"`
	GelarBelakang pgtype.Text `db:"gelar_belakang"`
	Nama          pgtype.Text `db:"nama"`
	UnorID        pgtype.Text `db:"unor_id"`
	Jabatan       pgtype.Text `db:"jabatan"`
	Pangkat       pgtype.Text `db:"pangkat"`
	Golongan      interface{} `db:"golongan"`
	Foto          pgtype.Text `db:"foto"`
}

func (q *Queries) GetProfilePegawaiByPNSID(ctx context.Context, pnsID string) (GetProfilePegawaiByPNSIDRow, error) {
	row := q.db.QueryRow(ctx, getProfilePegawaiByPNSID, pnsID)
	var i GetProfilePegawaiByPNSIDRow
	err := row.Scan(
		&i.NipLama,
		&i.NipBaru,
		&i.GelarDepan,
		&i.GelarBelakang,
		&i.Nama,
		&i.UnorID,
		&i.Jabatan,
		&i.Pangkat,
		&i.Golongan,
		&i.Foto,
	)
	return i, err
}

const listPegawaiAktif = `-- name: ListPegawaiAktif :many
SELECT
    pegawai.pns_id,
    pegawai.nip_baru AS nip,
    pegawai.nama,
    pegawai.gelar_depan,
    pegawai.gelar_belakang,
    ref_golongan_akhir.nama AS golongan,
    ref_jabatan.nama_jabatan AS jabatan,
    pegawai.unor_id,
    ref_kedudukan_hukum.nama as nama_kedudukuan_hukum,
    status_cpns_pns,
    pegawai.foto
FROM pegawai
LEFT JOIN ref_unit_kerja uk
    ON pegawai.unor_id = uk.id AND uk.deleted_at IS NULL
JOIN ref_kedudukan_hukum
    ON ref_kedudukan_hukum.id = pegawai.kedudukan_hukum_id AND ref_kedudukan_hukum.deleted_at IS NULL
LEFT JOIN ref_jabatan
    ON ref_jabatan.kode_jabatan = pegawai.jabatan_instansi_id AND ref_jabatan.deleted_at IS NULL
LEFT JOIN ref_golongan ref_golongan_akhir
    ON ref_golongan_akhir.id = pegawai.gol_id AND ref_golongan_akhir.deleted_at IS NULL
WHERE
    ref_kedudukan_hukum.is_pegawai_aktif = TRUE
    AND ($3::varchar is null or ref_kedudukan_hukum.nama = $3::varchar)
    AND (
        $4::VARCHAR IS NULL
        OR (
            pegawai.nama ILIKE '%' || $4::VARCHAR || '%'
            OR pegawai.nip_baru ILIKE '%' || $4::VARCHAR || '%'
        )
    )
    AND (
        $5::VARCHAR IS NULL
        OR $5::VARCHAR = uk.id
        OR $5::VARCHAR = uk.eselon_1
        OR $5::VARCHAR = uk.eselon_2
        OR $5::VARCHAR = uk.eselon_3
        OR $5::VARCHAR = uk.eselon_4
    )
    AND ( $6::INTEGER IS NULL OR pegawai.gol_id = $6::INTEGER )
    AND ( $7::VARCHAR IS NULL OR pegawai.jabatan_instansi_id = $7::VARCHAR )
    AND (
        $8::varchar[] IS NULL
        OR ( pegawai.status_cpns_pns = ANY($8::VARCHAR[]) AND ref_kedudukan_hukum.nama <> $9::varchar )
    )
    AND pegawai.deleted_at IS NULL
LIMIT $1 OFFSET $2
`

type ListPegawaiAktifParams struct {
	Limit       int32       `db:"limit"`
	Offset      int32       `db:"offset"`
	StatusHukum pgtype.Text `db:"status_hukum"`
	Keyword     pgtype.Text `db:"keyword"`
	UnitKerjaID pgtype.Text `db:"unit_kerja_id"`
	GolonganID  pgtype.Int4 `db:"golongan_id"`
	JabatanID   pgtype.Text `db:"jabatan_id"`
	StatusPns   []string    `db:"status_pns"`
	Mpp         string      `db:"mpp"`
}

type ListPegawaiAktifRow struct {
	PnsID               string      `db:"pns_id"`
	Nip                 pgtype.Text `db:"nip"`
	Nama                pgtype.Text `db:"nama"`
	GelarDepan          pgtype.Text `db:"gelar_depan"`
	GelarBelakang       pgtype.Text `db:"gelar_belakang"`
	Golongan            pgtype.Text `db:"golongan"`
	Jabatan             pgtype.Text `db:"jabatan"`
	UnorID              pgtype.Text `db:"unor_id"`
	NamaKedudukuanHukum pgtype.Text `db:"nama_kedudukuan_hukum"`
	StatusCpnsPns       pgtype.Text `db:"status_cpns_pns"`
	Foto                pgtype.Text `db:"foto"`
}

func (q *Queries) ListPegawaiAktif(ctx context.Context, arg ListPegawaiAktifParams) ([]ListPegawaiAktifRow, error) {
	rows, err := q.db.Query(ctx, listPegawaiAktif,
		arg.Limit,
		arg.Offset,
		arg.StatusHukum,
		arg.Keyword,
		arg.UnitKerjaID,
		arg.GolonganID,
		arg.JabatanID,
		arg.StatusPns,
		arg.Mpp,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPegawaiAktifRow
	for rows.Next() {
		var i ListPegawaiAktifRow
		if err := rows.Scan(
			&i.PnsID,
			&i.Nip,
			&i.Nama,
			&i.GelarDepan,
			&i.GelarBelakang,
			&i.Golongan,
			&i.Jabatan,
			&i.UnorID,
			&i.NamaKedudukuanHukum,
			&i.StatusCpnsPns,
			&i.Foto,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
