// Code generated by sqlc. DO NOT EDIT.
// source: pelatihan_teknis.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPelatihanTeknis = `-- name: CountPelatihanTeknis :one
SELECT COUNT(1)
FROM riwayat_kursus rk
JOIN pegawai p ON rk.pns_id = p.pns_id
WHERE p.nip_baru = $1
  AND p.deleted_at IS NULL
  AND rk.deleted_at IS NULL
`

func (q *Queries) CountPelatihanTeknis(ctx context.Context, nipBaru pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countPelatihanTeknis, nipBaru)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listPelatihanTeknis = `-- name: ListPelatihanTeknis :many
SELECT
    rk.id,
    rk.tipe_kursus,
    rk.jenis_kursus,
    rk.nama_kursus,
    rk.tanggal_kursus,
    EXTRACT(YEAR FROM rk.tanggal_kursus) as tahun,
    COALESCE(rk.lama_kursus, 0) as durasi,
    rk.institusi_penyelenggara,
    rk.no_sertifikat
FROM riwayat_kursus rk
JOIN pegawai p ON rk.pns_id = p.pns_id
WHERE p.nip_baru = $1
  AND p.deleted_at IS NULL
  AND rk.deleted_at IS NULL
ORDER BY rk.tanggal_kursus DESC NULLS LAST
LIMIT $2 OFFSET $3
`

type ListPelatihanTeknisParams struct {
	NipBaru pgtype.Text `db:"nip_baru"`
	Limit   int32       `db:"limit"`
	Offset  int32       `db:"offset"`
}

type ListPelatihanTeknisRow struct {
	ID                     int32          `db:"id"`
	TipeKursus             pgtype.Text    `db:"tipe_kursus"`
	JenisKursus            pgtype.Text    `db:"jenis_kursus"`
	NamaKursus             pgtype.Text    `db:"nama_kursus"`
	TanggalKursus          pgtype.Date    `db:"tanggal_kursus"`
	Tahun                  pgtype.Numeric `db:"tahun"`
	Durasi                 float64        `db:"durasi"`
	InstitusiPenyelenggara pgtype.Text    `db:"institusi_penyelenggara"`
	NoSertifikat           pgtype.Text    `db:"no_sertifikat"`
}

func (q *Queries) ListPelatihanTeknis(ctx context.Context, arg ListPelatihanTeknisParams) ([]ListPelatihanTeknisRow, error) {
	rows, err := q.db.Query(ctx, listPelatihanTeknis, arg.NipBaru, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPelatihanTeknisRow
	for rows.Next() {
		var i ListPelatihanTeknisRow
		if err := rows.Scan(
			&i.ID,
			&i.TipeKursus,
			&i.JenisKursus,
			&i.NamaKursus,
			&i.TanggalKursus,
			&i.Tahun,
			&i.Durasi,
			&i.InstitusiPenyelenggara,
			&i.NoSertifikat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
