// Code generated by sqlc. DO NOT EDIT.
// source: pendidikan_formal.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listPendidikanFormal = `-- name: ListPendidikanFormal :many
SELECT 
    rp.id,
    rp.nama_sekolah,
    rp.tahun_lulus,
    rp.no_ijazah,
    rp.gelar_depan,
    rp.gelar_belakang,
    rp.tugas_belajar,
    rp.negara_sekolah,
    tk.nama as jenjang_pendidikan,
    pend.nama as pendidikan
FROM riwayat_pendidikan rp
    LEFT JOIN ref_tingkat_pendidikan tk ON tk.id = rp.tingkat_pendidikan_id AND rp.deleted_at IS NULL
    LEFT JOIN ref_pendidikan pend ON rp.pendidikan_id = pend.id AND pend.deleted_at IS NULL
JOIN pegawai p ON p.pns_id = rp.pns_id_3
WHERE p.nip_baru = $1
ORDER BY rp.tahun_lulus ASC
`

type ListPendidikanFormalRow struct {
	ID                int32       `db:"id"`
	NamaSekolah       pgtype.Text `db:"nama_sekolah"`
	TahunLulus        pgtype.Text `db:"tahun_lulus"`
	NoIjazah          pgtype.Text `db:"no_ijazah"`
	GelarDepan        pgtype.Text `db:"gelar_depan"`
	GelarBelakang     pgtype.Text `db:"gelar_belakang"`
	TugasBelajar      pgtype.Int2 `db:"tugas_belajar"`
	NegaraSekolah     pgtype.Text `db:"negara_sekolah"`
	JenjangPendidikan pgtype.Text `db:"jenjang_pendidikan"`
	Pendidikan        pgtype.Text `db:"pendidikan"`
}

func (q *Queries) ListPendidikanFormal(ctx context.Context, nipBaru pgtype.Text) ([]ListPendidikanFormalRow, error) {
	rows, err := q.db.Query(ctx, listPendidikanFormal, nipBaru)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendidikanFormalRow
	for rows.Next() {
		var i ListPendidikanFormalRow
		if err := rows.Scan(
			&i.ID,
			&i.NamaSekolah,
			&i.TahunLulus,
			&i.NoIjazah,
			&i.GelarDepan,
			&i.GelarBelakang,
			&i.TugasBelajar,
			&i.NegaraSekolah,
			&i.JenjangPendidikan,
			&i.Pendidikan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
