// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountJenisKP(ctx context.Context) (int64, error)
	CountPelatihanTeknis(ctx context.Context, nipBaru pgtype.Text) (int64, error)
	CountRefGolongan(ctx context.Context) (int64, error)
	CountRefJabatan(ctx context.Context) (int64, error)
	CountRefJenisDiklat(ctx context.Context) (int64, error)
	CountRefJenisHukuman(ctx context.Context) (int64, error)
	CountRefJenisJabatan(ctx context.Context) (int64, error)
	CountRefJenisPenghargaan(ctx context.Context) (int64, error)
	CountRiwayatHukdis(ctx context.Context, pnsNip pgtype.Text) (int64, error)
	CountRiwayatJabatan(ctx context.Context, pnsNip string) (int64, error)
	CountRiwayatKepangkatan(ctx context.Context, pnsNip string) (int64, error)
	CountRiwayatPendidikan(ctx context.Context, nip pgtype.Text) (int64, error)
	CountRiwayatPenghargaan(ctx context.Context, nip string) (int64, error)
	CountRiwayatSertifikasi(ctx context.Context, nip pgtype.Text) (int64, error)
	CountUnitKerja(ctx context.Context, arg CountUnitKerjaParams) (int64, error)
	GetBerkasRiwayatHukdis(ctx context.Context, arg GetBerkasRiwayatHukdisParams) (pgtype.Text, error)
	GetBerkasRiwayatPendidikan(ctx context.Context, arg GetBerkasRiwayatPendidikanParams) (pgtype.Text, error)
	GetBerkasRiwayatSertifikasi(ctx context.Context, arg GetBerkasRiwayatSertifikasiParams) (pgtype.Text, error)
	GetDataPribadi(ctx context.Context, arg GetDataPribadiParams) (GetDataPribadiRow, error)
	GetJenisKP(ctx context.Context, arg GetJenisKPParams) ([]GetJenisKPRow, error)
	GetRefGolongan(ctx context.Context, arg GetRefGolonganParams) ([]GetRefGolonganRow, error)
	GetUnitKerjaByNamaOrInduk(ctx context.Context, arg GetUnitKerjaByNamaOrIndukParams) ([]GetUnitKerjaByNamaOrIndukRow, error)
	ListAnakByNip(ctx context.Context, nipBaru pgtype.Text) ([]ListAnakByNipRow, error)
	ListOrangTuaByNip(ctx context.Context, nipBaru pgtype.Text) ([]ListOrangTuaByNipRow, error)
	ListPasanganByNip(ctx context.Context, nipBaru pgtype.Text) ([]ListPasanganByNipRow, error)
	ListPelatihanStruktural(ctx context.Context, nipBaru pgtype.Text) ([]ListPelatihanStrukturalRow, error)
	ListPelatihanTeknis(ctx context.Context, arg ListPelatihanTeknisParams) ([]ListPelatihanTeknisRow, error)
	ListRefJabatan(ctx context.Context, arg ListRefJabatanParams) ([]ListRefJabatanRow, error)
	ListRefJenisDiklat(ctx context.Context, arg ListRefJenisDiklatParams) ([]ListRefJenisDiklatRow, error)
	ListRefJenisHukuman(ctx context.Context, arg ListRefJenisHukumanParams) ([]ListRefJenisHukumanRow, error)
	ListRefJenisJabatan(ctx context.Context, arg ListRefJenisJabatanParams) ([]ListRefJenisJabatanRow, error)
	ListRefJenisPenghargaan(ctx context.Context, arg ListRefJenisPenghargaanParams) ([]ListRefJenisPenghargaanRow, error)
	ListRiwayatHukdis(ctx context.Context, arg ListRiwayatHukdisParams) ([]ListRiwayatHukdisRow, error)
	ListRiwayatJabatan(ctx context.Context, arg ListRiwayatJabatanParams) ([]ListRiwayatJabatanRow, error)
	ListRiwayatKepangkatan(ctx context.Context, arg ListRiwayatKepangkatanParams) ([]ListRiwayatKepangkatanRow, error)
	ListRiwayatPendidikan(ctx context.Context, arg ListRiwayatPendidikanParams) ([]ListRiwayatPendidikanRow, error)
	ListRiwayatPenghargaan(ctx context.Context, arg ListRiwayatPenghargaanParams) ([]ListRiwayatPenghargaanRow, error)
	ListRiwayatSertifikasi(ctx context.Context, arg ListRiwayatSertifikasiParams) ([]ListRiwayatSertifikasiRow, error)
	ListUnitKerjaHierarchy(ctx context.Context, id string) ([]ListUnitKerjaHierarchyRow, error)
}

var _ Querier = (*Queries)(nil)
