// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"context"
	"database/sql"
)

type Querier interface {
	GetChildrenByEmployeeID(ctx context.Context, pnsID sql.NullString) ([]GetChildrenByEmployeeIDRow, error)
	GetEmployeeFamilyData(ctx context.Context, id int32) (GetEmployeeFamilyDataRow, error)
	GetJenisKP(ctx context.Context, arg GetJenisKPParams) ([]GetJenisKPRow, error)
	GetParentsByEmployeeID(ctx context.Context, pnsID sql.NullString) ([]GetParentsByEmployeeIDRow, error)
	GetRefGolongan(ctx context.Context, arg GetRefGolonganParams) ([]GetRefGolonganRow, error)
	GetRefJabatan(ctx context.Context, arg GetRefJabatanParams) ([]GetRefJabatanRow, error)
	GetRefJenisJabatan(ctx context.Context, arg GetRefJenisJabatanParams) ([]GetRefJenisJabatanRow, error)
	GetSpouseByEmployeeID(ctx context.Context, pnsID sql.NullString) (GetSpouseByEmployeeIDRow, error)
	ListUnitKerjaByNamaOrInduk(ctx context.Context, arg ListUnitKerjaByNamaOrIndukParams) ([]ListUnitKerjaByNamaOrIndukRow, error)
}

var _ Querier = (*Queries)(nil)
