// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountJenisKP(ctx context.Context) (int64, error)
	CountRefGolongan(ctx context.Context) (int64, error)
	CountRefJabatan(ctx context.Context) (int64, error)
	CountRefJenisDiklat(ctx context.Context) (int64, error)
	CountRefJenisHukuman(ctx context.Context) (int64, error)
	CountRefJenisJabatan(ctx context.Context) (int64, error)
	CountRefJenisPenghargaan(ctx context.Context) (int64, error)
	CountRefTingkatPendidikan(ctx context.Context) (int64, error)
	CountRiwayatHukdis(ctx context.Context, pnsNip pgtype.Text) (int64, error)
	CountRiwayatJabatan(ctx context.Context, pnsNip string) (int64, error)
	CountRiwayatKepangkatan(ctx context.Context, pnsNip string) (int64, error)
	CountRiwayatPelatihanFungsional(ctx context.Context, nipBaru pgtype.Text) (int64, error)
	CountRiwayatPelatihanStruktural(ctx context.Context, pnsNip pgtype.Text) (int64, error)
	CountRiwayatPelatihanTeknis(ctx context.Context, pnsNip pgtype.Text) (int64, error)
	CountRiwayatPendidikan(ctx context.Context, nip pgtype.Text) (int64, error)
	CountRiwayatPenghargaan(ctx context.Context, nip string) (int64, error)
	CountRiwayatSertifikasi(ctx context.Context, nip pgtype.Text) (int64, error)
	CountUnitKerja(ctx context.Context, arg CountUnitKerjaParams) (int64, error)
	GetBerkasRiwayatHukdis(ctx context.Context, arg GetBerkasRiwayatHukdisParams) (pgtype.Text, error)
	GetBerkasRiwayatPelatihanFungsional(ctx context.Context, arg GetBerkasRiwayatPelatihanFungsionalParams) (pgtype.Text, error)
	GetBerkasRiwayatPelatihanStruktural(ctx context.Context, arg GetBerkasRiwayatPelatihanStrukturalParams) (pgtype.Text, error)
	GetBerkasRiwayatPelatihanTeknis(ctx context.Context, arg GetBerkasRiwayatPelatihanTeknisParams) (pgtype.Text, error)
	GetBerkasRiwayatPendidikan(ctx context.Context, arg GetBerkasRiwayatPendidikanParams) (pgtype.Text, error)
	GetBerkasRiwayatPenghargaan(ctx context.Context, arg GetBerkasRiwayatPenghargaanParams) (pgtype.Text, error)
	GetBerkasRiwayatSertifikasi(ctx context.Context, arg GetBerkasRiwayatSertifikasiParams) (pgtype.Text, error)
	GetDataPribadi(ctx context.Context, arg GetDataPribadiParams) (GetDataPribadiRow, error)
	ListAnakByNip(ctx context.Context, nipBaru pgtype.Text) ([]ListAnakByNipRow, error)
	ListJenisKP(ctx context.Context, arg ListJenisKPParams) ([]ListJenisKPRow, error)
	ListOrangTuaByNip(ctx context.Context, nipBaru pgtype.Text) ([]ListOrangTuaByNipRow, error)
	ListPasanganByNip(ctx context.Context, nipBaru pgtype.Text) ([]ListPasanganByNipRow, error)
	ListRefGolongan(ctx context.Context, arg ListRefGolonganParams) ([]ListRefGolonganRow, error)
	ListRefJabatan(ctx context.Context, arg ListRefJabatanParams) ([]ListRefJabatanRow, error)
	ListRefJenisDiklat(ctx context.Context, arg ListRefJenisDiklatParams) ([]ListRefJenisDiklatRow, error)
	ListRefJenisHukuman(ctx context.Context, arg ListRefJenisHukumanParams) ([]ListRefJenisHukumanRow, error)
	ListRefJenisJabatan(ctx context.Context, arg ListRefJenisJabatanParams) ([]ListRefJenisJabatanRow, error)
	ListRefJenisPenghargaan(ctx context.Context, arg ListRefJenisPenghargaanParams) ([]ListRefJenisPenghargaanRow, error)
	ListRefTingkatPendidikan(ctx context.Context, arg ListRefTingkatPendidikanParams) ([]ListRefTingkatPendidikanRow, error)
	ListRiwayatHukdis(ctx context.Context, arg ListRiwayatHukdisParams) ([]ListRiwayatHukdisRow, error)
	ListRiwayatJabatan(ctx context.Context, arg ListRiwayatJabatanParams) ([]ListRiwayatJabatanRow, error)
	ListRiwayatKepangkatan(ctx context.Context, arg ListRiwayatKepangkatanParams) ([]ListRiwayatKepangkatanRow, error)
	ListRiwayatPelatihanFungsional(ctx context.Context, arg ListRiwayatPelatihanFungsionalParams) ([]ListRiwayatPelatihanFungsionalRow, error)
	ListRiwayatPelatihanStruktural(ctx context.Context, arg ListRiwayatPelatihanStrukturalParams) ([]ListRiwayatPelatihanStrukturalRow, error)
	ListRiwayatPelatihanTeknis(ctx context.Context, arg ListRiwayatPelatihanTeknisParams) ([]ListRiwayatPelatihanTeknisRow, error)
	ListRiwayatPendidikan(ctx context.Context, arg ListRiwayatPendidikanParams) ([]ListRiwayatPendidikanRow, error)
	ListRiwayatPenghargaan(ctx context.Context, arg ListRiwayatPenghargaanParams) ([]ListRiwayatPenghargaanRow, error)
	ListRiwayatSertifikasi(ctx context.Context, arg ListRiwayatSertifikasiParams) ([]ListRiwayatSertifikasiRow, error)
	ListUnitKerjaByNamaOrInduk(ctx context.Context, arg ListUnitKerjaByNamaOrIndukParams) ([]ListUnitKerjaByNamaOrIndukRow, error)
	ListUnitKerjaHierarchy(ctx context.Context, id string) ([]ListUnitKerjaHierarchyRow, error)
}

var _ Querier = (*Queries)(nil)
