// Code generated by sqlc. DO NOT EDIT.
// source: ref_jenis_kenaikan_pangkat.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countJenisKenaikanPangkat = `-- name: CountJenisKenaikanPangkat :one
SELECT COUNT(1) FROM ref_jenis_kenaikan_pangkat
WHERE deleted_at IS NULL
`

func (q *Queries) CountJenisKenaikanPangkat(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countJenisKenaikanPangkat)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listJenisKenaikanPangkat = `-- name: ListJenisKenaikanPangkat :many
SELECT id, nama FROM ref_jenis_kenaikan_pangkat
WHERE deleted_at IS NULL
LIMIT $1 OFFSET $2
`

type ListJenisKenaikanPangkatParams struct {
	Limit  int32 `db:"limit"`
	Offset int32 `db:"offset"`
}

type ListJenisKenaikanPangkatRow struct {
	ID   int32       `db:"id"`
	Nama pgtype.Text `db:"nama"`
}

func (q *Queries) ListJenisKenaikanPangkat(ctx context.Context, arg ListJenisKenaikanPangkatParams) ([]ListJenisKenaikanPangkatRow, error) {
	rows, err := q.db.Query(ctx, listJenisKenaikanPangkat, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJenisKenaikanPangkatRow
	for rows.Next() {
		var i ListJenisKenaikanPangkatRow
		if err := rows.Scan(&i.ID, &i.Nama); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
