// Code generated by sqlc. DO NOT EDIT.
// source: ref_jenis_hukuman.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRefJenisHukuman = `-- name: CountRefJenisHukuman :one
SELECT COUNT(1) 
FROM ref_jenis_hukuman
WHERE deleted_at IS NULL
`

func (q *Queries) CountRefJenisHukuman(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRefJenisHukuman)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRefJenisHukuman = `-- name: CreateRefJenisHukuman :one
INSERT INTO ref_jenis_hukuman (nama, tingkat_hukuman)
VALUES ($1, $2)
RETURNING id, nama, tingkat_hukuman as tingkat
`

type CreateRefJenisHukumanParams struct {
	Nama    pgtype.Text `db:"nama"`
	Tingkat pgtype.Text `db:"tingkat"`
}

type CreateRefJenisHukumanRow struct {
	ID      int32       `db:"id"`
	Nama    pgtype.Text `db:"nama"`
	Tingkat pgtype.Text `db:"tingkat"`
}

func (q *Queries) CreateRefJenisHukuman(ctx context.Context, arg CreateRefJenisHukumanParams) (CreateRefJenisHukumanRow, error) {
	row := q.db.QueryRow(ctx, createRefJenisHukuman, arg.Nama, arg.Tingkat)
	var i CreateRefJenisHukumanRow
	err := row.Scan(&i.ID, &i.Nama, &i.Tingkat)
	return i, err
}

const deleteRefJenisHukuman = `-- name: DeleteRefJenisHukuman :execrows
UPDATE ref_jenis_hukuman
SET deleted_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) DeleteRefJenisHukuman(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRefJenisHukuman, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRefJenisHukuman = `-- name: GetRefJenisHukuman :one
SELECT id, nama, tingkat_hukuman as tingkat
FROM ref_jenis_hukuman
WHERE id = $1
  AND deleted_at IS NULL
`

type GetRefJenisHukumanRow struct {
	ID      int32       `db:"id"`
	Nama    pgtype.Text `db:"nama"`
	Tingkat pgtype.Text `db:"tingkat"`
}

func (q *Queries) GetRefJenisHukuman(ctx context.Context, id int32) (GetRefJenisHukumanRow, error) {
	row := q.db.QueryRow(ctx, getRefJenisHukuman, id)
	var i GetRefJenisHukumanRow
	err := row.Scan(&i.ID, &i.Nama, &i.Tingkat)
	return i, err
}

const isExistReferencesRiwayatHukumanDisiplinByID = `-- name: IsExistReferencesRiwayatHukumanDisiplinByID :one
SELECT EXISTS (
    SELECT 1
    FROM riwayat_hukuman_disiplin
    WHERE jenis_hukuman_id = $1::int
      AND deleted_at IS NULL
) AS exists
`

func (q *Queries) IsExistReferencesRiwayatHukumanDisiplinByID(ctx context.Context, dollar_1 int32) (bool, error) {
	row := q.db.QueryRow(ctx, isExistReferencesRiwayatHukumanDisiplinByID, dollar_1)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listRefJenisHukuman = `-- name: ListRefJenisHukuman :many
SELECT 
  id, 
  nama,
  tingkat_hukuman as tingkat
FROM ref_jenis_hukuman
WHERE deleted_at IS NULL
LIMIT $1 OFFSET $2
`

type ListRefJenisHukumanParams struct {
	Limit  int32 `db:"limit"`
	Offset int32 `db:"offset"`
}

type ListRefJenisHukumanRow struct {
	ID      int32       `db:"id"`
	Nama    pgtype.Text `db:"nama"`
	Tingkat pgtype.Text `db:"tingkat"`
}

func (q *Queries) ListRefJenisHukuman(ctx context.Context, arg ListRefJenisHukumanParams) ([]ListRefJenisHukumanRow, error) {
	rows, err := q.db.Query(ctx, listRefJenisHukuman, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRefJenisHukumanRow
	for rows.Next() {
		var i ListRefJenisHukumanRow
		if err := rows.Scan(&i.ID, &i.Nama, &i.Tingkat); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRefJenisHukuman = `-- name: UpdateRefJenisHukuman :one
UPDATE ref_jenis_hukuman
SET 
  nama = $2,
  tingkat_hukuman = $3
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, nama, tingkat_hukuman as tingkat
`

type UpdateRefJenisHukumanParams struct {
	ID      int32       `db:"id"`
	Nama    pgtype.Text `db:"nama"`
	Tingkat pgtype.Text `db:"tingkat"`
}

type UpdateRefJenisHukumanRow struct {
	ID      int32       `db:"id"`
	Nama    pgtype.Text `db:"nama"`
	Tingkat pgtype.Text `db:"tingkat"`
}

func (q *Queries) UpdateRefJenisHukuman(ctx context.Context, arg UpdateRefJenisHukumanParams) (UpdateRefJenisHukumanRow, error) {
	row := q.db.QueryRow(ctx, updateRefJenisHukuman, arg.ID, arg.Nama, arg.Tingkat)
	var i UpdateRefJenisHukumanRow
	err := row.Scan(&i.ID, &i.Nama, &i.Tingkat)
	return i, err
}
