// Code generated by sqlc. DO NOT EDIT.
// source: ref_golongan.sql

package repository

import (
	"context"
	"database/sql"
)

const getRefGolongan = `-- name: GetRefGolongan :many
SELECT id, nama, nama_pangkat FROM ref_golongan
LIMIT $1 OFFSET $2
`

type GetRefGolonganParams struct {
	Limit  int32 `db:"limit"`
	Offset int32 `db:"offset"`
}

type GetRefGolonganRow struct {
	ID          int32          `db:"id"`
	Nama        sql.NullString `db:"nama"`
	NamaPangkat sql.NullString `db:"nama_pangkat"`
}

func (q *Queries) GetRefGolongan(ctx context.Context, arg GetRefGolonganParams) ([]GetRefGolonganRow, error) {
	rows, err := q.db.Query(ctx, getRefGolongan, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRefGolonganRow
	for rows.Next() {
		var i GetRefGolonganRow
		if err := rows.Scan(&i.ID, &i.Nama, &i.NamaPangkat); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
