// Code generated by sqlc. DO NOT EDIT.
// source: ref_tingkat_pendidikan.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRefTingkatPendidikan = `-- name: CountRefTingkatPendidikan :one
SELECT COUNT(1)
FROM ref_tingkat_pendidikan
WHERE deleted_at IS NULL
`

func (q *Queries) CountRefTingkatPendidikan(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRefTingkatPendidikan)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRefTingkatPendidikan = `-- name: CreateRefTingkatPendidikan :one
INSERT INTO ref_tingkat_pendidikan (nama, abbreviation, golongan_id, golongan_awal_id, tingkat)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, nama, abbreviation, golongan_id, golongan_awal_id, tingkat
`

type CreateRefTingkatPendidikanParams struct {
	Nama           pgtype.Text `db:"nama"`
	Abbreviation   pgtype.Text `db:"abbreviation"`
	GolonganID     pgtype.Int4 `db:"golongan_id"`
	GolonganAwalID pgtype.Int4 `db:"golongan_awal_id"`
	Tingkat        pgtype.Int2 `db:"tingkat"`
}

type CreateRefTingkatPendidikanRow struct {
	ID             int32       `db:"id"`
	Nama           pgtype.Text `db:"nama"`
	Abbreviation   pgtype.Text `db:"abbreviation"`
	GolonganID     pgtype.Int4 `db:"golongan_id"`
	GolonganAwalID pgtype.Int4 `db:"golongan_awal_id"`
	Tingkat        pgtype.Int2 `db:"tingkat"`
}

func (q *Queries) CreateRefTingkatPendidikan(ctx context.Context, arg CreateRefTingkatPendidikanParams) (CreateRefTingkatPendidikanRow, error) {
	row := q.db.QueryRow(ctx, createRefTingkatPendidikan,
		arg.Nama,
		arg.Abbreviation,
		arg.GolonganID,
		arg.GolonganAwalID,
		arg.Tingkat,
	)
	var i CreateRefTingkatPendidikanRow
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Abbreviation,
		&i.GolonganID,
		&i.GolonganAwalID,
		&i.Tingkat,
	)
	return i, err
}

const deleteRefTingkatPendidikan = `-- name: DeleteRefTingkatPendidikan :execrows
UPDATE ref_tingkat_pendidikan
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteRefTingkatPendidikan(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRefTingkatPendidikan, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRefTingkatPendidikan = `-- name: GetRefTingkatPendidikan :one
SELECT
    tp.id,
    tp.nama,
    tp.golongan_id,
    tp.golongan_awal_id,
    tp.abbreviation,
    tp.tingkat
FROM ref_tingkat_pendidikan tp
WHERE tp.deleted_at IS NULL AND tp.id = $1::integer
`

type GetRefTingkatPendidikanRow struct {
	ID             int32       `db:"id"`
	Nama           pgtype.Text `db:"nama"`
	GolonganID     pgtype.Int4 `db:"golongan_id"`
	GolonganAwalID pgtype.Int4 `db:"golongan_awal_id"`
	Abbreviation   pgtype.Text `db:"abbreviation"`
	Tingkat        pgtype.Int2 `db:"tingkat"`
}

func (q *Queries) GetRefTingkatPendidikan(ctx context.Context, id int32) (GetRefTingkatPendidikanRow, error) {
	row := q.db.QueryRow(ctx, getRefTingkatPendidikan, id)
	var i GetRefTingkatPendidikanRow
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.GolonganID,
		&i.GolonganAwalID,
		&i.Abbreviation,
		&i.Tingkat,
	)
	return i, err
}

const listRefTingkatPendidikan = `-- name: ListRefTingkatPendidikan :many
SELECT
    tp.id,
    tp.nama,
    tp.golongan_id,
    tp.golongan_awal_id,
    tp.abbreviation,
    tp.tingkat,
    g.nama as nama_golongan,
    g2.nama as nama_golongan_awal
FROM ref_tingkat_pendidikan tp
LEFT JOIN ref_golongan g ON g.id = tp.golongan_id
LEFT JOIN ref_golongan g2 ON g2.id = tp.golongan_awal_id
WHERE tp.deleted_at IS NULL
LIMIT $1 OFFSET $2
`

type ListRefTingkatPendidikanParams struct {
	Limit  int32 `db:"limit"`
	Offset int32 `db:"offset"`
}

type ListRefTingkatPendidikanRow struct {
	ID               int32       `db:"id"`
	Nama             pgtype.Text `db:"nama"`
	GolonganID       pgtype.Int4 `db:"golongan_id"`
	GolonganAwalID   pgtype.Int4 `db:"golongan_awal_id"`
	Abbreviation     pgtype.Text `db:"abbreviation"`
	Tingkat          pgtype.Int2 `db:"tingkat"`
	NamaGolongan     pgtype.Text `db:"nama_golongan"`
	NamaGolonganAwal pgtype.Text `db:"nama_golongan_awal"`
}

func (q *Queries) ListRefTingkatPendidikan(ctx context.Context, arg ListRefTingkatPendidikanParams) ([]ListRefTingkatPendidikanRow, error) {
	rows, err := q.db.Query(ctx, listRefTingkatPendidikan, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRefTingkatPendidikanRow
	for rows.Next() {
		var i ListRefTingkatPendidikanRow
		if err := rows.Scan(
			&i.ID,
			&i.Nama,
			&i.GolonganID,
			&i.GolonganAwalID,
			&i.Abbreviation,
			&i.Tingkat,
			&i.NamaGolongan,
			&i.NamaGolonganAwal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRefTingkatPendidikan = `-- name: UpdateRefTingkatPendidikan :one
UPDATE ref_tingkat_pendidikan
SET nama = $1, abbreviation = $2, golongan_id = $3, golongan_awal_id = $4, tingkat = $5
WHERE id = $6 AND deleted_at IS NULL
RETURNING id, nama, abbreviation, golongan_id, golongan_awal_id, tingkat
`

type UpdateRefTingkatPendidikanParams struct {
	Nama           pgtype.Text `db:"nama"`
	Abbreviation   pgtype.Text `db:"abbreviation"`
	GolonganID     pgtype.Int4 `db:"golongan_id"`
	GolonganAwalID pgtype.Int4 `db:"golongan_awal_id"`
	Tingkat        pgtype.Int2 `db:"tingkat"`
	ID             int32       `db:"id"`
}

type UpdateRefTingkatPendidikanRow struct {
	ID             int32       `db:"id"`
	Nama           pgtype.Text `db:"nama"`
	Abbreviation   pgtype.Text `db:"abbreviation"`
	GolonganID     pgtype.Int4 `db:"golongan_id"`
	GolonganAwalID pgtype.Int4 `db:"golongan_awal_id"`
	Tingkat        pgtype.Int2 `db:"tingkat"`
}

func (q *Queries) UpdateRefTingkatPendidikan(ctx context.Context, arg UpdateRefTingkatPendidikanParams) (UpdateRefTingkatPendidikanRow, error) {
	row := q.db.QueryRow(ctx, updateRefTingkatPendidikan,
		arg.Nama,
		arg.Abbreviation,
		arg.GolonganID,
		arg.GolonganAwalID,
		arg.Tingkat,
		arg.ID,
	)
	var i UpdateRefTingkatPendidikanRow
	err := row.Scan(
		&i.ID,
		&i.Nama,
		&i.Abbreviation,
		&i.GolonganID,
		&i.GolonganAwalID,
		&i.Tingkat,
	)
	return i, err
}
