// Code generated by sqlc. DO NOT EDIT.
// source: ref_jenis_penghargaan.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRefJenisPenghargaan = `-- name: CountRefJenisPenghargaan :one
SELECT COUNT(1) 
FROM ref_jenis_penghargaan
WHERE deleted_at IS NULL
`

func (q *Queries) CountRefJenisPenghargaan(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRefJenisPenghargaan)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listRefJenisPenghargaan = `-- name: ListRefJenisPenghargaan :many
SELECT 
  id, 
  nama 
FROM ref_jenis_penghargaan
WHERE deleted_at IS NULL
LIMIT $1 OFFSET $2
`

type ListRefJenisPenghargaanParams struct {
	Limit  int32 `db:"limit"`
	Offset int32 `db:"offset"`
}

type ListRefJenisPenghargaanRow struct {
	ID   int32       `db:"id"`
	Nama pgtype.Text `db:"nama"`
}

func (q *Queries) ListRefJenisPenghargaan(ctx context.Context, arg ListRefJenisPenghargaanParams) ([]ListRefJenisPenghargaanRow, error) {
	rows, err := q.db.Query(ctx, listRefJenisPenghargaan, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRefJenisPenghargaanRow
	for rows.Next() {
		var i ListRefJenisPenghargaanRow
		if err := rows.Scan(&i.ID, &i.Nama); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
