// Code generated by sqlc. DO NOT EDIT.
// source: ref_jenis_satker.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRefJenisSatker = `-- name: CountRefJenisSatker :one
SELECT COUNT(*) AS total
FROM ref_jenis_satker
WHERE deleted_at IS NULL
  AND ($1::varchar IS NULL OR nama ILIKE '%' || $1 || '%')
`

func (q *Queries) CountRefJenisSatker(ctx context.Context, nama pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countRefJenisSatker, nama)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createRefJenisSatker = `-- name: CreateRefJenisSatker :one
INSERT INTO ref_jenis_satker (nama)
VALUES ($1)
RETURNING id, nama
`

type CreateRefJenisSatkerRow struct {
	ID   int32       `db:"id"`
	Nama pgtype.Text `db:"nama"`
}

func (q *Queries) CreateRefJenisSatker(ctx context.Context, nama pgtype.Text) (CreateRefJenisSatkerRow, error) {
	row := q.db.QueryRow(ctx, createRefJenisSatker, nama)
	var i CreateRefJenisSatkerRow
	err := row.Scan(&i.ID, &i.Nama)
	return i, err
}

const deleteRefJenisSatker = `-- name: DeleteRefJenisSatker :execrows
UPDATE ref_jenis_satker
SET deleted_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) DeleteRefJenisSatker(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRefJenisSatker, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRefJenisSatker = `-- name: GetRefJenisSatker :one
SELECT id, nama
FROM ref_jenis_satker
WHERE id = $1
  AND deleted_at IS NULL
`

type GetRefJenisSatkerRow struct {
	ID   int32       `db:"id"`
	Nama pgtype.Text `db:"nama"`
}

func (q *Queries) GetRefJenisSatker(ctx context.Context, id int32) (GetRefJenisSatkerRow, error) {
	row := q.db.QueryRow(ctx, getRefJenisSatker, id)
	var i GetRefJenisSatkerRow
	err := row.Scan(&i.ID, &i.Nama)
	return i, err
}

const listRefJenisSatker = `-- name: ListRefJenisSatker :many
SELECT id, nama
FROM ref_jenis_satker
WHERE deleted_at IS NULL
  AND ($3::varchar IS NULL OR nama ILIKE '%' || $3 || '%')
LIMIT $1 OFFSET $2
`

type ListRefJenisSatkerParams struct {
	Limit  int32       `db:"limit"`
	Offset int32       `db:"offset"`
	Nama   pgtype.Text `db:"nama"`
}

type ListRefJenisSatkerRow struct {
	ID   int32       `db:"id"`
	Nama pgtype.Text `db:"nama"`
}

func (q *Queries) ListRefJenisSatker(ctx context.Context, arg ListRefJenisSatkerParams) ([]ListRefJenisSatkerRow, error) {
	rows, err := q.db.Query(ctx, listRefJenisSatker, arg.Limit, arg.Offset, arg.Nama)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRefJenisSatkerRow
	for rows.Next() {
		var i ListRefJenisSatkerRow
		if err := rows.Scan(&i.ID, &i.Nama); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRefJenisSatker = `-- name: UpdateRefJenisSatker :one
UPDATE ref_jenis_satker
SET nama = $2
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, nama
`

type UpdateRefJenisSatkerParams struct {
	ID   int32       `db:"id"`
	Nama pgtype.Text `db:"nama"`
}

type UpdateRefJenisSatkerRow struct {
	ID   int32       `db:"id"`
	Nama pgtype.Text `db:"nama"`
}

func (q *Queries) UpdateRefJenisSatker(ctx context.Context, arg UpdateRefJenisSatkerParams) (UpdateRefJenisSatkerRow, error) {
	row := q.db.QueryRow(ctx, updateRefJenisSatker, arg.ID, arg.Nama)
	var i UpdateRefJenisSatkerRow
	err := row.Scan(&i.ID, &i.Nama)
	return i, err
}
