// Code generated by sqlc. DO NOT EDIT.
// source: ref_golongan.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRefGolongan = `-- name: CountRefGolongan :one
SELECT COUNT(1) FROM ref_golongan
WHERE deleted_at IS NULL
`

func (q *Queries) CountRefGolongan(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRefGolongan)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRefGolongan = `-- name: GetRefGolongan :many
SELECT id, nama, nama_pangkat FROM ref_golongan
WHERE deleted_at IS NULL
LIMIT $1 OFFSET $2
`

type GetRefGolonganParams struct {
	Limit  int32 `db:"limit"`
	Offset int32 `db:"offset"`
}

type GetRefGolonganRow struct {
	ID          int32       `db:"id"`
	Nama        pgtype.Text `db:"nama"`
	NamaPangkat pgtype.Text `db:"nama_pangkat"`
}

func (q *Queries) GetRefGolongan(ctx context.Context, arg GetRefGolonganParams) ([]GetRefGolonganRow, error) {
	rows, err := q.db.Query(ctx, getRefGolongan, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRefGolonganRow
	for rows.Next() {
		var i GetRefGolonganRow
		if err := rows.Scan(&i.ID, &i.Nama, &i.NamaPangkat); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
