// Code generated by sqlc. DO NOT EDIT.
// source: ref_lokasi.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRefLokasi = `-- name: CountRefLokasi :one
SELECT COUNT(1)
FROM ref_lokasi p
WHERE 
    p.deleted_at IS NULL
    AND ($1::varchar = '' OR p.nama ILIKE '%' || $1::varchar || '%')
`

func (q *Queries) CountRefLokasi(ctx context.Context, nama string) (int64, error) {
	row := q.db.QueryRow(ctx, countRefLokasi, nama)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listRefLokasi = `-- name: ListRefLokasi :many
SELECT 
    p.id, p.nama
FROM 
    ref_lokasi p
WHERE 
    p.deleted_at IS NULL
    AND ($3::varchar = '' OR p.nama ILIKE '%' || $3::varchar || '%')
LIMIT $1 OFFSET $2
`

type ListRefLokasiParams struct {
	Limit  int32  `db:"limit"`
	Offset int32  `db:"offset"`
	Nama   string `db:"nama"`
}

type ListRefLokasiRow struct {
	ID   string      `db:"id"`
	Nama pgtype.Text `db:"nama"`
}

func (q *Queries) ListRefLokasi(ctx context.Context, arg ListRefLokasiParams) ([]ListRefLokasiRow, error) {
	rows, err := q.db.Query(ctx, listRefLokasi, arg.Limit, arg.Offset, arg.Nama)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRefLokasiRow
	for rows.Next() {
		var i ListRefLokasiRow
		if err := rows.Scan(&i.ID, &i.Nama); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
