// Code generated by sqlc. DO NOT EDIT.
// source: ref_jenis_jabatan.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countJenisJabatan = `-- name: CountJenisJabatan :one
SELECT COUNT(1) FROM ref_jenis_jabatan
WHERE deleted_at IS NULL
`

func (q *Queries) CountJenisJabatan(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countJenisJabatan)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRefJenisJabatan = `-- name: GetRefJenisJabatan :many
SELECT id, nama FROM ref_jenis_jabatan
WHERE deleted_at IS NULL
LIMIT $1 OFFSET $2
`

type GetRefJenisJabatanParams struct {
	Limit  int32 `db:"limit"`
	Offset int32 `db:"offset"`
}

type GetRefJenisJabatanRow struct {
	ID   int32       `db:"id"`
	Nama pgtype.Text `db:"nama"`
}

func (q *Queries) GetRefJenisJabatan(ctx context.Context, arg GetRefJenisJabatanParams) ([]GetRefJenisJabatanRow, error) {
	rows, err := q.db.Query(ctx, getRefJenisJabatan, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRefJenisJabatanRow
	for rows.Next() {
		var i GetRefJenisJabatanRow
		if err := rows.Scan(&i.ID, &i.Nama); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
