// Code generated by sqlc. DO NOT EDIT.
// source: ref_jenis_kawin.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRefJenisKawin = `-- name: CountRefJenisKawin :one
select count(1) from ref_jenis_kawin
where deleted_at is null
`

func (q *Queries) CountRefJenisKawin(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRefJenisKawin)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listRefJenisKawin = `-- name: ListRefJenisKawin :many
select id, nama from ref_jenis_kawin
where deleted_at is null
limit $1 offset $2
`

type ListRefJenisKawinParams struct {
	Limit  int32 `db:"limit"`
	Offset int32 `db:"offset"`
}

type ListRefJenisKawinRow struct {
	ID   int32       `db:"id"`
	Nama pgtype.Text `db:"nama"`
}

func (q *Queries) ListRefJenisKawin(ctx context.Context, arg ListRefJenisKawinParams) ([]ListRefJenisKawinRow, error) {
	rows, err := q.db.Query(ctx, listRefJenisKawin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRefJenisKawinRow
	for rows.Next() {
		var i ListRefJenisKawinRow
		if err := rows.Scan(&i.ID, &i.Nama); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
