// Code generated by sqlc. DO NOT EDIT.
// source: ref_jenis_diklat_fungsional.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRefJenisDiklatFungsional = `-- name: CountRefJenisDiklatFungsional :one
SELECT COUNT(1) 
FROM ref_jenis_diklat_fungsional
WHERE deleted_at IS NULL
`

func (q *Queries) CountRefJenisDiklatFungsional(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRefJenisDiklatFungsional)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listRefJenisDiklatFungsional = `-- name: ListRefJenisDiklatFungsional :many
SELECT 
  id, 
  nama 
FROM ref_jenis_diklat_fungsional
WHERE deleted_at IS NULL
LIMIT $1 OFFSET $2
`

type ListRefJenisDiklatFungsionalParams struct {
	Limit  int32 `db:"limit"`
	Offset int32 `db:"offset"`
}

type ListRefJenisDiklatFungsionalRow struct {
	ID   int32       `db:"id"`
	Nama pgtype.Text `db:"nama"`
}

func (q *Queries) ListRefJenisDiklatFungsional(ctx context.Context, arg ListRefJenisDiklatFungsionalParams) ([]ListRefJenisDiklatFungsionalRow, error) {
	rows, err := q.db.Query(ctx, listRefJenisDiklatFungsional, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRefJenisDiklatFungsionalRow
	for rows.Next() {
		var i ListRefJenisDiklatFungsionalRow
		if err := rows.Scan(&i.ID, &i.Nama); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
