// Code generated by sqlc. DO NOT EDIT.
// source: ref_jabatan.sql

package repository

import (
	"context"
	"database/sql"
)

const getRefJabatan = `-- name: GetRefJabatan :many
select id, kode_jabatan, nama_jabatan from ref_jabatan
LIMIT $1 OFFSET $2
`

type GetRefJabatanParams struct {
	Limit  int32 `db:"limit"`
	Offset int32 `db:"offset"`
}

type GetRefJabatanRow struct {
	ID          int32          `db:"id"`
	KodeJabatan string         `db:"kode_jabatan"`
	NamaJabatan sql.NullString `db:"nama_jabatan"`
}

func (q *Queries) GetRefJabatan(ctx context.Context, arg GetRefJabatanParams) ([]GetRefJabatanRow, error) {
	rows, err := q.db.Query(ctx, getRefJabatan, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRefJabatanRow
	for rows.Next() {
		var i GetRefJabatanRow
		if err := rows.Scan(&i.ID, &i.KodeJabatan, &i.NamaJabatan); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
