// Code generated by sqlc. DO NOT EDIT.
// source: ref_jabatan.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRefJabatan = `-- name: CountRefJabatan :one
SELECT COUNT(1) FROM ref_jabatan
WHERE ($1::varchar IS NULL OR nama_jabatan ILIKE $1::varchar || '%')
  AND deleted_at IS NULL
`

func (q *Queries) CountRefJabatan(ctx context.Context, nama pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countRefJabatan, nama)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listRefJabatan = `-- name: ListRefJabatan :many
select kode_jabatan, nama_jabatan from ref_jabatan
WHERE ($3::varchar IS NULL OR nama_jabatan ILIKE $3::varchar || '%')
  AND deleted_at IS NULL
LIMIT $1 OFFSET $2
`

type ListRefJabatanParams struct {
	Limit  int32       `db:"limit"`
	Offset int32       `db:"offset"`
	Nama   pgtype.Text `db:"nama"`
}

type ListRefJabatanRow struct {
	KodeJabatan string      `db:"kode_jabatan"`
	NamaJabatan pgtype.Text `db:"nama_jabatan"`
}

func (q *Queries) ListRefJabatan(ctx context.Context, arg ListRefJabatanParams) ([]ListRefJabatanRow, error) {
	rows, err := q.db.Query(ctx, listRefJabatan, arg.Limit, arg.Offset, arg.Nama)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRefJabatanRow
	for rows.Next() {
		var i ListRefJabatanRow
		if err := rows.Scan(&i.KodeJabatan, &i.NamaJabatan); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
