// Code generated by sqlc. DO NOT EDIT.
// source: riwayat_pindah_unit_kerja.sql

package repository

import (
	"context"
)

const updateRiwayatPindahUnitKerjaNamaNipByNIP = `-- name: UpdateRiwayatPindahUnitKerjaNamaNipByNIP :exec
UPDATE riwayat_pindah_unit_kerja
SET     
    pns_nip = $1::varchar,
    pns_nama = $2::varchar,
    updated_at = now()
WHERE pns_nip = $3::varchar AND deleted_at IS NULL
AND (
    ($1::varchar IS NOT NULL AND $1::varchar IS DISTINCT FROM pns_nip)
    OR ($2::varchar IS NOT NULL AND $2::varchar IS DISTINCT FROM pns_nama)
)
`

type UpdateRiwayatPindahUnitKerjaNamaNipByNIPParams struct {
	NipBaru string `db:"nip_baru"`
	Nama    string `db:"nama"`
	Nip     string `db:"nip"`
}

func (q *Queries) UpdateRiwayatPindahUnitKerjaNamaNipByNIP(ctx context.Context, arg UpdateRiwayatPindahUnitKerjaNamaNipByNIPParams) error {
	_, err := q.db.Exec(ctx, updateRiwayatPindahUnitKerjaNamaNipByNIP, arg.NipBaru, arg.Nama, arg.Nip)
	return err
}
