// Code generated by sqlc. DO NOT EDIT.
// source: riwayat_uji_kompetensi.sql

package repository

import (
	"context"
)

const updateRiwayatUjiKompetensiNamaNipByNIP = `-- name: UpdateRiwayatUjiKompetensiNamaNipByNIP :exec
UPDATE riwayat_uji_kompetensi
SET
    nip_baru = $1::varchar,
    updated_at = now()
WHERE nip_baru = $2::varchar AND deleted_at IS NULL
AND (
    ($1::varchar IS NOT NULL AND $1::varchar IS DISTINCT FROM nip_baru)
)
`

type UpdateRiwayatUjiKompetensiNamaNipByNIPParams struct {
	NipBaru string `db:"nip_baru"`
	Nip     string `db:"nip"`
}

func (q *Queries) UpdateRiwayatUjiKompetensiNamaNipByNIP(ctx context.Context, arg UpdateRiwayatUjiKompetensiNamaNipByNIPParams) error {
	_, err := q.db.Exec(ctx, updateRiwayatUjiKompetensiNamaNipByNIP, arg.NipBaru, arg.Nip)
	return err
}
