// Code generated by sqlc. DO NOT EDIT.
// source: riwayat_kenaikan_gaji_berkala.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRiwayatKenaikanGajiBerkala = `-- name: CountRiwayatKenaikanGajiBerkala :one
SELECT
    COUNT(1)
FROM
    riwayat_kenaikan_gaji_berkala rk
    JOIN pegawai p ON rk.pegawai_id = p.id
WHERE
    p.nip_baru = $1
    AND p.deleted_at IS NULL
    AND rk.deleted_at IS NULL
`

func (q *Queries) CountRiwayatKenaikanGajiBerkala(ctx context.Context, nipBaru pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countRiwayatKenaikanGajiBerkala, nipBaru)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBerkasRiwayatKenaikanGajiBerkala = `-- name: GetBerkasRiwayatKenaikanGajiBerkala :one
SELECT
    file_base64
FROM
    riwayat_kenaikan_gaji_berkala rk
    JOIN pegawai p ON rk.pegawai_id = p.id
WHERE
    p.nip_baru = $1
    AND rk.id = $2
    AND rk.deleted_at IS NULL
`

type GetBerkasRiwayatKenaikanGajiBerkalaParams struct {
	NipBaru pgtype.Text `db:"nip_baru"`
	ID      int64       `db:"id"`
}

func (q *Queries) GetBerkasRiwayatKenaikanGajiBerkala(ctx context.Context, arg GetBerkasRiwayatKenaikanGajiBerkalaParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getBerkasRiwayatKenaikanGajiBerkala, arg.NipBaru, arg.ID)
	var file_base64 pgtype.Text
	err := row.Scan(&file_base64)
	return file_base64, err
}

const listRiwayatKenaikanGajiBerkala = `-- name: ListRiwayatKenaikanGajiBerkala :many
SELECT
    rk.id,
    rg.id AS golongan_id,
    rg.nama AS golongan_nama,
    rg.nama_pangkat AS golongan_nama_pangkat,
    rk.no_sk,
    rk.tanggal_sk,
    rk.tmt_golongan,
    rk.masa_kerja_golongan_tahun,
    rk.masa_kerja_golongan_bulan,
    rk.tmt_sk AS tmt_kenaikan_gaji_berkala,
    rk.gaji_pokok,
    rk.jabatan,
    rk.tmt_jabatan,
    rk.last_education AS pendidikan,
    rk.last_education_date AS tanggal_lulus,
    rk.kantor_pembayaran,
    rk.unit_kerja_induk_id,
    uk.nama_unor AS unit_kerja_induk,
    rk.pejabat
FROM
    riwayat_kenaikan_gaji_berkala rk
    JOIN pegawai p ON rk.pegawai_id = p.id
    LEFT JOIN ref_golongan rg ON rk.golongan_id = rg.id AND rg.deleted_at IS NULL
    LEFT JOIN unit_kerja uk ON rk.unit_kerja_induk_id = uk.id AND uk.deleted_at IS NULL
WHERE
    p.nip_baru = $1
    AND p.deleted_at IS NULL
    AND rk.deleted_at IS NULL
ORDER BY
    rk.tmt_sk DESC
LIMIT
    $2
OFFSET
    $3
`

type ListRiwayatKenaikanGajiBerkalaParams struct {
	NipBaru pgtype.Text `db:"nip_baru"`
	Limit   int32       `db:"limit"`
	Offset  int32       `db:"offset"`
}

type ListRiwayatKenaikanGajiBerkalaRow struct {
	ID                     int64       `db:"id"`
	GolonganID             pgtype.Int4 `db:"golongan_id"`
	GolonganNama           pgtype.Text `db:"golongan_nama"`
	GolonganNamaPangkat    pgtype.Text `db:"golongan_nama_pangkat"`
	NoSk                   pgtype.Text `db:"no_sk"`
	TanggalSk              pgtype.Date `db:"tanggal_sk"`
	TmtGolongan            pgtype.Date `db:"tmt_golongan"`
	MasaKerjaGolonganTahun pgtype.Int2 `db:"masa_kerja_golongan_tahun"`
	MasaKerjaGolonganBulan pgtype.Int2 `db:"masa_kerja_golongan_bulan"`
	TmtKenaikanGajiBerkala pgtype.Date `db:"tmt_kenaikan_gaji_berkala"`
	GajiPokok              pgtype.Int4 `db:"gaji_pokok"`
	Jabatan                pgtype.Text `db:"jabatan"`
	TmtJabatan             pgtype.Date `db:"tmt_jabatan"`
	Pendidikan             pgtype.Text `db:"pendidikan"`
	TanggalLulus           pgtype.Date `db:"tanggal_lulus"`
	KantorPembayaran       pgtype.Text `db:"kantor_pembayaran"`
	UnitKerjaIndukID       pgtype.Text `db:"unit_kerja_induk_id"`
	UnitKerjaInduk         pgtype.Text `db:"unit_kerja_induk"`
	Pejabat                pgtype.Text `db:"pejabat"`
}

func (q *Queries) ListRiwayatKenaikanGajiBerkala(ctx context.Context, arg ListRiwayatKenaikanGajiBerkalaParams) ([]ListRiwayatKenaikanGajiBerkalaRow, error) {
	rows, err := q.db.Query(ctx, listRiwayatKenaikanGajiBerkala, arg.NipBaru, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRiwayatKenaikanGajiBerkalaRow
	for rows.Next() {
		var i ListRiwayatKenaikanGajiBerkalaRow
		if err := rows.Scan(
			&i.ID,
			&i.GolonganID,
			&i.GolonganNama,
			&i.GolonganNamaPangkat,
			&i.NoSk,
			&i.TanggalSk,
			&i.TmtGolongan,
			&i.MasaKerjaGolonganTahun,
			&i.MasaKerjaGolonganBulan,
			&i.TmtKenaikanGajiBerkala,
			&i.GajiPokok,
			&i.Jabatan,
			&i.TmtJabatan,
			&i.Pendidikan,
			&i.TanggalLulus,
			&i.KantorPembayaran,
			&i.UnitKerjaIndukID,
			&i.UnitKerjaInduk,
			&i.Pejabat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
