// Code generated by sqlc. DO NOT EDIT.
// source: riwayat_sertifikasi.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRiwayatSertifikasi = `-- name: CountRiwayatSertifikasi :one
select count(1) from riwayat_sertifikasi
where nip = $1 and deleted_at is null
`

func (q *Queries) CountRiwayatSertifikasi(ctx context.Context, nip pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countRiwayatSertifikasi, nip)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBerkasRiwayatSertifikasi = `-- name: GetBerkasRiwayatSertifikasi :one
select file_base64 from riwayat_sertifikasi
where nip = $1 and id = $2 and deleted_at is null
`

type GetBerkasRiwayatSertifikasiParams struct {
	Nip pgtype.Text `db:"nip"`
	ID  int64       `db:"id"`
}

func (q *Queries) GetBerkasRiwayatSertifikasi(ctx context.Context, arg GetBerkasRiwayatSertifikasiParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getBerkasRiwayatSertifikasi, arg.Nip, arg.ID)
	var file_base64 pgtype.Text
	err := row.Scan(&file_base64)
	return file_base64, err
}

const listRiwayatSertifikasi = `-- name: ListRiwayatSertifikasi :many
select id, nama_sertifikasi, tahun, deskripsi from riwayat_sertifikasi
where nip = $1 and deleted_at is null
order by tahun desc
limit $2 offset $3
`

type ListRiwayatSertifikasiParams struct {
	Nip    pgtype.Text `db:"nip"`
	Limit  int32       `db:"limit"`
	Offset int32       `db:"offset"`
}

type ListRiwayatSertifikasiRow struct {
	ID              int64       `db:"id"`
	NamaSertifikasi pgtype.Text `db:"nama_sertifikasi"`
	Tahun           pgtype.Int8 `db:"tahun"`
	Deskripsi       pgtype.Text `db:"deskripsi"`
}

func (q *Queries) ListRiwayatSertifikasi(ctx context.Context, arg ListRiwayatSertifikasiParams) ([]ListRiwayatSertifikasiRow, error) {
	rows, err := q.db.Query(ctx, listRiwayatSertifikasi, arg.Nip, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRiwayatSertifikasiRow
	for rows.Next() {
		var i ListRiwayatSertifikasiRow
		if err := rows.Scan(
			&i.ID,
			&i.NamaSertifikasi,
			&i.Tahun,
			&i.Deskripsi,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
