// Code generated by sqlc. DO NOT EDIT.
// source: riwayat_sertifikasi.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRiwayatSertifikasi = `-- name: CountRiwayatSertifikasi :one
select count(1) from riwayat_sertifikasi
where nip = $1 and deleted_at is null
`

func (q *Queries) CountRiwayatSertifikasi(ctx context.Context, nip pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countRiwayatSertifikasi, nip)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRiwayatSertifikasi = `-- name: CreateRiwayatSertifikasi :one
insert into 
    riwayat_sertifikasi (nip, tahun, nama_sertifikasi, deskripsi) 
values 
    ($1, $2, $3, $4)
returning id
`

type CreateRiwayatSertifikasiParams struct {
	Nip             pgtype.Text `db:"nip"`
	Tahun           pgtype.Int8 `db:"tahun"`
	NamaSertifikasi pgtype.Text `db:"nama_sertifikasi"`
	Deskripsi       pgtype.Text `db:"deskripsi"`
}

func (q *Queries) CreateRiwayatSertifikasi(ctx context.Context, arg CreateRiwayatSertifikasiParams) (int64, error) {
	row := q.db.QueryRow(ctx, createRiwayatSertifikasi,
		arg.Nip,
		arg.Tahun,
		arg.NamaSertifikasi,
		arg.Deskripsi,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteRiwayatSertifikasiByIDAndNIP = `-- name: DeleteRiwayatSertifikasiByIDAndNIP :execrows
update riwayat_sertifikasi
set
    deleted_at = now()
where id = $1 and nip = $2::varchar and deleted_at is null
`

type DeleteRiwayatSertifikasiByIDAndNIPParams struct {
	ID  int64  `db:"id"`
	Nip string `db:"nip"`
}

func (q *Queries) DeleteRiwayatSertifikasiByIDAndNIP(ctx context.Context, arg DeleteRiwayatSertifikasiByIDAndNIPParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRiwayatSertifikasiByIDAndNIP, arg.ID, arg.Nip)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBerkasRiwayatSertifikasi = `-- name: GetBerkasRiwayatSertifikasi :one
select file_base64 from riwayat_sertifikasi
where nip = $1 and id = $2 and deleted_at is null
`

type GetBerkasRiwayatSertifikasiParams struct {
	Nip pgtype.Text `db:"nip"`
	ID  int64       `db:"id"`
}

func (q *Queries) GetBerkasRiwayatSertifikasi(ctx context.Context, arg GetBerkasRiwayatSertifikasiParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getBerkasRiwayatSertifikasi, arg.Nip, arg.ID)
	var file_base64 pgtype.Text
	err := row.Scan(&file_base64)
	return file_base64, err
}

const listRiwayatSertifikasi = `-- name: ListRiwayatSertifikasi :many
select id, nama_sertifikasi, tahun, deskripsi from riwayat_sertifikasi
where nip = $1 and deleted_at is null
order by tahun desc nulls last
limit $2 offset $3
`

type ListRiwayatSertifikasiParams struct {
	Nip    pgtype.Text `db:"nip"`
	Limit  int32       `db:"limit"`
	Offset int32       `db:"offset"`
}

type ListRiwayatSertifikasiRow struct {
	ID              int64       `db:"id"`
	NamaSertifikasi pgtype.Text `db:"nama_sertifikasi"`
	Tahun           pgtype.Int8 `db:"tahun"`
	Deskripsi       pgtype.Text `db:"deskripsi"`
}

func (q *Queries) ListRiwayatSertifikasi(ctx context.Context, arg ListRiwayatSertifikasiParams) ([]ListRiwayatSertifikasiRow, error) {
	rows, err := q.db.Query(ctx, listRiwayatSertifikasi, arg.Nip, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRiwayatSertifikasiRow
	for rows.Next() {
		var i ListRiwayatSertifikasiRow
		if err := rows.Scan(
			&i.ID,
			&i.NamaSertifikasi,
			&i.Tahun,
			&i.Deskripsi,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBerkasRiwayatSertifikasiByIDAndNIP = `-- name: UpdateBerkasRiwayatSertifikasiByIDAndNIP :execrows
update riwayat_sertifikasi
set
    file_base64 = $1,
    updated_at = now()
where id = $2 and nip = $3::varchar and deleted_at is null
`

type UpdateBerkasRiwayatSertifikasiByIDAndNIPParams struct {
	FileBase64 pgtype.Text `db:"file_base64"`
	ID         int64       `db:"id"`
	Nip        string      `db:"nip"`
}

func (q *Queries) UpdateBerkasRiwayatSertifikasiByIDAndNIP(ctx context.Context, arg UpdateBerkasRiwayatSertifikasiByIDAndNIPParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBerkasRiwayatSertifikasiByIDAndNIP, arg.FileBase64, arg.ID, arg.Nip)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRiwayatSertifikasiByIDAndNIP = `-- name: UpdateRiwayatSertifikasiByIDAndNIP :execrows
update riwayat_sertifikasi
set
    tahun = $1,
    nama_sertifikasi = $2,
    deskripsi = $3,
    updated_at = now()
where id = $4 and nip = $5::varchar and deleted_at is null
`

type UpdateRiwayatSertifikasiByIDAndNIPParams struct {
	Tahun           pgtype.Int8 `db:"tahun"`
	NamaSertifikasi pgtype.Text `db:"nama_sertifikasi"`
	Deskripsi       pgtype.Text `db:"deskripsi"`
	ID              int64       `db:"id"`
	Nip             string      `db:"nip"`
}

func (q *Queries) UpdateRiwayatSertifikasiByIDAndNIP(ctx context.Context, arg UpdateRiwayatSertifikasiByIDAndNIPParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRiwayatSertifikasiByIDAndNIP,
		arg.Tahun,
		arg.NamaSertifikasi,
		arg.Deskripsi,
		arg.ID,
		arg.Nip,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRiwayatSertifikasiNamaNipByNIP = `-- name: UpdateRiwayatSertifikasiNamaNipByNIP :exec
UPDATE riwayat_sertifikasi
SET     
    nip = $1::varchar,
    updated_at = now()
WHERE nip = $2::varchar AND deleted_at IS NULL
AND (
    ($1::varchar IS NOT NULL AND $1::varchar IS DISTINCT FROM nip)
)
`

type UpdateRiwayatSertifikasiNamaNipByNIPParams struct {
	NipBaru string `db:"nip_baru"`
	Nip     string `db:"nip"`
}

func (q *Queries) UpdateRiwayatSertifikasiNamaNipByNIP(ctx context.Context, arg UpdateRiwayatSertifikasiNamaNipByNIPParams) error {
	_, err := q.db.Exec(ctx, updateRiwayatSertifikasiNamaNipByNIP, arg.NipBaru, arg.Nip)
	return err
}
