// Code generated by sqlc. DO NOT EDIT.
// source: riwayat_penugasan.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRiwayatPenugasan = `-- name: CountRiwayatPenugasan :one
select count(1) from riwayat_penugasan
where nip = $1 and deleted_at is null
`

func (q *Queries) CountRiwayatPenugasan(ctx context.Context, nip pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countRiwayatPenugasan, nip)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBerkasRiwayatPenugasan = `-- name: GetBerkasRiwayatPenugasan :one
select file_base64 from riwayat_penugasan
where nip = $1 and id = $2 and deleted_at is null
`

type GetBerkasRiwayatPenugasanParams struct {
	Nip pgtype.Text `db:"nip"`
	ID  int32       `db:"id"`
}

func (q *Queries) GetBerkasRiwayatPenugasan(ctx context.Context, arg GetBerkasRiwayatPenugasanParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getBerkasRiwayatPenugasan, arg.Nip, arg.ID)
	var file_base64 pgtype.Text
	err := row.Scan(&file_base64)
	return file_base64, err
}

const listRiwayatPenugasan = `-- name: ListRiwayatPenugasan :many
select
  id,
  tipe_jabatan,
  nama_jabatan,
  deskripsi_jabatan,
  tanggal_mulai,
  tanggal_selesai,
  is_menjabat
from riwayat_penugasan
where nip = $1 and deleted_at is null
order by tanggal_mulai desc
limit $2 offset $3
`

type ListRiwayatPenugasanParams struct {
	Nip    pgtype.Text `db:"nip"`
	Limit  int32       `db:"limit"`
	Offset int32       `db:"offset"`
}

type ListRiwayatPenugasanRow struct {
	ID               int32       `db:"id"`
	TipeJabatan      pgtype.Text `db:"tipe_jabatan"`
	NamaJabatan      pgtype.Text `db:"nama_jabatan"`
	DeskripsiJabatan pgtype.Text `db:"deskripsi_jabatan"`
	TanggalMulai     pgtype.Date `db:"tanggal_mulai"`
	TanggalSelesai   pgtype.Date `db:"tanggal_selesai"`
	IsMenjabat       pgtype.Bool `db:"is_menjabat"`
}

func (q *Queries) ListRiwayatPenugasan(ctx context.Context, arg ListRiwayatPenugasanParams) ([]ListRiwayatPenugasanRow, error) {
	rows, err := q.db.Query(ctx, listRiwayatPenugasan, arg.Nip, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRiwayatPenugasanRow
	for rows.Next() {
		var i ListRiwayatPenugasanRow
		if err := rows.Scan(
			&i.ID,
			&i.TipeJabatan,
			&i.NamaJabatan,
			&i.DeskripsiJabatan,
			&i.TanggalMulai,
			&i.TanggalSelesai,
			&i.IsMenjabat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
