// Code generated by sqlc. DO NOT EDIT.
// source: riwayat_pelatihan_teknis.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRiwayatPelatihanTeknis = `-- name: CountRiwayatPelatihanTeknis :one
SELECT COUNT(1)
FROM riwayat_kursus rk
WHERE rk.pns_nip = $1 AND rk.deleted_at IS NULL
`

func (q *Queries) CountRiwayatPelatihanTeknis(ctx context.Context, pnsNip pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countRiwayatPelatihanTeknis, pnsNip)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBerkasRiwayatPelatihanTeknis = `-- name: GetBerkasRiwayatPelatihanTeknis :one
select file_base64 from riwayat_kursus
where pns_nip = $1 and id = $2 and deleted_at is null
`

type GetBerkasRiwayatPelatihanTeknisParams struct {
	PnsNip pgtype.Text `db:"pns_nip"`
	ID     int32       `db:"id"`
}

func (q *Queries) GetBerkasRiwayatPelatihanTeknis(ctx context.Context, arg GetBerkasRiwayatPelatihanTeknisParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getBerkasRiwayatPelatihanTeknis, arg.PnsNip, arg.ID)
	var file_base64 pgtype.Text
	err := row.Scan(&file_base64)
	return file_base64, err
}

const listRiwayatPelatihanTeknis = `-- name: ListRiwayatPelatihanTeknis :many
SELECT
    rk.id,
    rk.tipe_kursus,
    rk.jenis_kursus,
    rk.nama_kursus,
    rk.tanggal_kursus,
    rk.lama_kursus as durasi,
    rk.institusi_penyelenggara,
    rk.no_sertifikat
FROM riwayat_kursus rk
WHERE rk.pns_nip = $1 AND rk.deleted_at IS NULL
ORDER BY rk.tanggal_kursus DESC NULLS LAST
LIMIT $2 OFFSET $3
`

type ListRiwayatPelatihanTeknisParams struct {
	PnsNip pgtype.Text `db:"pns_nip"`
	Limit  int32       `db:"limit"`
	Offset int32       `db:"offset"`
}

type ListRiwayatPelatihanTeknisRow struct {
	ID                     int32         `db:"id"`
	TipeKursus             pgtype.Text   `db:"tipe_kursus"`
	JenisKursus            pgtype.Text   `db:"jenis_kursus"`
	NamaKursus             pgtype.Text   `db:"nama_kursus"`
	TanggalKursus          pgtype.Date   `db:"tanggal_kursus"`
	Durasi                 pgtype.Float8 `db:"durasi"`
	InstitusiPenyelenggara pgtype.Text   `db:"institusi_penyelenggara"`
	NoSertifikat           pgtype.Text   `db:"no_sertifikat"`
}

func (q *Queries) ListRiwayatPelatihanTeknis(ctx context.Context, arg ListRiwayatPelatihanTeknisParams) ([]ListRiwayatPelatihanTeknisRow, error) {
	rows, err := q.db.Query(ctx, listRiwayatPelatihanTeknis, arg.PnsNip, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRiwayatPelatihanTeknisRow
	for rows.Next() {
		var i ListRiwayatPelatihanTeknisRow
		if err := rows.Scan(
			&i.ID,
			&i.TipeKursus,
			&i.JenisKursus,
			&i.NamaKursus,
			&i.TanggalKursus,
			&i.Durasi,
			&i.InstitusiPenyelenggara,
			&i.NoSertifikat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
