// Code generated by sqlc. DO NOT EDIT.
// source: riwayat_penghargaan.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRiwayatPenghargaan = `-- name: CountRiwayatPenghargaan :one
SELECT COUNT(1)
FROM riwayat_penghargaan_umum
WHERE nip = $1::varchar and riwayat_penghargaan_umum.deleted_at is null
`

func (q *Queries) CountRiwayatPenghargaan(ctx context.Context, nip string) (int64, error) {
	row := q.db.QueryRow(ctx, countRiwayatPenghargaan, nip)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listRiwayatPenghargaan = `-- name: ListRiwayatPenghargaan :many
SELECT
    riwayat_penghargaan_umum.id,
    ref_jenis_penghargaan.nama as jenis_penghargaan,
    nama_penghargaan,
    deskripsi_penghargaan,
    tanggal_penghargaan
FROM riwayat_penghargaan_umum
LEFT JOIN ref_jenis_penghargaan on riwayat_penghargaan_umum.jenis_penghargaan_id = ref_jenis_penghargaan.id and ref_jenis_penghargaan.deleted_at is null
WHERE nip = $3::varchar and riwayat_penghargaan_umum.deleted_at is null
ORDER BY tanggal_penghargaan DESC
LIMIT $1 OFFSET $2
`

type ListRiwayatPenghargaanParams struct {
	Limit  int32  `db:"limit"`
	Offset int32  `db:"offset"`
	Nip    string `db:"nip"`
}

type ListRiwayatPenghargaanRow struct {
	ID                   int32       `db:"id"`
	JenisPenghargaan     pgtype.Text `db:"jenis_penghargaan"`
	NamaPenghargaan      pgtype.Text `db:"nama_penghargaan"`
	DeskripsiPenghargaan pgtype.Text `db:"deskripsi_penghargaan"`
	TanggalPenghargaan   pgtype.Date `db:"tanggal_penghargaan"`
}

func (q *Queries) ListRiwayatPenghargaan(ctx context.Context, arg ListRiwayatPenghargaanParams) ([]ListRiwayatPenghargaanRow, error) {
	rows, err := q.db.Query(ctx, listRiwayatPenghargaan, arg.Limit, arg.Offset, arg.Nip)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRiwayatPenghargaanRow
	for rows.Next() {
		var i ListRiwayatPenghargaanRow
		if err := rows.Scan(
			&i.ID,
			&i.JenisPenghargaan,
			&i.NamaPenghargaan,
			&i.DeskripsiPenghargaan,
			&i.TanggalPenghargaan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
