// Code generated by sqlc. DO NOT EDIT.
// source: riwayat_pelatihan_struktural.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRiwayatPelatihanStruktural = `-- name: CountRiwayatPelatihanStruktural :one
SELECT COUNT(1) AS total
FROM riwayat_diklat_struktural rs
WHERE rs.pns_nip = $1
  AND rs.deleted_at IS NULL
`

func (q *Queries) CountRiwayatPelatihanStruktural(ctx context.Context, pnsNip pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countRiwayatPelatihanStruktural, pnsNip)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createRiwayatPelatihanStruktural = `-- name: CreateRiwayatPelatihanStruktural :one
insert into riwayat_diklat_struktural
    (id, nama_diklat, tanggal, tahun, lama, nomor, pns_id, pns_nip, pns_nama) values
    (public.uuid_generate_v4(), $1, $2, $3, $4, $5, $6, $7, $8)
returning id
`

type CreateRiwayatPelatihanStrukturalParams struct {
	NamaDiklat pgtype.Text   `db:"nama_diklat"`
	Tanggal    pgtype.Date   `db:"tanggal"`
	Tahun      pgtype.Int2   `db:"tahun"`
	Lama       pgtype.Float4 `db:"lama"`
	Nomor      pgtype.Text   `db:"nomor"`
	PnsID      pgtype.Text   `db:"pns_id"`
	PnsNip     pgtype.Text   `db:"pns_nip"`
	PnsNama    pgtype.Text   `db:"pns_nama"`
}

func (q *Queries) CreateRiwayatPelatihanStruktural(ctx context.Context, arg CreateRiwayatPelatihanStrukturalParams) (string, error) {
	row := q.db.QueryRow(ctx, createRiwayatPelatihanStruktural,
		arg.NamaDiklat,
		arg.Tanggal,
		arg.Tahun,
		arg.Lama,
		arg.Nomor,
		arg.PnsID,
		arg.PnsNip,
		arg.PnsNama,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteRiwayatPelatihanStruktural = `-- name: DeleteRiwayatPelatihanStruktural :execrows
update riwayat_diklat_struktural
set deleted_at = now()
where id = $1 and pns_nip = $2::varchar and deleted_at is null
`

type DeleteRiwayatPelatihanStrukturalParams struct {
	ID  string `db:"id"`
	Nip string `db:"nip"`
}

func (q *Queries) DeleteRiwayatPelatihanStruktural(ctx context.Context, arg DeleteRiwayatPelatihanStrukturalParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRiwayatPelatihanStruktural, arg.ID, arg.Nip)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBerkasRiwayatPelatihanStruktural = `-- name: GetBerkasRiwayatPelatihanStruktural :one
select file_base64 from riwayat_diklat_struktural
where pns_nip = $1 and id = $2 and deleted_at is null
`

type GetBerkasRiwayatPelatihanStrukturalParams struct {
	PnsNip pgtype.Text `db:"pns_nip"`
	ID     string      `db:"id"`
}

func (q *Queries) GetBerkasRiwayatPelatihanStruktural(ctx context.Context, arg GetBerkasRiwayatPelatihanStrukturalParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getBerkasRiwayatPelatihanStruktural, arg.PnsNip, arg.ID)
	var file_base64 pgtype.Text
	err := row.Scan(&file_base64)
	return file_base64, err
}

const listRiwayatPelatihanStruktural = `-- name: ListRiwayatPelatihanStruktural :many
SELECT
    rs.id,
    rs.nama_diklat,
    rs.tanggal,
    rs.tahun,
    rs.nomor,
    rs.lama
FROM riwayat_diklat_struktural rs
WHERE rs.pns_nip = $1
AND rs.deleted_at IS NULL
ORDER BY rs."tahun" DESC NULLS LAST
LIMIT $2 OFFSET $3
`

type ListRiwayatPelatihanStrukturalParams struct {
	PnsNip pgtype.Text `db:"pns_nip"`
	Limit  int32       `db:"limit"`
	Offset int32       `db:"offset"`
}

type ListRiwayatPelatihanStrukturalRow struct {
	ID         string        `db:"id"`
	NamaDiklat pgtype.Text   `db:"nama_diklat"`
	Tanggal    pgtype.Date   `db:"tanggal"`
	Tahun      pgtype.Int2   `db:"tahun"`
	Nomor      pgtype.Text   `db:"nomor"`
	Lama       pgtype.Float4 `db:"lama"`
}

func (q *Queries) ListRiwayatPelatihanStruktural(ctx context.Context, arg ListRiwayatPelatihanStrukturalParams) ([]ListRiwayatPelatihanStrukturalRow, error) {
	rows, err := q.db.Query(ctx, listRiwayatPelatihanStruktural, arg.PnsNip, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRiwayatPelatihanStrukturalRow
	for rows.Next() {
		var i ListRiwayatPelatihanStrukturalRow
		if err := rows.Scan(
			&i.ID,
			&i.NamaDiklat,
			&i.Tanggal,
			&i.Tahun,
			&i.Nomor,
			&i.Lama,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRiwayatPelatihanStruktural = `-- name: UpdateRiwayatPelatihanStruktural :execrows
update riwayat_diklat_struktural
set
    nama_diklat = $1,
    tanggal = $2,
    tahun = $3,
    lama = $4,
    nomor = $5,
    updated_at = now()
where id = $6 and pns_nip = $7::varchar and deleted_at is null
`

type UpdateRiwayatPelatihanStrukturalParams struct {
	NamaDiklat pgtype.Text   `db:"nama_diklat"`
	Tanggal    pgtype.Date   `db:"tanggal"`
	Tahun      pgtype.Int2   `db:"tahun"`
	Lama       pgtype.Float4 `db:"lama"`
	Nomor      pgtype.Text   `db:"nomor"`
	ID         string        `db:"id"`
	Nip        string        `db:"nip"`
}

func (q *Queries) UpdateRiwayatPelatihanStruktural(ctx context.Context, arg UpdateRiwayatPelatihanStrukturalParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRiwayatPelatihanStruktural,
		arg.NamaDiklat,
		arg.Tanggal,
		arg.Tahun,
		arg.Lama,
		arg.Nomor,
		arg.ID,
		arg.Nip,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const uploadBerkasRiwayatPelatihanStruktural = `-- name: UploadBerkasRiwayatPelatihanStruktural :execrows
update riwayat_diklat_struktural
set
    file_base64 = $1,
    updated_at = now()
where id = $2 and pns_nip = $3::varchar and deleted_at is null
`

type UploadBerkasRiwayatPelatihanStrukturalParams struct {
	FileBase64 pgtype.Text `db:"file_base64"`
	ID         string      `db:"id"`
	Nip        string      `db:"nip"`
}

func (q *Queries) UploadBerkasRiwayatPelatihanStruktural(ctx context.Context, arg UploadBerkasRiwayatPelatihanStrukturalParams) (int64, error) {
	result, err := q.db.Exec(ctx, uploadBerkasRiwayatPelatihanStruktural, arg.FileBase64, arg.ID, arg.Nip)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
