// Code generated by sqlc. DO NOT EDIT.
// source: riwayat_asesmen_nine_box.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRiwayatAsesmenNineBox = `-- name: CountRiwayatAsesmenNineBox :one
select count(1) from riwayat_asesmen_nine_box
where pns_nip = $1 and deleted_at is null
`

func (q *Queries) CountRiwayatAsesmenNineBox(ctx context.Context, pnsNip pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countRiwayatAsesmenNineBox, pnsNip)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listRiwayatAsesmenNineBox = `-- name: ListRiwayatAsesmenNineBox :many
select
  id,
  tahun,
  kesimpulan
from riwayat_asesmen_nine_box
where pns_nip = $1 and deleted_at is null
order by tahun desc nulls last
limit $2 offset $3
`

type ListRiwayatAsesmenNineBoxParams struct {
	PnsNip pgtype.Text `db:"pns_nip"`
	Limit  int32       `db:"limit"`
	Offset int32       `db:"offset"`
}

type ListRiwayatAsesmenNineBoxRow struct {
	ID         int32       `db:"id"`
	Tahun      pgtype.Int2 `db:"tahun"`
	Kesimpulan pgtype.Text `db:"kesimpulan"`
}

func (q *Queries) ListRiwayatAsesmenNineBox(ctx context.Context, arg ListRiwayatAsesmenNineBoxParams) ([]ListRiwayatAsesmenNineBoxRow, error) {
	rows, err := q.db.Query(ctx, listRiwayatAsesmenNineBox, arg.PnsNip, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRiwayatAsesmenNineBoxRow
	for rows.Next() {
		var i ListRiwayatAsesmenNineBoxRow
		if err := rows.Scan(&i.ID, &i.Tahun, &i.Kesimpulan); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
