// Code generated by sqlc. DO NOT EDIT.
// source: riwayat_kepangkatan.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRiwayatKepangkatan = `-- name: CountRiwayatKepangkatan :one
select count(*) from riwayat_golongan rg
where rg.deleted_at is null and rg.pns_nip = $1::varchar
`

func (q *Queries) CountRiwayatKepangkatan(ctx context.Context, pnsNip string) (int64, error) {
	row := q.db.QueryRow(ctx, countRiwayatKepangkatan, pnsNip)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBerkasRiwayatKepangkatan = `-- name: GetBerkasRiwayatKepangkatan :one
select file_base64 from riwayat_golongan
where pns_nip = $1 and id = $2 and deleted_at is null
`

type GetBerkasRiwayatKepangkatanParams struct {
	PnsNip pgtype.Text `db:"pns_nip"`
	ID     int32       `db:"id"`
}

func (q *Queries) GetBerkasRiwayatKepangkatan(ctx context.Context, arg GetBerkasRiwayatKepangkatanParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getBerkasRiwayatKepangkatan, arg.PnsNip, arg.ID)
	var file_base64 pgtype.Text
	err := row.Scan(&file_base64)
	return file_base64, err
}

const listRiwayatKepangkatan = `-- name: ListRiwayatKepangkatan :many
select
    rg.id,
    ref_jenis_kp.id as jenis_kp_id,
    ref_jenis_kp.nama as nama_jenis_kp,
    ref_golongan.id as golongan_id,
    ref_golongan.nama as nama_golongan,
    ref_golongan.nama_pangkat as nama_golongan_pangkat,
    rg.tmt_golongan,
    rg.sk_nomor,
    rg.sk_tanggal,
    rg.mk_golongan_tahun,
    rg.mk_golongan_bulan,
    rg.no_bkn,
    rg.tanggal_bkn,
    rg.jumlah_angka_kredit_tambahan,
    rg.jumlah_angka_kredit_utama
from riwayat_golongan rg
LEFT join ref_jenis_kp on rg.jenis_kp_id = ref_jenis_kp.id and ref_jenis_kp.deleted_at is null
LEFT join ref_golongan on rg.golongan_id = ref_golongan.id and ref_golongan.deleted_at is null
where rg.deleted_at is null and rg.pns_nip = $3::varchar
order by rg.tmt_golongan desc
limit $1 offset $2
`

type ListRiwayatKepangkatanParams struct {
	Limit  int32  `db:"limit"`
	Offset int32  `db:"offset"`
	PnsNip string `db:"pns_nip"`
}

type ListRiwayatKepangkatanRow struct {
	ID                        int32       `db:"id"`
	JenisKpID                 pgtype.Int4 `db:"jenis_kp_id"`
	NamaJenisKp               pgtype.Text `db:"nama_jenis_kp"`
	GolonganID                pgtype.Int4 `db:"golongan_id"`
	NamaGolongan              pgtype.Text `db:"nama_golongan"`
	NamaGolonganPangkat       pgtype.Text `db:"nama_golongan_pangkat"`
	TmtGolongan               pgtype.Date `db:"tmt_golongan"`
	SkNomor                   pgtype.Text `db:"sk_nomor"`
	SkTanggal                 pgtype.Date `db:"sk_tanggal"`
	MkGolonganTahun           pgtype.Int2 `db:"mk_golongan_tahun"`
	MkGolonganBulan           pgtype.Int2 `db:"mk_golongan_bulan"`
	NoBkn                     pgtype.Text `db:"no_bkn"`
	TanggalBkn                pgtype.Date `db:"tanggal_bkn"`
	JumlahAngkaKreditTambahan pgtype.Int2 `db:"jumlah_angka_kredit_tambahan"`
	JumlahAngkaKreditUtama    pgtype.Int2 `db:"jumlah_angka_kredit_utama"`
}

func (q *Queries) ListRiwayatKepangkatan(ctx context.Context, arg ListRiwayatKepangkatanParams) ([]ListRiwayatKepangkatanRow, error) {
	rows, err := q.db.Query(ctx, listRiwayatKepangkatan, arg.Limit, arg.Offset, arg.PnsNip)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRiwayatKepangkatanRow
	for rows.Next() {
		var i ListRiwayatKepangkatanRow
		if err := rows.Scan(
			&i.ID,
			&i.JenisKpID,
			&i.NamaJenisKp,
			&i.GolonganID,
			&i.NamaGolongan,
			&i.NamaGolonganPangkat,
			&i.TmtGolongan,
			&i.SkNomor,
			&i.SkTanggal,
			&i.MkGolonganTahun,
			&i.MkGolonganBulan,
			&i.NoBkn,
			&i.TanggalBkn,
			&i.JumlahAngkaKreditTambahan,
			&i.JumlahAngkaKreditUtama,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
