// Code generated by sqlc. DO NOT EDIT.
// source: riwayat_pendidikan.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRiwayatPendidikan = `-- name: CountRiwayatPendidikan :one
select count(1)
from riwayat_pendidikan
where nip = $1 and deleted_at is null
`

func (q *Queries) CountRiwayatPendidikan(ctx context.Context, nip pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countRiwayatPendidikan, nip)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBerkasRiwayatPendidikan = `-- name: GetBerkasRiwayatPendidikan :one
select file_base64 from riwayat_pendidikan
where nip = $1 and id = $2 and deleted_at is null
`

type GetBerkasRiwayatPendidikanParams struct {
	Nip pgtype.Text `db:"nip"`
	ID  int32       `db:"id"`
}

func (q *Queries) GetBerkasRiwayatPendidikan(ctx context.Context, arg GetBerkasRiwayatPendidikanParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getBerkasRiwayatPendidikan, arg.Nip, arg.ID)
	var file_base64 pgtype.Text
	err := row.Scan(&file_base64)
	return file_base64, err
}

const listRiwayatPendidikan = `-- name: ListRiwayatPendidikan :many
select
    rp.id,
    rp.nama_sekolah,
    rp.tahun_lulus,
    rp.no_ijazah,
    rp.gelar_depan,
    rp.gelar_belakang,
    rp.tugas_belajar,
    rp.negara_sekolah,
    tk.nama as jenjang_pendidikan,
    pend.nama as pendidikan
from riwayat_pendidikan rp
left join ref_tingkat_pendidikan tk on tk.id = rp.tingkat_pendidikan_id and tk.deleted_at is null
left join ref_pendidikan pend on pend.id = rp.pendidikan_id and pend.deleted_at is null
where rp.nip = $1 and rp.deleted_at is null
order by rp.tahun_lulus desc
limit $2 offset $3
`

type ListRiwayatPendidikanParams struct {
	Nip    pgtype.Text `db:"nip"`
	Limit  int32       `db:"limit"`
	Offset int32       `db:"offset"`
}

type ListRiwayatPendidikanRow struct {
	ID                int32       `db:"id"`
	NamaSekolah       pgtype.Text `db:"nama_sekolah"`
	TahunLulus        pgtype.Int2 `db:"tahun_lulus"`
	NoIjazah          pgtype.Text `db:"no_ijazah"`
	GelarDepan        pgtype.Text `db:"gelar_depan"`
	GelarBelakang     pgtype.Text `db:"gelar_belakang"`
	TugasBelajar      pgtype.Int2 `db:"tugas_belajar"`
	NegaraSekolah     pgtype.Text `db:"negara_sekolah"`
	JenjangPendidikan pgtype.Text `db:"jenjang_pendidikan"`
	Pendidikan        pgtype.Text `db:"pendidikan"`
}

func (q *Queries) ListRiwayatPendidikan(ctx context.Context, arg ListRiwayatPendidikanParams) ([]ListRiwayatPendidikanRow, error) {
	rows, err := q.db.Query(ctx, listRiwayatPendidikan, arg.Nip, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRiwayatPendidikanRow
	for rows.Next() {
		var i ListRiwayatPendidikanRow
		if err := rows.Scan(
			&i.ID,
			&i.NamaSekolah,
			&i.TahunLulus,
			&i.NoIjazah,
			&i.GelarDepan,
			&i.GelarBelakang,
			&i.TugasBelajar,
			&i.NegaraSekolah,
			&i.JenjangPendidikan,
			&i.Pendidikan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
