// Code generated by sqlc. DO NOT EDIT.
// source: sk_pegawai.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSKPegawaiByNIP = `-- name: CountSKPegawaiByNIP :one
SELECT COUNT(1) as total
FROM file_digital_signature fds
WHERE fds.deleted_at IS NULL
    AND fds.nip_sk = $1::VARCHAR
    AND ($2::varchar IS NULL OR fds.no_sk ILIKE '%' || $2::varchar || '%')
    AND ($3::integer IS NULL OR fds.status_sk = $3::integer)
    AND ($4::varchar is null OR fds.kategori ILIKE '%' || $4::varchar || '%')
`

type CountSKPegawaiByNIPParams struct {
	Nip        string      `db:"nip"`
	NoSk       pgtype.Text `db:"no_sk"`
	StatusSk   pgtype.Int4 `db:"status_sk"`
	KategoriSk pgtype.Text `db:"kategori_sk"`
}

func (q *Queries) CountSKPegawaiByNIP(ctx context.Context, arg CountSKPegawaiByNIPParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSKPegawaiByNIP,
		arg.Nip,
		arg.NoSk,
		arg.StatusSk,
		arg.KategoriSk,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getSKPegawaiByNIPAndID = `-- name: GetSKPegawaiByNIPAndID :one
SELECT
    fds.kategori as kategori_sk,
    fds.no_sk,
    fds.tanggal_sk,
    fds.status_sk,
    p.unor_id,
    fds.nama_pemilik_sk,
    pemroses.nama as nama_penandatangan
FROM file_digital_signature fds
JOIN pegawai p on p.nip_baru = fds.nip_sk
LEFT JOIN pegawai pemroses on pemroses.nip_baru = fds.nip_pemroses
WHERE fds.deleted_at IS NULL
    AND fds.nip_sk = $1::VARCHAR
    AND fds.file_id = $2::varchar
`

type GetSKPegawaiByNIPAndIDParams struct {
	Nip string `db:"nip"`
	ID  string `db:"id"`
}

type GetSKPegawaiByNIPAndIDRow struct {
	KategoriSk        pgtype.Text `db:"kategori_sk"`
	NoSk              pgtype.Text `db:"no_sk"`
	TanggalSk         pgtype.Date `db:"tanggal_sk"`
	StatusSk          pgtype.Int2 `db:"status_sk"`
	UnorID            pgtype.Text `db:"unor_id"`
	NamaPemilikSk     pgtype.Text `db:"nama_pemilik_sk"`
	NamaPenandatangan pgtype.Text `db:"nama_penandatangan"`
}

func (q *Queries) GetSKPegawaiByNIPAndID(ctx context.Context, arg GetSKPegawaiByNIPAndIDParams) (GetSKPegawaiByNIPAndIDRow, error) {
	row := q.db.QueryRow(ctx, getSKPegawaiByNIPAndID, arg.Nip, arg.ID)
	var i GetSKPegawaiByNIPAndIDRow
	err := row.Scan(
		&i.KategoriSk,
		&i.NoSk,
		&i.TanggalSk,
		&i.StatusSk,
		&i.UnorID,
		&i.NamaPemilikSk,
		&i.NamaPenandatangan,
	)
	return i, err
}

const listSKPegawaiByNIP = `-- name: ListSKPegawaiByNIP :many
SELECT
    fds.kategori as kategori_sk,
    fds.no_sk,
    fds.tanggal_sk,
    fds.status_sk,
    p.unor_id
FROM file_digital_signature fds
JOIN pegawai p on p.nip_baru = fds.nip_sk
WHERE fds.deleted_at IS NULL
    AND fds.nip_sk = $3::varchar
    AND ($4::varchar IS NULL OR fds.no_sk ILIKE '%' || $4::varchar || '%')
    AND ($5::integer IS NULL OR fds.status_sk = $5::integer)
    AND ($6::varchar is null OR fds.kategori ILIKE '%' || $6::varchar || '%')
ORDER BY fds.created_at DESC
LIMIT $1 OFFSET $2
`

type ListSKPegawaiByNIPParams struct {
	Limit      int32       `db:"limit"`
	Offset     int32       `db:"offset"`
	Nip        string      `db:"nip"`
	NoSk       pgtype.Text `db:"no_sk"`
	StatusSk   pgtype.Int4 `db:"status_sk"`
	KategoriSk pgtype.Text `db:"kategori_sk"`
}

type ListSKPegawaiByNIPRow struct {
	KategoriSk pgtype.Text `db:"kategori_sk"`
	NoSk       pgtype.Text `db:"no_sk"`
	TanggalSk  pgtype.Date `db:"tanggal_sk"`
	StatusSk   pgtype.Int2 `db:"status_sk"`
	UnorID     pgtype.Text `db:"unor_id"`
}

func (q *Queries) ListSKPegawaiByNIP(ctx context.Context, arg ListSKPegawaiByNIPParams) ([]ListSKPegawaiByNIPRow, error) {
	rows, err := q.db.Query(ctx, listSKPegawaiByNIP,
		arg.Limit,
		arg.Offset,
		arg.Nip,
		arg.NoSk,
		arg.StatusSk,
		arg.KategoriSk,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSKPegawaiByNIPRow
	for rows.Next() {
		var i ListSKPegawaiByNIPRow
		if err := rows.Scan(
			&i.KategoriSk,
			&i.NoSk,
			&i.TanggalSk,
			&i.StatusSk,
			&i.UnorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
