// Code generated by sqlc. DO NOT EDIT.
// source: surat_keputusan.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAntreanKoreksiSuratKeputusanByNIP = `-- name: CountAntreanKoreksiSuratKeputusanByNIP :one
SELECT 
    COUNT(DISTINCT fds.kategori) AS total
FROM 
    surat_keputusan fds
JOIN 
    koreksi_surat_keputusan fdc ON fds.file_id = fdc.file_id AND fdc.deleted_at IS NULL
JOIN 
    pegawai korektor ON fdc.pegawai_korektor_id = korektor.pns_id AND korektor.deleted_at IS NULL
WHERE 
    fds.status_ttd = 0
    AND fds.ds_ok = true
    AND fds.kategori != '< Semua >'
    AND (fdc.status_koreksi = 0 OR fdc.status_koreksi IS NULL)
    AND korektor.nip_baru = $1::varchar
    AND fds.ds_ok = true
`

func (q *Queries) CountAntreanKoreksiSuratKeputusanByNIP(ctx context.Context, nipKorektor string) (int64, error) {
	row := q.db.QueryRow(ctx, countAntreanKoreksiSuratKeputusanByNIP, nipKorektor)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countKoreksiSuratKeputusanByPNSID = `-- name: CountKoreksiSuratKeputusanByPNSID :one
select
    count(1) as total
FROM koreksi_surat_keputusan fdc
JOIN surat_keputusan fds ON fds.file_id = fdc.file_id AND fds.deleted_at IS NULL
JOIN pegawai p ON fds.nip_sk = p.nip_baru AND p.deleted_at IS NULL
LEFT JOIN ref_unit_kerja uk ON p.unor_id = uk.id AND uk.deleted_at IS NULL
WHERE fdc.deleted_at IS NULL
    AND ($1::VARCHAR IS NULL
        OR $1::VARCHAR = uk.id
        OR $1::VARCHAR = uk.eselon_1
        OR $1::VARCHAR = uk.eselon_2
        OR $1::VARCHAR = uk.eselon_3
        OR $1::VARCHAR = uk.eselon_4)
    AND ($2::VARCHAR IS NULL OR p.nama ILIKE '%' || $2::VARCHAR || '%')
    AND ($3::VARCHAR IS NULL OR fds.nip_sk = $3::VARCHAR)
    AND ($4::INTEGER IS NULL OR p.gol_id = $4::INTEGER)
    AND ($5::VARCHAR IS NULL OR p.jabatan_instansi_id = $5::VARCHAR)
    AND ($6::VARCHAR is NULL OR fds.kategori ILIKE '%' || $6::VARCHAR || '%')
    AND ($7::VARCHAR IS NULL OR fds.no_sk ILIKE '%' || $7::VARCHAR || '%')
    AND (
        $8::integer[] IS NULL
        OR fdc.status_koreksi = ANY($8::integer[])
    )
    AND fdc.pegawai_korektor_id = $9::varchar
    AND ds_ok = true
`

type CountKoreksiSuratKeputusanByPNSIDParams struct {
	UnitKerjaID   pgtype.Text `db:"unit_kerja_id"`
	NamaPemilik   pgtype.Text `db:"nama_pemilik"`
	NipPemilik    pgtype.Text `db:"nip_pemilik"`
	GolonganID    pgtype.Int4 `db:"golongan_id"`
	JabatanID     pgtype.Text `db:"jabatan_id"`
	KategoriSk    pgtype.Text `db:"kategori_sk"`
	NoSk          pgtype.Text `db:"no_sk"`
	StatusKoreksi []int32     `db:"status_koreksi"`
	PnsID         string      `db:"pns_id"`
}

func (q *Queries) CountKoreksiSuratKeputusanByPNSID(ctx context.Context, arg CountKoreksiSuratKeputusanByPNSIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, countKoreksiSuratKeputusanByPNSID,
		arg.UnitKerjaID,
		arg.NamaPemilik,
		arg.NipPemilik,
		arg.GolonganID,
		arg.JabatanID,
		arg.KategoriSk,
		arg.NoSk,
		arg.StatusKoreksi,
		arg.PnsID,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countLogRequestSuratKeputusan = `-- name: CountLogRequestSuratKeputusan :one
SELECT COUNT(1) 
FROM log_request_surat_keputusan lrs 
JOIN pegawai p on p.nik = lrs.nik and p.deleted_at is null 
WHERE 
    lrs.deleted_at IS NULL AND ($1::int2 IS NULL OR lrs.status = $1::int2)
    AND ($2::varchar IS NULL OR p.nik = $2::varchar)
`

type CountLogRequestSuratKeputusanParams struct {
	Status pgtype.Int2 `db:"status"`
	Nik    pgtype.Text `db:"nik"`
}

func (q *Queries) CountLogRequestSuratKeputusan(ctx context.Context, arg CountLogRequestSuratKeputusanParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLogRequestSuratKeputusan, arg.Status, arg.Nik)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSuratKeputusan = `-- name: CountSuratKeputusan :one
SELECT COUNT(*) as total
FROM surat_keputusan fds
JOIN pegawai p ON fds.nip_sk = p.nip_baru AND p.deleted_at IS NULL
LEFT JOIN ref_unit_kerja uk ON p.unor_id = uk.id AND uk.deleted_at IS NULL
WHERE fds.deleted_at IS NULL
    AND ($1::VARCHAR IS NULL
        OR $1::VARCHAR = uk.id
        OR $1::VARCHAR = uk.eselon_1
        OR $1::VARCHAR = uk.eselon_2
        OR $1::VARCHAR = uk.eselon_3
        OR $1::VARCHAR = uk.eselon_4)
    AND ($2::VARCHAR IS NULL OR p.nama ILIKE '%' || $2::VARCHAR || '%')
    AND ($3::VARCHAR IS NULL OR fds.nip_sk = $3::VARCHAR)
    AND ($4::INTEGER IS NULL OR p.gol_id = $4::INTEGER)
    AND ($5::VARCHAR IS NULL OR p.jabatan_instansi_id = $5::VARCHAR)
    AND ($6::VARCHAR is NULL OR fds.kategori ILIKE '%' || $6::VARCHAR || '%')
    AND ($7::DATE IS NULL OR fds.tanggal_sk >= $7::DATE)
    AND ($8::DATE IS NULL OR fds.tanggal_sk <= $8::DATE)
    AND ($9::integer[] IS NULL OR fds.status_sk = ANY($9::integer[]))
    AND ds_ok = true
`

type CountSuratKeputusanParams struct {
	UnitKerjaID    pgtype.Text `db:"unit_kerja_id"`
	NamaPemilik    pgtype.Text `db:"nama_pemilik"`
	Nip            pgtype.Text `db:"nip"`
	GolonganID     pgtype.Int4 `db:"golongan_id"`
	JabatanID      pgtype.Text `db:"jabatan_id"`
	KategoriSk     pgtype.Text `db:"kategori_sk"`
	TanggalSkMulai pgtype.Date `db:"tanggal_sk_mulai"`
	TanggalSkAkhir pgtype.Date `db:"tanggal_sk_akhir"`
	ListStatusSk   []int32     `db:"list_status_sk"`
}

func (q *Queries) CountSuratKeputusan(ctx context.Context, arg CountSuratKeputusanParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSuratKeputusan,
		arg.UnitKerjaID,
		arg.NamaPemilik,
		arg.Nip,
		arg.GolonganID,
		arg.JabatanID,
		arg.KategoriSk,
		arg.TanggalSkMulai,
		arg.TanggalSkAkhir,
		arg.ListStatusSk,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countSuratKeputusanByNIP = `-- name: CountSuratKeputusanByNIP :one
SELECT COUNT(1) as total
FROM surat_keputusan fds
WHERE fds.deleted_at IS NULL
    AND fds.nip_sk = $1::VARCHAR
    AND ($2::varchar IS NULL OR fds.no_sk ILIKE '%' || $2::varchar || '%')
    AND ($3::integer[] IS NULL OR fds.status_sk = ANY($3::integer[]))
    AND ($4::varchar is null OR fds.kategori ILIKE '%' || $4::varchar || '%')
    AND ds_ok = true
`

type CountSuratKeputusanByNIPParams struct {
	Nip          string      `db:"nip"`
	NoSk         pgtype.Text `db:"no_sk"`
	ListStatusSk []int32     `db:"list_status_sk"`
	KategoriSk   pgtype.Text `db:"kategori_sk"`
}

func (q *Queries) CountSuratKeputusanByNIP(ctx context.Context, arg CountSuratKeputusanByNIPParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSuratKeputusanByNIP,
		arg.Nip,
		arg.NoSk,
		arg.ListStatusSk,
		arg.KategoriSk,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countTandaTanganSuratKeputusanAntreanByPNSID = `-- name: CountTandaTanganSuratKeputusanAntreanByPNSID :one
select
    count(distinct fds.kategori) as total
FROM surat_keputusan fds
JOIN koreksi_surat_keputusan fdc  ON fds.file_id = fdc.file_id AND fdc.deleted_at IS NULL AND fdc.status_koreksi = 2
WHERE fds.status_ttd = 0
  AND fds.ds_ok = true
  AND fds.kategori NOT IN ('< Semua >', '< Pilih >')
  AND fds.ttd_pegawai_id = $1::varchar
  AND fds.deleted_at IS NULL
  AND fds.ds_ok = true
`

func (q *Queries) CountTandaTanganSuratKeputusanAntreanByPNSID(ctx context.Context, pnsID string) (int64, error) {
	row := q.db.QueryRow(ctx, countTandaTanganSuratKeputusanAntreanByPNSID, pnsID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countTandaTanganSuratKeputusanByPNSID = `-- name: CountTandaTanganSuratKeputusanByPNSID :one
select
    count(1) as total
FROM surat_keputusan fds
JOIN pegawai p ON fds.nip_sk = p.nip_baru AND p.deleted_at IS NULL
LEFT JOIN ref_unit_kerja uk ON p.unor_id = uk.id AND uk.deleted_at IS NULL
WHERE fds.deleted_at IS NULL
    AND ($1::VARCHAR IS NULL
        OR $1::VARCHAR = uk.id
        OR $1::VARCHAR = uk.eselon_1
        OR $1::VARCHAR = uk.eselon_2
        OR $1::VARCHAR = uk.eselon_3
        OR $1::VARCHAR = uk.eselon_4)
    AND ($2::VARCHAR IS NULL OR p.nama ILIKE '%' || $2::VARCHAR || '%')
    AND ($3::VARCHAR IS NULL OR fds.nip_sk = $3::VARCHAR)
    AND ($4::INTEGER IS NULL OR p.gol_id = $4::INTEGER)
    AND ($5::VARCHAR IS NULL OR p.jabatan_instansi_id = $5::VARCHAR)
    AND ($6::VARCHAR is NULL OR fds.kategori ILIKE '%' || $6::VARCHAR || '%')
    AND ($7::VARCHAR IS NULL OR fds.no_sk ILIKE '%' || $7::VARCHAR || '%')
    AND fds.status_koreksi = 1 
    and ($8::integer is NULL or fds.status_ttd = $8::integer)
    AND fds.ttd_pegawai_id = $9::varchar
    AND fds.ds_ok = true
`

type CountTandaTanganSuratKeputusanByPNSIDParams struct {
	UnitKerjaID pgtype.Text `db:"unit_kerja_id"`
	NamaPemilik pgtype.Text `db:"nama_pemilik"`
	NipPemilik  pgtype.Text `db:"nip_pemilik"`
	GolonganID  pgtype.Int4 `db:"golongan_id"`
	JabatanID   pgtype.Text `db:"jabatan_id"`
	KategoriSk  pgtype.Text `db:"kategori_sk"`
	NoSk        pgtype.Text `db:"no_sk"`
	StatusTtd   pgtype.Int4 `db:"status_ttd"`
	PnsID       string      `db:"pns_id"`
}

func (q *Queries) CountTandaTanganSuratKeputusanByPNSID(ctx context.Context, arg CountTandaTanganSuratKeputusanByPNSIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTandaTanganSuratKeputusanByPNSID,
		arg.UnitKerjaID,
		arg.NamaPemilik,
		arg.NipPemilik,
		arg.GolonganID,
		arg.JabatanID,
		arg.KategoriSk,
		arg.NoSk,
		arg.StatusTtd,
		arg.PnsID,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getBerkasSuratKeputusanByID = `-- name: GetBerkasSuratKeputusanByID :one
SELECT
    file_base64
FROM
    surat_keputusan fds
WHERE
    fds.deleted_at IS NULL
    AND fds.file_id = $1::varchar
`

func (q *Queries) GetBerkasSuratKeputusanByID(ctx context.Context, id string) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getBerkasSuratKeputusanByID, id)
	var file_base64 pgtype.Text
	err := row.Scan(&file_base64)
	return file_base64, err
}

const getBerkasSuratKeputusanByNIPAndID = `-- name: GetBerkasSuratKeputusanByNIPAndID :one
SELECT
    file_base64
FROM
    surat_keputusan fds
WHERE
    fds.deleted_at IS NULL
    AND fds.nip_sk = $1::VARCHAR
    AND fds.file_id = $2::varchar
`

type GetBerkasSuratKeputusanByNIPAndIDParams struct {
	Nip string `db:"nip"`
	ID  string `db:"id"`
}

func (q *Queries) GetBerkasSuratKeputusanByNIPAndID(ctx context.Context, arg GetBerkasSuratKeputusanByNIPAndIDParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getBerkasSuratKeputusanByNIPAndID, arg.Nip, arg.ID)
	var file_base64 pgtype.Text
	err := row.Scan(&file_base64)
	return file_base64, err
}

const getBerkasSuratKeputusanSignedByID = `-- name: GetBerkasSuratKeputusanSignedByID :one
SELECT
    file_base64_sign
FROM
    surat_keputusan fds
WHERE
    fds.deleted_at IS NULL
    AND fds.file_id = $1::varchar
`

func (q *Queries) GetBerkasSuratKeputusanSignedByID(ctx context.Context, id string) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getBerkasSuratKeputusanSignedByID, id)
	var file_base64_sign pgtype.Text
	err := row.Scan(&file_base64_sign)
	return file_base64_sign, err
}

const getBerkasSuratKeputusanSignedByNIPAndID = `-- name: GetBerkasSuratKeputusanSignedByNIPAndID :one
SELECT
    file_base64_sign
FROM
    surat_keputusan fds
WHERE
    fds.deleted_at IS NULL
    AND fds.nip_sk = $1::VARCHAR
    AND fds.file_id = $2::varchar
`

type GetBerkasSuratKeputusanSignedByNIPAndIDParams struct {
	Nip string `db:"nip"`
	ID  string `db:"id"`
}

func (q *Queries) GetBerkasSuratKeputusanSignedByNIPAndID(ctx context.Context, arg GetBerkasSuratKeputusanSignedByNIPAndIDParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getBerkasSuratKeputusanSignedByNIPAndID, arg.Nip, arg.ID)
	var file_base64_sign pgtype.Text
	err := row.Scan(&file_base64_sign)
	return file_base64_sign, err
}

const getSuratKeputusanByID = `-- name: GetSuratKeputusanByID :one
SELECT
    fds.kategori as kategori_sk,
    fds.no_sk,
    fds.tanggal_sk,
    fds.status_sk,
    p.nama as nama_pemilik_sk,
    p.nip_baru as nip_pemilik_sk,
    pemroses.nama as nama_penandatangan,
    rj.nama_jabatan as jabatan_penandatangan,
    status_ttd,
    status_koreksi,
    catatan,
    ttd_pegawai_id,
    letak_ttd,
    show_qrcode,
    halaman_ttd
FROM surat_keputusan fds
JOIN pegawai p on p.nip_baru = fds.nip_sk and p.deleted_at is null
LEFT JOIN pegawai pemroses on pemroses.nip_baru = fds.nip_pemroses and pemroses.deleted_at is null
LEFT JOIN ref_jabatan rj on pemroses.jabatan_instansi_id = rj.kode_jabatan and rj.deleted_at is null
WHERE fds.deleted_at IS NULL
    AND fds.file_id = $1::varchar
`

type GetSuratKeputusanByIDRow struct {
	KategoriSk           pgtype.Text `db:"kategori_sk"`
	NoSk                 pgtype.Text `db:"no_sk"`
	TanggalSk            pgtype.Date `db:"tanggal_sk"`
	StatusSk             pgtype.Int2 `db:"status_sk"`
	NamaPemilikSk        pgtype.Text `db:"nama_pemilik_sk"`
	NipPemilikSk         pgtype.Text `db:"nip_pemilik_sk"`
	NamaPenandatangan    pgtype.Text `db:"nama_penandatangan"`
	JabatanPenandatangan pgtype.Text `db:"jabatan_penandatangan"`
	StatusTtd            pgtype.Int2 `db:"status_ttd"`
	StatusKoreksi        pgtype.Int2 `db:"status_koreksi"`
	Catatan              pgtype.Text `db:"catatan"`
	TtdPegawaiID         pgtype.Text `db:"ttd_pegawai_id"`
	LetakTtd             pgtype.Int2 `db:"letak_ttd"`
	ShowQrcode           pgtype.Bool `db:"show_qrcode"`
	HalamanTtd           pgtype.Int2 `db:"halaman_ttd"`
}

func (q *Queries) GetSuratKeputusanByID(ctx context.Context, id string) (GetSuratKeputusanByIDRow, error) {
	row := q.db.QueryRow(ctx, getSuratKeputusanByID, id)
	var i GetSuratKeputusanByIDRow
	err := row.Scan(
		&i.KategoriSk,
		&i.NoSk,
		&i.TanggalSk,
		&i.StatusSk,
		&i.NamaPemilikSk,
		&i.NipPemilikSk,
		&i.NamaPenandatangan,
		&i.JabatanPenandatangan,
		&i.StatusTtd,
		&i.StatusKoreksi,
		&i.Catatan,
		&i.TtdPegawaiID,
		&i.LetakTtd,
		&i.ShowQrcode,
		&i.HalamanTtd,
	)
	return i, err
}

const getSuratKeputusanByNIPAndID = `-- name: GetSuratKeputusanByNIPAndID :one
SELECT
    fds.kategori as kategori_sk,
    fds.no_sk,
    fds.tanggal_sk,
    fds.status_sk,
    p.nama as nama_pemilik_sk,
    pemroses.nama as nama_penandatangan
FROM surat_keputusan fds
JOIN pegawai p on p.nip_baru = fds.nip_sk  and p.deleted_at is null
LEFT JOIN pegawai pemroses on pemroses.nip_baru = fds.nip_pemroses and pemroses.deleted_at is null
WHERE fds.deleted_at IS NULL
    AND fds.nip_sk = $1::VARCHAR
    AND fds.file_id = $2::varchar
`

type GetSuratKeputusanByNIPAndIDParams struct {
	Nip string `db:"nip"`
	ID  string `db:"id"`
}

type GetSuratKeputusanByNIPAndIDRow struct {
	KategoriSk        pgtype.Text `db:"kategori_sk"`
	NoSk              pgtype.Text `db:"no_sk"`
	TanggalSk         pgtype.Date `db:"tanggal_sk"`
	StatusSk          pgtype.Int2 `db:"status_sk"`
	NamaPemilikSk     pgtype.Text `db:"nama_pemilik_sk"`
	NamaPenandatangan pgtype.Text `db:"nama_penandatangan"`
}

func (q *Queries) GetSuratKeputusanByNIPAndID(ctx context.Context, arg GetSuratKeputusanByNIPAndIDParams) (GetSuratKeputusanByNIPAndIDRow, error) {
	row := q.db.QueryRow(ctx, getSuratKeputusanByNIPAndID, arg.Nip, arg.ID)
	var i GetSuratKeputusanByNIPAndIDRow
	err := row.Scan(
		&i.KategoriSk,
		&i.NoSk,
		&i.TanggalSk,
		&i.StatusSk,
		&i.NamaPemilikSk,
		&i.NamaPenandatangan,
	)
	return i, err
}

const insertLogRequestSuratKeputusan = `-- name: InsertLogRequestSuratKeputusan :exec
INSERT INTO log_request_surat_keputusan (
    file_id,
    nik,
    keterangan,
    status,
    proses_cron,
    created_at,
    updated_at
) VALUES (
    $1::varchar,
    $2::varchar,
    $3::varchar,
    $4::integer,
    $5::boolean,
    now(),
    now()
)
`

type InsertLogRequestSuratKeputusanParams struct {
	FileID     string `db:"file_id"`
	Nik        string `db:"nik"`
	Keterangan string `db:"keterangan"`
	Status     int32  `db:"status"`
	ProsesCron bool   `db:"proses_cron"`
}

func (q *Queries) InsertLogRequestSuratKeputusan(ctx context.Context, arg InsertLogRequestSuratKeputusanParams) error {
	_, err := q.db.Exec(ctx, insertLogRequestSuratKeputusan,
		arg.FileID,
		arg.Nik,
		arg.Keterangan,
		arg.Status,
		arg.ProsesCron,
	)
	return err
}

const insertRiwayatSuratKeputusan = `-- name: InsertRiwayatSuratKeputusan :exec
INSERT INTO riwayat_surat_keputusan (
    file_id,
    nip_pemroses,
    tindakan,
    catatan_tindakan,
    akses_pengguna,
    waktu_tindakan,
    created_at,
    updated_at
) VALUES (
    $1::varchar,
    $2::varchar,
    $3::varchar,
    $4::text,
    $5::varchar,
    now(),
    now(),
    now()
)
`

type InsertRiwayatSuratKeputusanParams struct {
	FileID          string `db:"file_id"`
	NipPemroses     string `db:"nip_pemroses"`
	Tindakan        string `db:"tindakan"`
	CatatanTindakan string `db:"catatan_tindakan"`
	AksesPengguna   string `db:"akses_pengguna"`
}

func (q *Queries) InsertRiwayatSuratKeputusan(ctx context.Context, arg InsertRiwayatSuratKeputusanParams) error {
	_, err := q.db.Exec(ctx, insertRiwayatSuratKeputusan,
		arg.FileID,
		arg.NipPemroses,
		arg.Tindakan,
		arg.CatatanTindakan,
		arg.AksesPengguna,
	)
	return err
}

const listAntreanKoreksiSuratKeputusanByNIP = `-- name: ListAntreanKoreksiSuratKeputusanByNIP :many
SELECT 
  fds.kategori,
  COUNT(1) AS jumlah
FROM 
  surat_keputusan fds
JOIN 
  koreksi_surat_keputusan fdc ON fds.file_id = fdc.file_id AND fdc.deleted_at IS NULL
JOIN 
  pegawai korektor ON fdc.pegawai_korektor_id = korektor.pns_id AND korektor.deleted_at IS NULL
WHERE 
  fds.status_ttd = 0
  AND fds.ds_ok = true
  AND fds.kategori != '< Semua >'
  AND (fdc.status_koreksi = 0 OR fdc.status_koreksi IS NULL)
  AND korektor.nip_baru = $3::varchar
  AND fds.ds_ok = true
GROUP BY 
  fds.kategori
LIMIT $1 OFFSET $2
`

type ListAntreanKoreksiSuratKeputusanByNIPParams struct {
	Limit       int32  `db:"limit"`
	Offset      int32  `db:"offset"`
	NipKorektor string `db:"nip_korektor"`
}

type ListAntreanKoreksiSuratKeputusanByNIPRow struct {
	Kategori pgtype.Text `db:"kategori"`
	Jumlah   int64       `db:"jumlah"`
}

func (q *Queries) ListAntreanKoreksiSuratKeputusanByNIP(ctx context.Context, arg ListAntreanKoreksiSuratKeputusanByNIPParams) ([]ListAntreanKoreksiSuratKeputusanByNIPRow, error) {
	rows, err := q.db.Query(ctx, listAntreanKoreksiSuratKeputusanByNIP, arg.Limit, arg.Offset, arg.NipKorektor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAntreanKoreksiSuratKeputusanByNIPRow
	for rows.Next() {
		var i ListAntreanKoreksiSuratKeputusanByNIPRow
		if err := rows.Scan(&i.Kategori, &i.Jumlah); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKoreksiSuratKeputusanByPNSID = `-- name: ListKoreksiSuratKeputusanByPNSID :many
SELECT
    fds.file_id,
    p.nama as nama_pemilik_sk,
    p.nip_baru as nip_pemilik_sk,
    g.nama as nama_golongan_pemilik,
    g.nama_pangkat as pangkat_golongan_pemilik,
    rj.nama_jabatan as jabatan_pemilik,
    fds.kategori AS kategori_sk,
    fds.no_sk,
    fds.tanggal_sk,
    p.unor_id
FROM koreksi_surat_keputusan fdc
JOIN surat_keputusan fds ON fds.file_id = fdc.file_id AND fds.deleted_at IS NULL
JOIN pegawai p ON fds.nip_sk = p.nip_baru AND p.deleted_at IS NULL
LEFT JOIN ref_unit_kerja uk ON p.unor_id = uk.id AND uk.deleted_at IS NULL
LEFT JOIN ref_golongan g ON p.gol_id = g.id AND g.deleted_at IS NULL
LEFT JOIN ref_jabatan rj on p.jabatan_instansi_id = rj.kode_jabatan and rj.deleted_at is null
WHERE fdc.deleted_at IS NULL
    AND ($3::VARCHAR IS NULL
        OR $3::VARCHAR = uk.id
        OR $3::VARCHAR = uk.eselon_1
        OR $3::VARCHAR = uk.eselon_2
        OR $3::VARCHAR = uk.eselon_3
        OR $3::VARCHAR = uk.eselon_4)
    AND ($4::VARCHAR IS NULL OR p.nama ILIKE '%' || $4::VARCHAR || '%')
    AND ($5::VARCHAR IS NULL OR fds.nip_sk = $5::VARCHAR)
    AND ($6::INTEGER IS NULL OR p.gol_id = $6::INTEGER)
    AND ($7::VARCHAR IS NULL OR p.jabatan_instansi_id = $7::VARCHAR)
    AND ($8::VARCHAR is NULL OR fds.kategori ILIKE '%' || $8::VARCHAR || '%')
    AND ($9::VARCHAR IS NULL OR fds.no_sk ILIKE '%' || $9::VARCHAR || '%')
    AND (
        $10::integer[] IS NULL
        OR fdc.status_koreksi = ANY($10::integer[])
    )
    AND fdc.pegawai_korektor_id = $11::varchar
    AND ds_ok = true
ORDER BY fds.created_at DESC
LIMIT $1 OFFSET $2
`

type ListKoreksiSuratKeputusanByPNSIDParams struct {
	Limit         int32       `db:"limit"`
	Offset        int32       `db:"offset"`
	UnitKerjaID   pgtype.Text `db:"unit_kerja_id"`
	NamaPemilik   pgtype.Text `db:"nama_pemilik"`
	NipPemilik    pgtype.Text `db:"nip_pemilik"`
	GolonganID    pgtype.Int4 `db:"golongan_id"`
	JabatanID     pgtype.Text `db:"jabatan_id"`
	KategoriSk    pgtype.Text `db:"kategori_sk"`
	NoSk          pgtype.Text `db:"no_sk"`
	StatusKoreksi []int32     `db:"status_koreksi"`
	PnsID         string      `db:"pns_id"`
}

type ListKoreksiSuratKeputusanByPNSIDRow struct {
	FileID                 string      `db:"file_id"`
	NamaPemilikSk          pgtype.Text `db:"nama_pemilik_sk"`
	NipPemilikSk           pgtype.Text `db:"nip_pemilik_sk"`
	NamaGolonganPemilik    pgtype.Text `db:"nama_golongan_pemilik"`
	PangkatGolonganPemilik pgtype.Text `db:"pangkat_golongan_pemilik"`
	JabatanPemilik         pgtype.Text `db:"jabatan_pemilik"`
	KategoriSk             pgtype.Text `db:"kategori_sk"`
	NoSk                   pgtype.Text `db:"no_sk"`
	TanggalSk              pgtype.Date `db:"tanggal_sk"`
	UnorID                 pgtype.Text `db:"unor_id"`
}

func (q *Queries) ListKoreksiSuratKeputusanByPNSID(ctx context.Context, arg ListKoreksiSuratKeputusanByPNSIDParams) ([]ListKoreksiSuratKeputusanByPNSIDRow, error) {
	rows, err := q.db.Query(ctx, listKoreksiSuratKeputusanByPNSID,
		arg.Limit,
		arg.Offset,
		arg.UnitKerjaID,
		arg.NamaPemilik,
		arg.NipPemilik,
		arg.GolonganID,
		arg.JabatanID,
		arg.KategoriSk,
		arg.NoSk,
		arg.StatusKoreksi,
		arg.PnsID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKoreksiSuratKeputusanByPNSIDRow
	for rows.Next() {
		var i ListKoreksiSuratKeputusanByPNSIDRow
		if err := rows.Scan(
			&i.FileID,
			&i.NamaPemilikSk,
			&i.NipPemilikSk,
			&i.NamaGolonganPemilik,
			&i.PangkatGolonganPemilik,
			&i.JabatanPemilik,
			&i.KategoriSk,
			&i.NoSk,
			&i.TanggalSk,
			&i.UnorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKorektorSuratKeputusanByID = `-- name: ListKorektorSuratKeputusanByID :many
SELECT 
    fds.file_id,
    fdc.korektor_ke,
    korektor.nama as nama_korektor,
    korektor.nip_baru as nip_korektor,
    korektor.gelar_depan as gelar_depan_korektor,
    korektor.gelar_belakang as gelar_belakang_korektor,
    fdc.status_koreksi,
    fdc.catatan_koreksi,
    fdc.pegawai_korektor_id
FROM 
    surat_keputusan fds
JOIN 
    koreksi_surat_keputusan fdc ON fds.file_id = fdc.file_id AND fdc.deleted_at IS NULL
JOIN 
    pegawai korektor on fdc.pegawai_korektor_id = korektor.pns_id and korektor.deleted_at is null
WHERE 
    fds.deleted_at IS NULL
    AND fds.file_id = $1::varchar
    AND fds.ds_ok = true
ORDER BY fdc.korektor_ke ASC
`

type ListKorektorSuratKeputusanByIDRow struct {
	FileID                string      `db:"file_id"`
	KorektorKe            pgtype.Int2 `db:"korektor_ke"`
	NamaKorektor          pgtype.Text `db:"nama_korektor"`
	NipKorektor           pgtype.Text `db:"nip_korektor"`
	GelarDepanKorektor    pgtype.Text `db:"gelar_depan_korektor"`
	GelarBelakangKorektor pgtype.Text `db:"gelar_belakang_korektor"`
	StatusKoreksi         pgtype.Int2 `db:"status_koreksi"`
	CatatanKoreksi        pgtype.Text `db:"catatan_koreksi"`
	PegawaiKorektorID     pgtype.Text `db:"pegawai_korektor_id"`
}

func (q *Queries) ListKorektorSuratKeputusanByID(ctx context.Context, id string) ([]ListKorektorSuratKeputusanByIDRow, error) {
	rows, err := q.db.Query(ctx, listKorektorSuratKeputusanByID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKorektorSuratKeputusanByIDRow
	for rows.Next() {
		var i ListKorektorSuratKeputusanByIDRow
		if err := rows.Scan(
			&i.FileID,
			&i.KorektorKe,
			&i.NamaKorektor,
			&i.NipKorektor,
			&i.GelarDepanKorektor,
			&i.GelarBelakangKorektor,
			&i.StatusKoreksi,
			&i.CatatanKoreksi,
			&i.PegawaiKorektorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogRequestSuratKeputusan = `-- name: ListLogRequestSuratKeputusan :many
SELECT
    file_id,
    p.nik,
    p.nama,
    keterangan,
    status,
    proses_cron,
    lrs.created_at,
    lrs.updated_at
FROM log_request_surat_keputusan lrs
JOIN pegawai p on p.nik = lrs.nik and p.deleted_at is null
WHERE 
    lrs.deleted_at IS NULL
    AND ($3::int2 IS NULL OR lrs.status = $3::int2)
    AND ($4::varchar IS NULL OR p.nik = $4::varchar)
ORDER BY lrs.created_at DESC
LIMIT $1 OFFSET $2
`

type ListLogRequestSuratKeputusanParams struct {
	Limit  int32       `db:"limit"`
	Offset int32       `db:"offset"`
	Status pgtype.Int2 `db:"status"`
	Nik    pgtype.Text `db:"nik"`
}

type ListLogRequestSuratKeputusanRow struct {
	FileID     pgtype.Text        `db:"file_id"`
	Nik        pgtype.Text        `db:"nik"`
	Nama       pgtype.Text        `db:"nama"`
	Keterangan pgtype.Text        `db:"keterangan"`
	Status     pgtype.Int2        `db:"status"`
	ProsesCron pgtype.Bool        `db:"proses_cron"`
	CreatedAt  pgtype.Timestamptz `db:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at"`
}

func (q *Queries) ListLogRequestSuratKeputusan(ctx context.Context, arg ListLogRequestSuratKeputusanParams) ([]ListLogRequestSuratKeputusanRow, error) {
	rows, err := q.db.Query(ctx, listLogRequestSuratKeputusan,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Nik,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLogRequestSuratKeputusanRow
	for rows.Next() {
		var i ListLogRequestSuratKeputusanRow
		if err := rows.Scan(
			&i.FileID,
			&i.Nik,
			&i.Nama,
			&i.Keterangan,
			&i.Status,
			&i.ProsesCron,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogSuratKeputusanByID = `-- name: ListLogSuratKeputusanByID :many
SELECT
    tindakan as log,
    pemroses.nama as actor,
    fdsr.created_at as waktu_tindakan
FROM
    riwayat_surat_keputusan fdsr
LEFT JOIN pegawai pemroses on pemroses.nip_baru = fdsr.nip_pemroses and pemroses.deleted_at is null
WHERE fdsr.file_id = $1::varchar and fdsr.deleted_at IS NULL
`

type ListLogSuratKeputusanByIDRow struct {
	Log           pgtype.Text        `db:"log"`
	Actor         pgtype.Text        `db:"actor"`
	WaktuTindakan pgtype.Timestamptz `db:"waktu_tindakan"`
}

func (q *Queries) ListLogSuratKeputusanByID(ctx context.Context, id string) ([]ListLogSuratKeputusanByIDRow, error) {
	rows, err := q.db.Query(ctx, listLogSuratKeputusanByID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLogSuratKeputusanByIDRow
	for rows.Next() {
		var i ListLogSuratKeputusanByIDRow
		if err := rows.Scan(&i.Log, &i.Actor, &i.WaktuTindakan); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuratKeputusan = `-- name: ListSuratKeputusan :many
SELECT
    fds.file_id,
    p.nama as nama_pemilik_sk,
    p.nip_baru as nip_pemilik_sk,
    fds.kategori AS kategori_sk,
    fds.no_sk,
    fds.tanggal_sk,
    p.unor_id,
    fds.status_sk,
    rj.nama_jabatan as jabatan_pemilik,
    rg.nama as golongan_pemilik,
    rg.nama_pangkat as pangkat_golongan_pemilik
FROM surat_keputusan fds
JOIN pegawai p ON fds.nip_sk = p.nip_baru AND p.deleted_at IS NULL
LEFT JOIN ref_unit_kerja uk ON p.unor_id = uk.id AND uk.deleted_at IS NULL
LEFT JOIN ref_jabatan rj ON rj.kode_jabatan = p.jabatan_instansi_id AND rj.deleted_at IS NULL
LEFT JOIN ref_golongan rg on rg.id = p.gol_id and rg.deleted_at is null
WHERE fds.deleted_at IS NULL
    AND ($3::VARCHAR IS NULL
        OR $3::VARCHAR = uk.id
        OR $3::VARCHAR = uk.eselon_1
        OR $3::VARCHAR = uk.eselon_2
        OR $3::VARCHAR = uk.eselon_3
        OR $3::VARCHAR = uk.eselon_4)
    AND ($4::VARCHAR IS NULL OR p.nama ILIKE '%' || $4::VARCHAR || '%')
    AND ($5::VARCHAR IS NULL OR fds.nip_sk = $5::VARCHAR)
    AND ($6::INTEGER IS NULL OR p.gol_id = $6::INTEGER)
    AND ($7::VARCHAR IS NULL OR p.jabatan_instansi_id = $7::VARCHAR)
    AND ($8::VARCHAR is NULL OR fds.kategori ILIKE '%' || $8::VARCHAR || '%')
    AND ($9::DATE IS NULL OR fds.tanggal_sk >= $9::DATE)
    AND ($10::DATE IS NULL OR fds.tanggal_sk <= $10::DATE)
    AND ($11::integer[] IS NULL OR fds.status_sk = ANY($11::integer[]))
    AND ds_ok = true
ORDER BY fds.created_at DESC
LIMIT $1 OFFSET $2
`

type ListSuratKeputusanParams struct {
	Limit          int32       `db:"limit"`
	Offset         int32       `db:"offset"`
	UnitKerjaID    pgtype.Text `db:"unit_kerja_id"`
	NamaPemilik    pgtype.Text `db:"nama_pemilik"`
	Nip            pgtype.Text `db:"nip"`
	GolonganID     pgtype.Int4 `db:"golongan_id"`
	JabatanID      pgtype.Text `db:"jabatan_id"`
	KategoriSk     pgtype.Text `db:"kategori_sk"`
	TanggalSkMulai pgtype.Date `db:"tanggal_sk_mulai"`
	TanggalSkAkhir pgtype.Date `db:"tanggal_sk_akhir"`
	ListStatusSk   []int32     `db:"list_status_sk"`
}

type ListSuratKeputusanRow struct {
	FileID                 string      `db:"file_id"`
	NamaPemilikSk          pgtype.Text `db:"nama_pemilik_sk"`
	NipPemilikSk           pgtype.Text `db:"nip_pemilik_sk"`
	KategoriSk             pgtype.Text `db:"kategori_sk"`
	NoSk                   pgtype.Text `db:"no_sk"`
	TanggalSk              pgtype.Date `db:"tanggal_sk"`
	UnorID                 pgtype.Text `db:"unor_id"`
	StatusSk               pgtype.Int2 `db:"status_sk"`
	JabatanPemilik         pgtype.Text `db:"jabatan_pemilik"`
	GolonganPemilik        pgtype.Text `db:"golongan_pemilik"`
	PangkatGolonganPemilik pgtype.Text `db:"pangkat_golongan_pemilik"`
}

func (q *Queries) ListSuratKeputusan(ctx context.Context, arg ListSuratKeputusanParams) ([]ListSuratKeputusanRow, error) {
	rows, err := q.db.Query(ctx, listSuratKeputusan,
		arg.Limit,
		arg.Offset,
		arg.UnitKerjaID,
		arg.NamaPemilik,
		arg.Nip,
		arg.GolonganID,
		arg.JabatanID,
		arg.KategoriSk,
		arg.TanggalSkMulai,
		arg.TanggalSkAkhir,
		arg.ListStatusSk,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSuratKeputusanRow
	for rows.Next() {
		var i ListSuratKeputusanRow
		if err := rows.Scan(
			&i.FileID,
			&i.NamaPemilikSk,
			&i.NipPemilikSk,
			&i.KategoriSk,
			&i.NoSk,
			&i.TanggalSk,
			&i.UnorID,
			&i.StatusSk,
			&i.JabatanPemilik,
			&i.GolonganPemilik,
			&i.PangkatGolonganPemilik,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuratKeputusanByNIP = `-- name: ListSuratKeputusanByNIP :many
SELECT
    fds.file_id,
    fds.kategori as kategori_sk,
    fds.no_sk,
    fds.tanggal_sk,
    fds.status_sk
FROM surat_keputusan fds
WHERE fds.deleted_at IS NULL
    AND fds.nip_sk = $3::varchar
    AND ($4::varchar IS NULL OR fds.no_sk ILIKE '%' || $4::varchar || '%')
    AND ($5::integer[] IS NULL OR fds.status_sk = ANY($5::integer[]))
    AND ($6::varchar is null OR fds.kategori ILIKE '%' || $6::varchar || '%')
    AND ds_ok = true
ORDER BY fds.created_at DESC
LIMIT $1 OFFSET $2
`

type ListSuratKeputusanByNIPParams struct {
	Limit        int32       `db:"limit"`
	Offset       int32       `db:"offset"`
	Nip          string      `db:"nip"`
	NoSk         pgtype.Text `db:"no_sk"`
	ListStatusSk []int32     `db:"list_status_sk"`
	KategoriSk   pgtype.Text `db:"kategori_sk"`
}

type ListSuratKeputusanByNIPRow struct {
	FileID     string      `db:"file_id"`
	KategoriSk pgtype.Text `db:"kategori_sk"`
	NoSk       pgtype.Text `db:"no_sk"`
	TanggalSk  pgtype.Date `db:"tanggal_sk"`
	StatusSk   pgtype.Int2 `db:"status_sk"`
}

func (q *Queries) ListSuratKeputusanByNIP(ctx context.Context, arg ListSuratKeputusanByNIPParams) ([]ListSuratKeputusanByNIPRow, error) {
	rows, err := q.db.Query(ctx, listSuratKeputusanByNIP,
		arg.Limit,
		arg.Offset,
		arg.Nip,
		arg.NoSk,
		arg.ListStatusSk,
		arg.KategoriSk,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSuratKeputusanByNIPRow
	for rows.Next() {
		var i ListSuratKeputusanByNIPRow
		if err := rows.Scan(
			&i.FileID,
			&i.KategoriSk,
			&i.NoSk,
			&i.TanggalSk,
			&i.StatusSk,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTandaTanganSuratKeputusanAntreanByPNSID = `-- name: ListTandaTanganSuratKeputusanAntreanByPNSID :many
SELECT 
    fds.kategori,
    fds.ttd_pegawai_id,
    COUNT(*) AS jumlah
FROM surat_keputusan fds
JOIN koreksi_surat_keputusan fdc  ON fds.file_id = fdc.file_id AND fdc.deleted_at IS NULL AND fdc.status_koreksi = 2
WHERE fds.status_ttd = 0
  AND fds.ds_ok = true
  AND fds.kategori NOT IN ('< Semua >', '< Pilih >')
  AND fds.ttd_pegawai_id = $3::varchar
  AND fds.deleted_at IS NULL
  AND fds.ds_ok = true
GROUP BY 
    fds.kategori,
    fds.ttd_pegawai_id
LIMIT $1 OFFSET $2
`

type ListTandaTanganSuratKeputusanAntreanByPNSIDParams struct {
	Limit  int32  `db:"limit"`
	Offset int32  `db:"offset"`
	PnsID  string `db:"pns_id"`
}

type ListTandaTanganSuratKeputusanAntreanByPNSIDRow struct {
	Kategori     pgtype.Text `db:"kategori"`
	TtdPegawaiID pgtype.Text `db:"ttd_pegawai_id"`
	Jumlah       int64       `db:"jumlah"`
}

func (q *Queries) ListTandaTanganSuratKeputusanAntreanByPNSID(ctx context.Context, arg ListTandaTanganSuratKeputusanAntreanByPNSIDParams) ([]ListTandaTanganSuratKeputusanAntreanByPNSIDRow, error) {
	rows, err := q.db.Query(ctx, listTandaTanganSuratKeputusanAntreanByPNSID, arg.Limit, arg.Offset, arg.PnsID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTandaTanganSuratKeputusanAntreanByPNSIDRow
	for rows.Next() {
		var i ListTandaTanganSuratKeputusanAntreanByPNSIDRow
		if err := rows.Scan(&i.Kategori, &i.TtdPegawaiID, &i.Jumlah); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTandaTanganSuratKeputusanByPNSID = `-- name: ListTandaTanganSuratKeputusanByPNSID :many
SELECT
    fds.file_id,
    p.nama as nama_pemilik_sk,
    p.nip_baru as nip_pemilik_sk,
    g.nama as nama_golongan_pemilik,
    g.nama_pangkat as pangkat_golongan_pemilik,
    rj.nama_jabatan as jabatan_pemilik,
    fds.kategori AS kategori_sk,
    fds.no_sk,
    fds.tanggal_sk,
    p.unor_id
FROM surat_keputusan fds
JOIN pegawai p ON fds.nip_sk = p.nip_baru AND p.deleted_at IS NULL
LEFT JOIN ref_unit_kerja uk ON p.unor_id = uk.id AND uk.deleted_at IS NULL
LEFT JOIN ref_golongan g ON p.gol_id = g.id AND g.deleted_at IS NULL
LEFT JOIN ref_jabatan rj on p.jabatan_instansi_id = rj.kode_jabatan and rj.deleted_at is null
WHERE fds.deleted_at IS NULL
    AND ($3::VARCHAR IS NULL
        OR $3::VARCHAR = uk.id
        OR $3::VARCHAR = uk.eselon_1
        OR $3::VARCHAR = uk.eselon_2
        OR $3::VARCHAR = uk.eselon_3
        OR $3::VARCHAR = uk.eselon_4)
    AND ($4::VARCHAR IS NULL OR p.nama ILIKE '%' || $4::VARCHAR || '%')
    AND ($5::VARCHAR IS NULL OR fds.nip_sk = $5::VARCHAR)
    AND ($6::INTEGER IS NULL OR p.gol_id = $6::INTEGER)
    AND ($7::VARCHAR IS NULL OR p.jabatan_instansi_id = $7::VARCHAR)
    AND ($8::VARCHAR is NULL OR fds.kategori ILIKE '%' || $8::VARCHAR || '%')
    AND ($9::VARCHAR IS NULL OR fds.no_sk ILIKE '%' || $9::VARCHAR || '%')
    AND fds.status_koreksi = 1 
    and ($10::integer is NULL or fds.status_ttd = $10::integer)
    AND fds.ttd_pegawai_id = $11::varchar
    AND fds.ds_ok = true
ORDER BY fds.created_at DESC
LIMIT $1 OFFSET $2
`

type ListTandaTanganSuratKeputusanByPNSIDParams struct {
	Limit       int32       `db:"limit"`
	Offset      int32       `db:"offset"`
	UnitKerjaID pgtype.Text `db:"unit_kerja_id"`
	NamaPemilik pgtype.Text `db:"nama_pemilik"`
	NipPemilik  pgtype.Text `db:"nip_pemilik"`
	GolonganID  pgtype.Int4 `db:"golongan_id"`
	JabatanID   pgtype.Text `db:"jabatan_id"`
	KategoriSk  pgtype.Text `db:"kategori_sk"`
	NoSk        pgtype.Text `db:"no_sk"`
	StatusTtd   pgtype.Int4 `db:"status_ttd"`
	PnsID       string      `db:"pns_id"`
}

type ListTandaTanganSuratKeputusanByPNSIDRow struct {
	FileID                 string      `db:"file_id"`
	NamaPemilikSk          pgtype.Text `db:"nama_pemilik_sk"`
	NipPemilikSk           pgtype.Text `db:"nip_pemilik_sk"`
	NamaGolonganPemilik    pgtype.Text `db:"nama_golongan_pemilik"`
	PangkatGolonganPemilik pgtype.Text `db:"pangkat_golongan_pemilik"`
	JabatanPemilik         pgtype.Text `db:"jabatan_pemilik"`
	KategoriSk             pgtype.Text `db:"kategori_sk"`
	NoSk                   pgtype.Text `db:"no_sk"`
	TanggalSk              pgtype.Date `db:"tanggal_sk"`
	UnorID                 pgtype.Text `db:"unor_id"`
}

func (q *Queries) ListTandaTanganSuratKeputusanByPNSID(ctx context.Context, arg ListTandaTanganSuratKeputusanByPNSIDParams) ([]ListTandaTanganSuratKeputusanByPNSIDRow, error) {
	rows, err := q.db.Query(ctx, listTandaTanganSuratKeputusanByPNSID,
		arg.Limit,
		arg.Offset,
		arg.UnitKerjaID,
		arg.NamaPemilik,
		arg.NipPemilik,
		arg.GolonganID,
		arg.JabatanID,
		arg.KategoriSk,
		arg.NoSk,
		arg.StatusTtd,
		arg.PnsID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTandaTanganSuratKeputusanByPNSIDRow
	for rows.Next() {
		var i ListTandaTanganSuratKeputusanByPNSIDRow
		if err := rows.Scan(
			&i.FileID,
			&i.NamaPemilikSk,
			&i.NipPemilikSk,
			&i.NamaGolonganPemilik,
			&i.PangkatGolonganPemilik,
			&i.JabatanPemilik,
			&i.KategoriSk,
			&i.NoSk,
			&i.TanggalSk,
			&i.UnorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBerkasSuratKeputusanSignedByID = `-- name: UpdateBerkasSuratKeputusanSignedByID :exec
UPDATE 
    surat_keputusan
SET 
    file_base64_sign = $1::text
WHERE 
    file_id = $2::varchar
`

type UpdateBerkasSuratKeputusanSignedByIDParams struct {
	FileBase64Sign string `db:"file_base64_sign"`
	ID             string `db:"id"`
}

func (q *Queries) UpdateBerkasSuratKeputusanSignedByID(ctx context.Context, arg UpdateBerkasSuratKeputusanSignedByIDParams) error {
	_, err := q.db.Exec(ctx, updateBerkasSuratKeputusanSignedByID, arg.FileBase64Sign, arg.ID)
	return err
}

const updateKorektorSuratKeputusanByID = `-- name: UpdateKorektorSuratKeputusanByID :exec
UPDATE 
    koreksi_surat_keputusan
SET 
    status_koreksi = COALESCE($1, status_koreksi),
    catatan_koreksi = COALESCE($2::text, catatan_koreksi)
WHERE 
    file_id = $3::varchar AND pegawai_korektor_id = $4::varchar
`

type UpdateKorektorSuratKeputusanByIDParams struct {
	StatusKoreksi  pgtype.Int2 `db:"status_koreksi"`
	CatatanKoreksi string      `db:"catatan_koreksi"`
	ID             string      `db:"id"`
	PnsID          string      `db:"pns_id"`
}

func (q *Queries) UpdateKorektorSuratKeputusanByID(ctx context.Context, arg UpdateKorektorSuratKeputusanByIDParams) error {
	_, err := q.db.Exec(ctx, updateKorektorSuratKeputusanByID,
		arg.StatusKoreksi,
		arg.CatatanKoreksi,
		arg.ID,
		arg.PnsID,
	)
	return err
}

const updateRiwayatSuratKeputusanNamaNipPemrosesByNIP = `-- name: UpdateRiwayatSuratKeputusanNamaNipPemrosesByNIP :exec
UPDATE riwayat_surat_keputusan
SET
    nip_pemroses = $1::varchar,
    updated_at = now()
WHERE nip_pemroses = $2::varchar AND deleted_at IS NULL
AND (
        ($1::varchar IS NOT NULL AND $1::varchar IS DISTINCT FROM nip_pemroses)
    )
`

type UpdateRiwayatSuratKeputusanNamaNipPemrosesByNIPParams struct {
	NipBaru string `db:"nip_baru"`
	Nip     string `db:"nip"`
}

func (q *Queries) UpdateRiwayatSuratKeputusanNamaNipPemrosesByNIP(ctx context.Context, arg UpdateRiwayatSuratKeputusanNamaNipPemrosesByNIPParams) error {
	_, err := q.db.Exec(ctx, updateRiwayatSuratKeputusanNamaNipPemrosesByNIP, arg.NipBaru, arg.Nip)
	return err
}

const updateStatusSuratKeputusanByID = `-- name: UpdateStatusSuratKeputusanByID :exec
UPDATE 
    surat_keputusan
SET 
    status_sk = COALESCE($1, status_sk),
    status_ttd = COALESCE($2, status_ttd),
    status_kembali = COALESCE($3, status_kembali),
    status_koreksi = COALESCE($4, status_koreksi),
    catatan = COALESCE($5::text, catatan)
WHERE 
    file_id = $6::varchar
`

type UpdateStatusSuratKeputusanByIDParams struct {
	StatusSk      pgtype.Int2 `db:"status_sk"`
	StatusTtd     pgtype.Int2 `db:"status_ttd"`
	StatusKembali pgtype.Int2 `db:"status_kembali"`
	StatusKoreksi pgtype.Int2 `db:"status_koreksi"`
	Catatan       string      `db:"catatan"`
	ID            string      `db:"id"`
}

func (q *Queries) UpdateStatusSuratKeputusanByID(ctx context.Context, arg UpdateStatusSuratKeputusanByIDParams) error {
	_, err := q.db.Exec(ctx, updateStatusSuratKeputusanByID,
		arg.StatusSk,
		arg.StatusTtd,
		arg.StatusKembali,
		arg.StatusKoreksi,
		arg.Catatan,
		arg.ID,
	)
	return err
}

const updateSuratKeputusanNamaNipPemilikByNIP = `-- name: UpdateSuratKeputusanNamaNipPemilikByNIP :exec
UPDATE surat_keputusan
SET 
    nip_sk = $1::varchar,
    nama_pemilik_sk = $2::varchar,
    updated_at = now()
WHERE nip_sk = $3::varchar AND deleted_at IS NULL
AND (
    ($1::varchar IS NOT NULL AND $1::varchar IS DISTINCT FROM nip_sk)
    OR ($2::varchar IS NOT NULL AND $2::varchar IS DISTINCT FROM nama_pemilik_sk)
)
`

type UpdateSuratKeputusanNamaNipPemilikByNIPParams struct {
	NipBaru string `db:"nip_baru"`
	Nama    string `db:"nama"`
	Nip     string `db:"nip"`
}

func (q *Queries) UpdateSuratKeputusanNamaNipPemilikByNIP(ctx context.Context, arg UpdateSuratKeputusanNamaNipPemilikByNIPParams) error {
	_, err := q.db.Exec(ctx, updateSuratKeputusanNamaNipPemilikByNIP, arg.NipBaru, arg.Nama, arg.Nip)
	return err
}

const updateSuratKeputusanNipPemrosesByNIP = `-- name: UpdateSuratKeputusanNipPemrosesByNIP :exec
UPDATE surat_keputusan
SET 
    nip_pemroses = $1::varchar,
    updated_at = now()
WHERE nip_pemroses = $2::varchar AND deleted_at IS NULL
AND (
    ($1::varchar IS NOT NULL AND $1::varchar IS DISTINCT FROM nip_pemroses)
)
`

type UpdateSuratKeputusanNipPemrosesByNIPParams struct {
	NipBaru string `db:"nip_baru"`
	Nip     string `db:"nip"`
}

func (q *Queries) UpdateSuratKeputusanNipPemrosesByNIP(ctx context.Context, arg UpdateSuratKeputusanNipPemrosesByNIPParams) error {
	_, err := q.db.Exec(ctx, updateSuratKeputusanNipPemrosesByNIP, arg.NipBaru, arg.Nip)
	return err
}
