// Code generated by sqlc. DO NOT EDIT.
// source: unit_kerja.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAkarUnitKerja = `-- name: CountAkarUnitKerja :one
SELECT COUNT(1) FROM unit_kerja
WHERE
    diatasan_id IS NULL
    AND deleted_at IS NULL
`

func (q *Queries) CountAkarUnitKerja(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAkarUnitKerja)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnitKerja = `-- name: CountUnitKerja :one
SELECT COUNT(1) FROM unit_kerja
WHERE
    (CASE WHEN $1::varchar = '' THEN true ELSE nama_unor ilike $1::varchar || '%' END)
    AND (CASE WHEN $2::varchar = '' THEN true ELSE unor_induk = $2::varchar END)
    AND deleted_at IS NULL
`

type CountUnitKerjaParams struct {
	Nama      string `db:"nama"`
	UnorInduk string `db:"unor_induk"`
}

func (q *Queries) CountUnitKerja(ctx context.Context, arg CountUnitKerjaParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnitKerja, arg.Nama, arg.UnorInduk)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnitKerjaByDiatasanID = `-- name: CountUnitKerjaByDiatasanID :one
SELECT COUNT(1) FROM unit_kerja
WHERE
    diatasan_id = $1
    AND deleted_at IS NULL
`

func (q *Queries) CountUnitKerjaByDiatasanID(ctx context.Context, diatasanID pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countUnitKerjaByDiatasanID, diatasanID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listAkarUnitKerja = `-- name: ListAkarUnitKerja :many
SELECT id, nama_unor
FROM unit_kerja
WHERE
    diatasan_id IS NULL
    AND deleted_at IS NULL
LIMIT $1 OFFSET $2
`

type ListAkarUnitKerjaParams struct {
	Limit  int32 `db:"limit"`
	Offset int32 `db:"offset"`
}

type ListAkarUnitKerjaRow struct {
	ID       string      `db:"id"`
	NamaUnor pgtype.Text `db:"nama_unor"`
}

func (q *Queries) ListAkarUnitKerja(ctx context.Context, arg ListAkarUnitKerjaParams) ([]ListAkarUnitKerjaRow, error) {
	rows, err := q.db.Query(ctx, listAkarUnitKerja, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAkarUnitKerjaRow
	for rows.Next() {
		var i ListAkarUnitKerjaRow
		if err := rows.Scan(&i.ID, &i.NamaUnor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnitKerjaByDiatasanID = `-- name: ListUnitKerjaByDiatasanID :many
SELECT 
    uk.id,
    uk.nama_unor,
    EXISTS (
        SELECT 1 
        FROM unit_kerja uk2
        WHERE 
            uk2.diatasan_id = uk.id
            AND uk2.deleted_at IS NULL
    ) as has_anak
FROM unit_kerja uk
WHERE
    uk.diatasan_id = $3
    AND uk.deleted_at IS NULL
LIMIT $1 OFFSET $2
`

type ListUnitKerjaByDiatasanIDParams struct {
	Limit      int32       `db:"limit"`
	Offset     int32       `db:"offset"`
	DiatasanID pgtype.Text `db:"diatasan_id"`
}

type ListUnitKerjaByDiatasanIDRow struct {
	ID       string      `db:"id"`
	NamaUnor pgtype.Text `db:"nama_unor"`
	HasAnak  bool        `db:"has_anak"`
}

func (q *Queries) ListUnitKerjaByDiatasanID(ctx context.Context, arg ListUnitKerjaByDiatasanIDParams) ([]ListUnitKerjaByDiatasanIDRow, error) {
	rows, err := q.db.Query(ctx, listUnitKerjaByDiatasanID, arg.Limit, arg.Offset, arg.DiatasanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnitKerjaByDiatasanIDRow
	for rows.Next() {
		var i ListUnitKerjaByDiatasanIDRow
		if err := rows.Scan(&i.ID, &i.NamaUnor, &i.HasAnak); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnitKerjaByNamaOrInduk = `-- name: ListUnitKerjaByNamaOrInduk :many
SELECT id, nama_unor
from unit_kerja
WHERE
    (CASE WHEN $3::varchar = '' THEN true ELSE nama_unor ilike $3::varchar || '%' END)
    AND (CASE WHEN $4::varchar = '' THEN true ELSE unor_induk = $4::varchar END)
    AND deleted_at IS NULL
LIMIT $1 OFFSET $2
`

type ListUnitKerjaByNamaOrIndukParams struct {
	Limit     int32  `db:"limit"`
	Offset    int32  `db:"offset"`
	Nama      string `db:"nama"`
	UnorInduk string `db:"unor_induk"`
}

type ListUnitKerjaByNamaOrIndukRow struct {
	ID       string      `db:"id"`
	NamaUnor pgtype.Text `db:"nama_unor"`
}

func (q *Queries) ListUnitKerjaByNamaOrInduk(ctx context.Context, arg ListUnitKerjaByNamaOrIndukParams) ([]ListUnitKerjaByNamaOrIndukRow, error) {
	rows, err := q.db.Query(ctx, listUnitKerjaByNamaOrInduk,
		arg.Limit,
		arg.Offset,
		arg.Nama,
		arg.UnorInduk,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnitKerjaByNamaOrIndukRow
	for rows.Next() {
		var i ListUnitKerjaByNamaOrIndukRow
		if err := rows.Scan(&i.ID, &i.NamaUnor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnitKerjaHierarchy = `-- name: ListUnitKerjaHierarchy :many
with recursive unit_kerja_path as (
    -- anchor
    select uk.id, uk.nama_unor, uk.diatasan_id, 1 as depth
    from unit_kerja uk
    where uk.id = $1 and uk.deleted_at is null

    union all

    -- recursive
    select uk.id, uk.nama_unor, uk.diatasan_id, ukp.depth + 1
    from unit_kerja uk
    join unit_kerja_path ukp on uk.id = ukp.diatasan_id
    where ukp.depth < 10 and uk.deleted_at is null
)
select id, nama_unor from unit_kerja_path
`

type ListUnitKerjaHierarchyRow struct {
	ID       string      `db:"id"`
	NamaUnor pgtype.Text `db:"nama_unor"`
}

func (q *Queries) ListUnitKerjaHierarchy(ctx context.Context, id string) ([]ListUnitKerjaHierarchyRow, error) {
	rows, err := q.db.Query(ctx, listUnitKerjaHierarchy, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnitKerjaHierarchyRow
	for rows.Next() {
		var i ListUnitKerjaHierarchyRow
		if err := rows.Scan(&i.ID, &i.NamaUnor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnitKerjaHierarchyByNIP = `-- name: ListUnitKerjaHierarchyByNIP :many
with recursive unit_kerja_path as (
    -- anchor
    select uk.id, uk.nama_unor, uk.diatasan_id, 1 as depth
    from unit_kerja uk
    where uk.id = (SELECT unor_id FROM pegawai where nip_baru = $1::varchar LIMIT 1) and uk.deleted_at is null

    union all

    -- recursive
    select uk.id, uk.nama_unor, uk.diatasan_id, ukp.depth + 1
    from unit_kerja uk
    join unit_kerja_path ukp on uk.id = ukp.diatasan_id
    where ukp.depth < 10 and uk.deleted_at is null
)
select id, nama_unor from unit_kerja_path
`

type ListUnitKerjaHierarchyByNIPRow struct {
	ID       string      `db:"id"`
	NamaUnor pgtype.Text `db:"nama_unor"`
}

func (q *Queries) ListUnitKerjaHierarchyByNIP(ctx context.Context, nip string) ([]ListUnitKerjaHierarchyByNIPRow, error) {
	rows, err := q.db.Query(ctx, listUnitKerjaHierarchyByNIP, nip)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnitKerjaHierarchyByNIPRow
	for rows.Next() {
		var i ListUnitKerjaHierarchyByNIPRow
		if err := rows.Scan(&i.ID, &i.NamaUnor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnitKerjaLengkapByIDs = `-- name: ListUnitKerjaLengkapByIDs :many
with recursive unit_kerja_path as (
    -- anchor
    select 
        uk.id,
        uk.id as start_id,
        uk.diatasan_id,
        uk.nama_unor::text as path,
        1 as depth
    from unit_kerja uk
    where uk.id = ANY($1::varchar[]) AND uk.deleted_at is null

    union all

    -- recursive
    select 
        uk.id,
        ukp.start_id,
        uk.diatasan_id,
        ukp.path || ' - ' || uk.nama_unor, 
        ukp.depth + 1
    from unit_kerja uk
    join unit_kerja_path ukp
      on uk.id = ukp.diatasan_id
    where ukp.depth < 10 and uk.deleted_at is null
)

select 
    start_id as id,
    path as nama_unor_lengkap
from (
    select id, start_id, diatasan_id, path, depth, row_number() over (partition by start_id order by depth desc) as rn
    from unit_kerja_path
) t
where rn = 1
`

type ListUnitKerjaLengkapByIDsRow struct {
	ID              string `db:"id"`
	NamaUnorLengkap string `db:"nama_unor_lengkap"`
}

func (q *Queries) ListUnitKerjaLengkapByIDs(ctx context.Context, ids []string) ([]ListUnitKerjaLengkapByIDsRow, error) {
	rows, err := q.db.Query(ctx, listUnitKerjaLengkapByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnitKerjaLengkapByIDsRow
	for rows.Next() {
		var i ListUnitKerjaLengkapByIDsRow
		if err := rows.Scan(&i.ID, &i.NamaUnorLengkap); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
