// Code generated by sqlc. DO NOT EDIT.
// source: usulan_perubahan_data.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPendingUsulanPerubahanData = `-- name: CountPendingUsulanPerubahanData :one
select count(1)
from usulan_perubahan_data upd
join pegawai p on p.nip_baru = upd.nip and p.deleted_at is null
where upd.status = 'Diusulkan' and upd.deleted_at is null
  and ($1::varchar = '' or p.nama ilike '%' || $1::varchar || '%')
  and ($2::varchar = '' or upd.nip like $2::varchar || '%')
  and ($3::varchar = '' or upd.jenis_data = $3::varchar)
  and ($4::varchar = '' or p.jabatan_instansi_id = $4::varchar)
  and ($5::int2 is null or p.gol_id = $5::int2)
  and ($6::varchar = '' or p.unor_id = $6::varchar)
`

type CountPendingUsulanPerubahanDataParams struct {
	Nama        string      `db:"nama"`
	Nip         string      `db:"nip"`
	JenisData   string      `db:"jenis_data"`
	KodeJabatan string      `db:"kode_jabatan"`
	GolonganID  pgtype.Int2 `db:"golongan_id"`
	UnitKerjaID string      `db:"unit_kerja_id"`
}

func (q *Queries) CountPendingUsulanPerubahanData(ctx context.Context, arg CountPendingUsulanPerubahanDataParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingUsulanPerubahanData,
		arg.Nama,
		arg.Nip,
		arg.JenisData,
		arg.KodeJabatan,
		arg.GolonganID,
		arg.UnitKerjaID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadUsulanPerubahanDataByNIP = `-- name: CountUnreadUsulanPerubahanDataByNIP :one
select count(1)
from usulan_perubahan_data
where nip = $1 and jenis_data = $2
  and read_at is null and deleted_at is null
`

type CountUnreadUsulanPerubahanDataByNIPParams struct {
	Nip       string `db:"nip"`
	JenisData string `db:"jenis_data"`
}

func (q *Queries) CountUnreadUsulanPerubahanDataByNIP(ctx context.Context, arg CountUnreadUsulanPerubahanDataByNIPParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadUsulanPerubahanDataByNIP, arg.Nip, arg.JenisData)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUsulanPerubahanData = `-- name: CreateUsulanPerubahanData :one
insert into usulan_perubahan_data
  (nip, jenis_data, data_id, perubahan_data, action) values
  ($1, $2, $3, $4, $5)
returning id
`

type CreateUsulanPerubahanDataParams struct {
	Nip           string      `db:"nip"`
	JenisData     string      `db:"jenis_data"`
	DataID        pgtype.Text `db:"data_id"`
	PerubahanData []byte      `db:"perubahan_data"`
	Action        string      `db:"action"`
}

func (q *Queries) CreateUsulanPerubahanData(ctx context.Context, arg CreateUsulanPerubahanDataParams) (int64, error) {
	row := q.db.QueryRow(ctx, createUsulanPerubahanData,
		arg.Nip,
		arg.JenisData,
		arg.DataID,
		arg.PerubahanData,
		arg.Action,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteUsulanPerubahanData = `-- name: DeleteUsulanPerubahanData :exec
update usulan_perubahan_data
set deleted_at = now()
where id = $1 and jenis_data = $2 and deleted_at is null
`

type DeleteUsulanPerubahanDataParams struct {
	ID        int64  `db:"id"`
	JenisData string `db:"jenis_data"`
}

func (q *Queries) DeleteUsulanPerubahanData(ctx context.Context, arg DeleteUsulanPerubahanDataParams) error {
	_, err := q.db.Exec(ctx, deleteUsulanPerubahanData, arg.ID, arg.JenisData)
	return err
}

const getUsulanPerubahanData = `-- name: GetUsulanPerubahanData :one
select
  upd.id,
  upd.nip,
  upd.jenis_data,
  upd.data_id,
  upd.perubahan_data,
  upd.action,
  upd.status,
  upd.catatan,
  upd.created_at,
  p.gelar_depan as gelar_depan_pegawai,
  p.gelar_belakang as gelar_belakang_pegawai,
  p.nama as nama_pegawai,
  case when kh.is_pppk then g.gol_pppk else g.nama end as golongan_pegawai,
  j.nama_jabatan as jabatan_pegawai,
  p.foto as foto_pegawai,
  case
    when p.status_cpns_pns = 'P' then 'PNS'
    when p.status_cpns_pns = 'C' then 'CPNS'
    else p.status_cpns_pns
  end as status_pns_pegawai,
  p.unor_id as unor_id_pegawai
from usulan_perubahan_data upd
join pegawai p on p.nip_baru = upd.nip and p.deleted_at is null
left join ref_jabatan j on j.kode_jabatan = p.jabatan_instansi_id and j.deleted_at is null
left join ref_golongan g on g.id = p.gol_id and g.deleted_at is null
left join ref_kedudukan_hukum kh on kh.id = p.kedudukan_hukum_id and kh.deleted_at is null
where upd.id = $1 and upd.jenis_data = $2 and upd.deleted_at is null
`

type GetUsulanPerubahanDataParams struct {
	ID        int64  `db:"id"`
	JenisData string `db:"jenis_data"`
}

type GetUsulanPerubahanDataRow struct {
	ID                   int64              `db:"id"`
	Nip                  string             `db:"nip"`
	JenisData            string             `db:"jenis_data"`
	DataID               pgtype.Text        `db:"data_id"`
	PerubahanData        []byte             `db:"perubahan_data"`
	Action               string             `db:"action"`
	Status               string             `db:"status"`
	Catatan              pgtype.Text        `db:"catatan"`
	CreatedAt            pgtype.Timestamptz `db:"created_at"`
	GelarDepanPegawai    pgtype.Text        `db:"gelar_depan_pegawai"`
	GelarBelakangPegawai pgtype.Text        `db:"gelar_belakang_pegawai"`
	NamaPegawai          pgtype.Text        `db:"nama_pegawai"`
	GolonganPegawai      interface{}        `db:"golongan_pegawai"`
	JabatanPegawai       pgtype.Text        `db:"jabatan_pegawai"`
	FotoPegawai          pgtype.Text        `db:"foto_pegawai"`
	StatusPnsPegawai     interface{}        `db:"status_pns_pegawai"`
	UnorIDPegawai        pgtype.Text        `db:"unor_id_pegawai"`
}

func (q *Queries) GetUsulanPerubahanData(ctx context.Context, arg GetUsulanPerubahanDataParams) (GetUsulanPerubahanDataRow, error) {
	row := q.db.QueryRow(ctx, getUsulanPerubahanData, arg.ID, arg.JenisData)
	var i GetUsulanPerubahanDataRow
	err := row.Scan(
		&i.ID,
		&i.Nip,
		&i.JenisData,
		&i.DataID,
		&i.PerubahanData,
		&i.Action,
		&i.Status,
		&i.Catatan,
		&i.CreatedAt,
		&i.GelarDepanPegawai,
		&i.GelarBelakangPegawai,
		&i.NamaPegawai,
		&i.GolonganPegawai,
		&i.JabatanPegawai,
		&i.FotoPegawai,
		&i.StatusPnsPegawai,
		&i.UnorIDPegawai,
	)
	return i, err
}

const listPendingUsulanPerubahanData = `-- name: ListPendingUsulanPerubahanData :many
select
  upd.id,
  upd.nip,
  upd.jenis_data,
  upd.created_at,
  p.gelar_depan as gelar_depan_pegawai,
  p.gelar_belakang as gelar_belakang_pegawai,
  p.nama as nama_pegawai,
  p.unor_id as unor_id_pegawai
from usulan_perubahan_data upd
join pegawai p on p.nip_baru = upd.nip and p.deleted_at is null
where upd.status = 'Diusulkan' and upd.deleted_at is null
  and ($3::varchar = '' or p.nama ilike '%' || $3::varchar || '%')
  and ($4::varchar = '' or upd.nip like $4::varchar || '%')
  and ($5::varchar = '' or upd.jenis_data = $5::varchar)
  and ($6::varchar = '' or p.jabatan_instansi_id = $6::varchar)
  and ($7::int2 is null or p.gol_id = $7::int2)
  and ($8::varchar = '' or p.unor_id = $8::varchar)
order by upd.created_at asc
limit $1 offset $2
`

type ListPendingUsulanPerubahanDataParams struct {
	Limit       int32       `db:"limit"`
	Offset      int32       `db:"offset"`
	Nama        string      `db:"nama"`
	Nip         string      `db:"nip"`
	JenisData   string      `db:"jenis_data"`
	KodeJabatan string      `db:"kode_jabatan"`
	GolonganID  pgtype.Int2 `db:"golongan_id"`
	UnitKerjaID string      `db:"unit_kerja_id"`
}

type ListPendingUsulanPerubahanDataRow struct {
	ID                   int64              `db:"id"`
	Nip                  string             `db:"nip"`
	JenisData            string             `db:"jenis_data"`
	CreatedAt            pgtype.Timestamptz `db:"created_at"`
	GelarDepanPegawai    pgtype.Text        `db:"gelar_depan_pegawai"`
	GelarBelakangPegawai pgtype.Text        `db:"gelar_belakang_pegawai"`
	NamaPegawai          pgtype.Text        `db:"nama_pegawai"`
	UnorIDPegawai        pgtype.Text        `db:"unor_id_pegawai"`
}

func (q *Queries) ListPendingUsulanPerubahanData(ctx context.Context, arg ListPendingUsulanPerubahanDataParams) ([]ListPendingUsulanPerubahanDataRow, error) {
	rows, err := q.db.Query(ctx, listPendingUsulanPerubahanData,
		arg.Limit,
		arg.Offset,
		arg.Nama,
		arg.Nip,
		arg.JenisData,
		arg.KodeJabatan,
		arg.GolonganID,
		arg.UnitKerjaID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingUsulanPerubahanDataRow
	for rows.Next() {
		var i ListPendingUsulanPerubahanDataRow
		if err := rows.Scan(
			&i.ID,
			&i.Nip,
			&i.JenisData,
			&i.CreatedAt,
			&i.GelarDepanPegawai,
			&i.GelarBelakangPegawai,
			&i.NamaPegawai,
			&i.UnorIDPegawai,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadUsulanPerubahanDataByNIP = `-- name: ListUnreadUsulanPerubahanDataByNIP :many
select
  id,
  jenis_data,
  data_id,
  perubahan_data,
  action,
  status,
  catatan
from usulan_perubahan_data
where nip = $1 and jenis_data = $2
  and read_at is null and deleted_at is null
order by updated_at desc
limit $3 offset $4
`

type ListUnreadUsulanPerubahanDataByNIPParams struct {
	Nip       string `db:"nip"`
	JenisData string `db:"jenis_data"`
	Limit     int32  `db:"limit"`
	Offset    int32  `db:"offset"`
}

type ListUnreadUsulanPerubahanDataByNIPRow struct {
	ID            int64       `db:"id"`
	JenisData     string      `db:"jenis_data"`
	DataID        pgtype.Text `db:"data_id"`
	PerubahanData []byte      `db:"perubahan_data"`
	Action        string      `db:"action"`
	Status        string      `db:"status"`
	Catatan       pgtype.Text `db:"catatan"`
}

func (q *Queries) ListUnreadUsulanPerubahanDataByNIP(ctx context.Context, arg ListUnreadUsulanPerubahanDataByNIPParams) ([]ListUnreadUsulanPerubahanDataByNIPRow, error) {
	rows, err := q.db.Query(ctx, listUnreadUsulanPerubahanDataByNIP,
		arg.Nip,
		arg.JenisData,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnreadUsulanPerubahanDataByNIPRow
	for rows.Next() {
		var i ListUnreadUsulanPerubahanDataByNIPRow
		if err := rows.Scan(
			&i.ID,
			&i.JenisData,
			&i.DataID,
			&i.PerubahanData,
			&i.Action,
			&i.Status,
			&i.Catatan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAsReadUsulanPerubahanData = `-- name: MarkAsReadUsulanPerubahanData :exec
update usulan_perubahan_data
set read_at = now()
where id = $1 and jenis_data = $2 and deleted_at is null
`

type MarkAsReadUsulanPerubahanDataParams struct {
	ID        int64  `db:"id"`
	JenisData string `db:"jenis_data"`
}

func (q *Queries) MarkAsReadUsulanPerubahanData(ctx context.Context, arg MarkAsReadUsulanPerubahanDataParams) error {
	_, err := q.db.Exec(ctx, markAsReadUsulanPerubahanData, arg.ID, arg.JenisData)
	return err
}

const updateStatusUsulanPerubahanData = `-- name: UpdateStatusUsulanPerubahanData :exec
update usulan_perubahan_data
set
  status = $3,
  catatan = $4,
  updated_at = now()
where id = $1 and jenis_data = $2 and deleted_at is null
`

type UpdateStatusUsulanPerubahanDataParams struct {
	ID        int64       `db:"id"`
	JenisData string      `db:"jenis_data"`
	Status    string      `db:"status"`
	Catatan   pgtype.Text `db:"catatan"`
}

func (q *Queries) UpdateStatusUsulanPerubahanData(ctx context.Context, arg UpdateStatusUsulanPerubahanDataParams) error {
	_, err := q.db.Exec(ctx, updateStatusUsulanPerubahanData,
		arg.ID,
		arg.JenisData,
		arg.Status,
		arg.Catatan,
	)
	return err
}
