// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	GetChildrenByEmployeeID(ctx context.Context, pnsID sql.NullString) ([]GetChildrenByEmployeeIDRow, error)
	GetEmployeeFamilyData(ctx context.Context, id int32) (GetEmployeeFamilyDataRow, error)
	GetParentsByEmployeeID(ctx context.Context, pnsID sql.NullString) ([]GetParentsByEmployeeIDRow, error)
	GetSpouseByEmployeeID(ctx context.Context, pnsID sql.NullString) (GetSpouseByEmployeeIDRow, error)
}

var _ Querier = (*Queries)(nil)
